### PR TITLE
Create ghstudent-ecc.json

### PR DESCRIPTION
**Pull request by ecc-doug**
NASA site was down - couldn't get coords.

### CODE REVIEW

**Comment by ecc-doug** [comment]
this is a test

**Comment by Personallyon** [comment]
#4601

**Comment by crichID** [comment]
@ecc-doug we replaced the link for the NASA site so you can get your coordinates now if you would like to try again https://landsatlook.usgs.gov/

**Comment by shajanjp** [comment]
Your pin should be in this format.
```
---
githubHandle: <YOUR_USER_NAME>
latitude: <LATITUDE>
longitude: <LONGITUDE>
---
```

**Comment by hectorsector** [comment]
@ecc-doug thank you for checking out our [on-demand classes](https://services.github.com/on-demand/). Since this file is not valid per the examples in the course, I am going to go ahead and close this Pull Request. If you would like to complete the activity, please feel free to re-open this Pull Request or start again. If you have any questions, please let us know!

**Pull request closed without merging**
