### PR TITLE
Create Lasersniped.json

### LINKED ISSUE #20411: Please Add me
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by pinkshdw**
#first try at this
@githubteacher 
closes #20411

### CODE REVIEW

**Comment by Fswoop7** [comment]
You can do it!

**Comment by tpsoe** [comment]
@pinkshdw this is good 🎉

**Comment by MikaelLennefors** [comment]
Good work!

**Comment by chrt** [comment]
Great!

**Comment by 0Redfeather** [comment]
I believe in you!

**Comment by KenielYao** [comment]
looks great!

**Pull request closed without merging**
