### PR TITLE
Create greyhead47.json

### PR DESCRIPTION
**Pull request by greyhead47**
Coordinates added, thanks @githubteacher

### CODE REVIEW

**Comment by brianamarie** [comment]
Hi @greyhead47! Make sure the first and last line of your file has `---`. Let me know if you need any help! 😄

**Comment by marcorod** [comment]
Hey @greyhead47, remember to add your number issue to the pull request message.

**Comment by brianamarie** [comment]
Hi @greyhead47! This looks great, go ahead and merge! 😄

**Comment by brianamarie** [comment]
Hi @jlabuac, please do not merge other people's pull requests.

**Pull request merged**
