### PR TITLE
Add naythiha's pin to the map

### LINKED ISSUE #8565: Add me!
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by naythiha**
Adding Mandalay to the map!

closes #8565

### CODE REVIEW

**Comment by joshmorel** [comment]
Hey @nayafia welcome. Looks like you need the coordinates to make Travis happy:

```
---
githubHandle: YOUR-USERNAME
latitude: YOUR_LATITUDE
longitude: YOUR_LONGITUDE
---
```

**Comment by nayafia** [comment]
Think you were trying to tag @naythiha :wink:

**Comment by cdevitasuse** [comment]
I show the coordinates as 21.9588° N, 96.0891° E

**Comment by alanofbrent** [comment]
Hi @naythiha.  Good job.  All your code checks have passed, you can now merge your pull request by clicking the green button below.  Afterwards, the process is complete when you delete your branch with the purple button that pops up.

**Comment by dgr-goutham** [comment]
hey good work @naythiha all your checks has passed its good to merge your code

**Comment by Sirhurryup** [comment]
@naythiha This looks amazing 👍

**Pull request merged**
