### PR TITLE
add kkrr6 pin to the map!

### PR DESCRIPTION
**Pull request by kkrr6**
On the map?

### CODE REVIEW

**Comment by jquiro12** [comment]
Hi! i belive the map doesn't work. :'(

**Comment by jquiro12** [comment]
Try  you submmit whit this.

---
githubHandle: kkrr6
latitude: 44.092414
longitude: 123.138570
---

**Comment by brianamarie** [comment]
Hi @kkrr6!   Make sure the file is named `_pins/` at the beginning, and has `.json` at the end.
 Capitalization counts! 😉

**Comment by crichID** [comment]
@kkrr6 I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/2814/commits/49ae22a859e83278236d4c75d258fc4ca3a6c79a. Please take a quick look at the changes. Once the tests have finished running, please feel free to click the big green **Merge pull request** button. If you haven't merged it by January 27th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
