### PR TITLE
Add new map pin

### PR DESCRIPTION
**Pull request by atticula**
Any feedback is appreciated!

### CODE REVIEW

**Comment by tnelsen** [comment]
Good job!

**Comment by crichID** [comment]
@jr-cologne I went ahead and fixed the two syntax issues in this file! Can you please approve these changes?

@atticula I went ahead and fixed the file name in  https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/2180/commits/7eca8046341cfc3dc70732eccbb0faad043913c9 and removed the extra spaces in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/2180/commits/11d4065ed699b9f1636df195a91677316dd8acf6. Please take a quick look at the changes. Once the tests have finished running and @jr-cologne has approved the changes, please feel free to click the big green **Merge pull request** button. If you haven't merged it by 12/22/2016, I will go ahead and do it just to keep the repository clean!

**Comment by cuent** [comment]
This is working this PR could be merged. :+1:

**Comment by ezeetester** [comment]
All the best!

**Pull request merged**
