### PR TITLE
Create vicamc85.json

### PR DESCRIPTION
**Pull request by vicamc85**
I'm trying to add my pin :D

### CODE REVIEW

**Comment by davidnhz** [comment]
👍

**Comment by kotality** [comment]
👍

**Comment by tradfabio** [comment]
**Nice!**

**Comment by crichID** [comment]
@vicamc85 your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on July 7th.

**Pull request merged**
