### PR TITLE
Created pin for jcombs0929

### PR DESCRIPTION
**Pull request by jcombs0929**
@githubteacher Please add my pin to the map.

This pull request closes #3073

### CODE REVIEW

**Comment by afaaqalam** [comment]
👍  Nice work! @jcombs0929

**Comment by jcombs0929** [comment]
@githubteacher Travis CI fails on the first check but passes on the second. I check the details and it fails due to Jokerevil1611.json's pin. I'm having trouble understanding what I'm doing wrong here.

**Comment by crichID** [comment]
@jcombs0929 this is actually a tricky situation that I am trying to fix. Basically what happened is a bunch of pins were added to the repository that were broken. When you created your branch, those pins were part of your history! So when you created your pull request and the tests started to run, it saw those broken files and failed.

I have actually fixed all of those files on master already and I am just working on back-porting the fixes to all of the open branches. I will go ahead and do yours now so and you should be able to merge after that! Give me 5 minutes and it will be done!

**Comment by crichID** [comment]
@jcombs0929 all fixed! Feel free to click the big green **Merge pull request** button!

**Comment by jcombs0929** [comment]
@crichID Thanks! That was my original thought too after viewing several closed pull requests.

**Pull request merged**
