### PR TITLE
tercer intento

### PR DESCRIPTION
**Pull request by norageek**
adding GD to the map 
cloes #904

### CODE REVIEW

**Comment by davidnhz** [comment]
👍

**Comment by crichID** [comment]
@norageek this looks great! You just need to add `---` on the first and last line of your file and your checks should pass!

**Comment by davidnhz** [comment]
You need to add `---` at the beginning and at the end of the file.

**Comment by davidnhz** [comment]
💯

**Comment by crichID** [comment]
@norageek your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on July 7th.

**Pull request merged**
