### PR TITLE
Create TERIYAKI

### PR DESCRIPTION
**Pull request by admjgptw1357**
Teriyaki is awesome!!

### CODE REVIEW

**Comment by frinko** [comment]
I love teriyaki! 👍

**Comment by musicm122** [comment]
@admjgptw1357 Teriyaki rocks!

**Comment by hectorsector** [comment]
@admjgptw1357 looks like you're ready to merge! Go ahead when you're ready.

**Comment by zdx91** [comment]
@admjgptw1357 It looks great!👍

**Pull request merged**
