### PR TITLE
Add cjbear's coordinates

### PR DESCRIPTION
**Pull request by cjbear**

### CODE REVIEW

**Comment by C6H10O5n** [comment]
@cjbear great work

**Comment by crichID** [comment]
@cjbear your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on August 11th.

**Comment by BillBridge** [comment]
@cjbear : nice location. 🥇 
This closes #9391

**Comment by sharon-lin** [comment]
@cjbear Looks great! 👍

**Pull request merged**
