### PR TITLE
Add MadhavBahlMD's pin to the map

### LINKED ISSUE #15132: Please Add Me
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by MadhavBahlMD**
Adding Vellore to the map.

Closes #15132

### CODE REVIEW

**Comment by nC3rtainity** [comment]
It appears to be correct, why the Travis Cl build failed though? 😕

**Comment by MadhavBahlMD** [comment]
I have no clue why this happened, any solutions?

**Comment by nC3rtainity** [comment]
No I couldn't find any reasons.. some strange anomaly 😕

**Comment by MadhavBahlMD** [comment]
I will give it another try then

**Comment by Schiavi13** [comment]
@MadhavBahlMD I deleted the identation, let's see if that's the problem

**Comment by Schiavi13** [comment]
@MadhavBahlMD Apparently it was

**Comment by MadhavBahlMD** [comment]
Thanks @Schiavi13 This solved the problem :)

**Pull request merged**
