### PR TITLE
Add gudivada,andra pradesh,india to map

### LINKED ISSUE #651: Adding Gudivada,India
## Adding Gudivada,Andhra Pradesh ,india to the map

Hi everyone! This issue is to track the addition of Gudivada to the map, which can be found at:

- Longitude: 16.441025
- Latitude: 80.992633

### PR DESCRIPTION
**Pull request by khari512**
- Added Gudivada,Andra Pradesh,India to the map.

- @githubteacher 

- Closes #651

### CODE REVIEW

**Comment by MadeleineS** [comment]
Looks good!

**Comment by catherbd** [comment]
great!

**Comment by VeryHacker** [comment]
good

**Comment by jliao2011** [comment]
Nice!

**Comment by PMcComas15** [comment]
Awesome! :+1:

**Comment by eosogge16** [comment]
yeah 👍

**Comment by githubteacher** [comment]
@khari512 we would love to see your pin on our map. We just need to make a few changes to your file!

1. Change the file name from `_pins/khari512` to `_pins/khari512.json`. You can do that by clicking the Files Changed tab at the top of this pull request and then clicking the pencil icon at the top right of the file. Enter the new file name and then commit your changes.
2. Add a series of three dashes `---` to the first line of the file and after the last line. Your final file should look like the instructions in part 3 below:

screen-shot-2016-10-11-at-10 01 58-am

**Pull request merged**
