### PR TITLE
Create yeonyc.jason

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by shajanjp** [comment]
@gomfa Nice. but instead of username you added your email ID. Please fix that. If you get stuck anywhere, feel free to ask for help. :relaxed:

**Comment by hectorsector** [comment]
@gomfa you've got some good advice from @shajanjp ☝️

**Comment by hollenberry** [comment]
Hey @gomfa  ! Looks like you've gotten a ton of great advice above! If you take action on those changes, you'll be set. 👍

Please let us know if you need any help! We'll be closing this out to keep the repository clean if there's no action or conversation within the week.

**Comment by crichID** [comment]
@gomfa I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/4966/commits/f3dc870b6105acb5271986346b24727951cb7fe1. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by April 21st, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
