### PR TITLE
Marissa vara boston

### PR DESCRIPTION
**Pull request by marissa-vara**
Test file and my file to upload my pin to the map

### CODE REVIEW

**Comment by kylemacey** [comment]
Hi @marissa-vara! The `testFile` you created in the root of the repository is causing the tests to fail We try to keep the root of the repository clear of user created files. If you remove that file, the tests should pass. Please let me know if I can be of any more help!

**Comment by marissa-vara** [comment]
I just deleted the test file, now what?

**Comment by kylemacey** [comment]
@marissa-vara Sorry, I missed that `marissa-vara.json` is also in the root of the repository. Try moving it to the `_pins` directory. Once that's done, the tests should pass (you'll get a green check next to your commit) and you'll be able to merge your pull request.

**Comment by marissa-vara** [comment]
@kylemacey how do i move the file

**Comment by kylemacey** [comment]
> @kylemacey how do i move the file

@marissa-vara If using the web interface on GitHub.com, the easiest way is to rename the file from `marissa-vara.json` to `_pins/marissa-vara.json`. This will put the file in the `_pins` directory.

I see you've deleted and recreated the file. This should work fine as well. Sorry for not getting to you sooner.

**Comment by marissa-vara** [comment]
@kylemacey i deleted and moved the file

**Comment by kylemacey** [comment]
> @kylemacey i deleted and moved the file

@marissa-vara Very good. It looks like Travis-CI, which runs our automated tests, is taking a minute to pick up the changes. I'll check back in again shortly to make sure everything is going smoothly.

**Pull request merged**
