### PR TITLE
pleas add githubjuconbo pin to the map

### PR DESCRIPTION
**Pull request by Jucon**
adding sf to the map!

### CODE REVIEW

**Comment by hollenberry** [comment]
Very close @Jucon ! You mostly just need to double-check your capitalization! Latitude and longitude should be written all lowercase, and githubHandle is camel cased.

If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions!

**Comment by Jucon** [comment]
Thanks man!! I just didn't understand what was wrong.

El 18 may 2017, a las 19:12, Eric Hollenberry <notifications@github.com<mailto:notifications@github.com>> escribió:


Very close @Jucon<https://github.com/jucon> ! You mostly just need to double-check your capitalization! Latitude and longitude should be written all lowercase, and githubHandle is camel cased.

If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions!

**Comment by hollenberry** [comment]
> Thanks man!! I just didn't understand what was wrong.

No problem! Let me know if you need help making a fix.

**Comment by Jucon** [comment]
Cheers!

El 18 may 2017, a las 19:55, Eric Hollenberry <notifications@github.com<mailto:notifications@github.com>> escribió:


Thanks man!! I just didn't understand what was wrong.

No problem! Let me know if you need help making a fix.

**Comment by crichID** [comment]
@Jucon I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/6712/commits/bd8b6e3d0ef565ae6c0ce377681c0b5475719b20. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by May 26th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
