### PR TITLE
TUfreiberg

### PR DESCRIPTION
**Pull request by Miladkhaghanirad**
Adding freiberg to the map!

closes #13952

### CODE REVIEW

**Comment by jackkolb** [comment]
nice job :)!

**Comment by Roshankd1** [comment]
hi @Miladkhaghanirad 

try closes #13952 instead of #3

**Comment by Miladkhaghanirad** [comment]
@githubstudent Why it doesn't work?What's wrong with that?Its very complicated and not user friendly.

**Comment by aravindharinair** [comment]
Hi. Try tagging @githubteacher

**Pull request merged**
