### PR TITLE
adding meierjp57's coordinates

### PR DESCRIPTION
**Pull request by meierjp57**
@githubteacher - please add my coordinates to the map

closes issue #8348

### CODE REVIEW

**Comment by meierjp57** [comment]
@githubteacher - after looking at the Travis-CI log, the only thing I can think of why the build is failing is that my branch is named "meierjp57_Cumming" and not "meierjp57-Cumming" (I used an underscore and not a dash). Is that the issue? I mean I copied the file contents and added the coordinates. Can a branch be renamed or does it have to be dropped/recreated?

**Comment by brianamarie** [comment]
@meierjp57 Great question. The test feedback definitely isn't the easiest thing to read. Based on [these lines](https://travis-ci.org/githubschool/open-enrollment-classes-introduction-to-github/builds/250842554#L410-L479) I think the problem is the name of the directory. Right now, your file is `/pins/meierjp57.json`. Try changing it to `/_pins/meierjp57.json`, and see if that helps at all. 😄  Let me know if you want or need any help.

**Comment by brianamarie** [comment]
Also @meierjp57, it's worth noting that if you don't have time to update this pull request by the end of next week, one of the GitHub trainers will go ahead and do it for you and merge it in to keep the repository clean. 😊

**Comment by LuluChenpku** [comment]
@meierjp57  That looks great! Pretty cool! 🎉

**Comment by beardofedu** [comment]
@meierjp57 I deleted the file in the `pins` folder, since you just need to add 1 file in the `_pins` folder, like you have done. Hopefully this allows your test to pass.

**Pull request merged**
