### PR TITLE
Mytest misson

### PR DESCRIPTION
**Pull request by mide70029**
@mide70029, try again.

close issue #3629

### CODE REVIEW

**Comment by mide70029** [comment]
OK?

**Comment by mihamerstan** [comment]
@mide70029  I believe the issue is that the extension should be .json not .jason

Try going back to that!

**Comment by Funce** [comment]
My thoughts exactly @mide70029 
You seem to have the hang of fixing things up yourself.

**Comment by brianamarie** [comment]
Hi @mide70029!   Make sure the file is named `_pins/` at the beginning, and has `.json` at the end. Let me know if you need any help!

**Comment by brianamarie** [comment]
Hi @mide70029! I went ahead and made some changes. Since it's been open for a while, I'm going to merge, too. Nice work!

**Pull request merged**
