### PR TITLE
Create Ckryix.json

### PR DESCRIPTION
**Pull request by Ckryix2014**
Well, I'm sure I'm following right phase so far.

@githubteacher 

closes#3814

### CODE REVIEW

**Comment by Ckryix2014** [comment]
Well, Thanks for helping me so far :)

**Comment by Ckryix2014** [comment]
Well, can anyone help my dumbass ability to pass the checks? I don't think I understand what I did wrong.

**Comment by Ckryix2014** [comment]
Well, I hope I can figure out eventually. 

@githubteacher 

closes #3814

**Comment by brianamarie** [comment]
Hi @Ckryix2014! Try adding a space after each colon before the key value.

**Comment by Ckryix2014** [comment]
Thanks for help @brianamarie I did what you said earlier about the adding a space after each colon but, for some reasons, I still got the error about the trailing spaces. Any advice? sorry for my dull understanding again.

**Comment by brianamarie** [comment]
@Ckryix2014 You have nothing to apologize for! Try editing the file and deleting any extra spaces at the end of each line, except for the last line, which should have a line break so line 6 is empty.

**Comment by brianamarie** [comment]
🎉

**Pull request merged**
