### PR TITLE
Adding Maggie323 coordinates2

### PR DESCRIPTION
**Pull request by Maggie323**
Tab: 'Work on GitHub'
Thanks for adding me @githubteacher 

This pull request closes #10542

### CODE REVIEW

**Comment by Maggie323** [comment]
@githubteacher 
Hi, I received the message **"*All checks have failed*"**. 
What does this mean?

**Comment by Maggie323** [comment]
@githubteacher 
Please help! I'm not sure why this wont merge.

**Comment by zapper123** [comment]
@Maggie323  I can't see your issue 10542 ,did you close it?

**Comment by Maggie323** [comment]
open #10542 

@zapper123 I think I've opened it now. Can you take an look? I still see the **All checks have failed** message.

**Comment by zapper123** [comment]
@Maggie323  I think you were suppose to have an issue in the "Issues"  table, then you close that issue in here. But now, i can't find your issue ,neither open nor closed. And your tag 10542 I think is just this post in "Pull requests" table. So ,maybe you can try to post a new issue in the "Issues"  table, and try to close that new issue again.

**Comment by hollenberry** [comment]
Absolutely right @AbrahamFriedman ! Thank you!

@Maggie323  I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/10542/commits/f5646685c187de0a36e78a6f19576754c20334a9. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by October 20th, I will go ahead and do it just to keep the repository clean!

**Comment by Maggie323** [comment]
Thank you so much! I’ll take a look again this weekend.

Maggie

**Pull request merged**
