### PR TITLE
Adding San Jose to the map

### LINKED ISSUE #32: Adding San Jose to the map
## Adding San Jose to the map

Hi everyone! This issue is to track the addition of San Jose to the map, which can be found at:

- Longitude: -121.886329
- Latitude: 37.338208

### PR DESCRIPTION
**Pull request by brentjo**
Hopefully this PR adds San Jose to the map!

This resolves #32 @githubteacher

### CODE REVIEW

**Comment by brianamarie** [comment]
@brentjo Looks great 😄 👍 Go ahead and merge! :shipit:

**Comment by brianamarie** [comment]
@brentjo  👋 Hello! I'd love to help you get this merge conflict figured out. Please let me know if you want some help! 

There are changes coming to this project and repository. To help get it ready, we are hoping to clean up some outstanding issues and pull requests. Unless I hear from you here, I am planning on closing this pull request without merging on **Friday, July 1st**. Thank you and happy coding! 😄

**Comment by brentjo** [comment]
@brianamarie It should be good to merge now!

**Comment by brianamarie** [comment]
Woohoo @brentjo! :shipit:

**Comment by crichID** [comment]
@brentjo you branch had a bit of a conflict because it includes changes to the class-pins.topojson file which is also being modified by the Travis CI build. I am going to go ahead and merge this so your pin can finally appear on the map! Welcome to Github!

**Pull request merged**
