### PR TITLE
computing programming - wmg

### PR DESCRIPTION
**Pull request by RainingShi**
good afternoon

### CODE REVIEW

**Comment by ElvaT** [comment]
👍

**Comment by megjlow** [comment]
Congratulations :-)

**Comment by hollenberry** [comment]
@RainingShi @impappl is correct! Also, just a few typos in latitude and longitude. 

If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions!

**Comment by crichID** [comment]
@RainingShi I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/6701/commits/b26dc1fa7f4cdda536f8d2a38c3fa6e873075c71. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by May 26th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
