### PR TITLE
adding jazz's coordinates

### LINKED ISSUE #12123: it's me
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by jazzlee**
@githubteacher what do you think?

this pull request closes #12123

### CODE REVIEW

**Comment by brianamarie** [comment]
@jazzlee  your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open by the end of next week.

After you merge, you can go ahead and close your other open pull request if you'd like. 😄

**Comment by hfuquene** [comment]
Good job !

**Comment by hfuquene** [comment]
:1st_place_medal:  good !! :+1:

**Comment by KonopekElo** [comment]
its great!
🥇

**Pull request merged**
