### PR TITLE
Commit Change

### PR DESCRIPTION
**Pull request by droderiques**
It's very easy to make some words **bold** and other words *italic* with Markdown. You can even [link to Google!](http://google.com)

### CODE REVIEW

**Comment by crichID** [comment]
@droderiques I noticed you closed your pull request without merging it. This usually happens when people don't know how to fix the failing tests, so I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/3376/commits/5b38aa9f69319532315e5c791e2937c661cf8559. Please take a quick look at the changes. Once the tests have finished running, please feel free to click the big green **Merge pull request** button.

**Comment by rvcat** [comment]
@droderiques looks great

**Comment by frberube** [comment]
@droderiques looks nice! 👍

**Comment by crichID** [comment]
@droderiques your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on February 10th.

**Comment by BLSB3** [comment]
you done did a thing congrats :p

**Pull request merged**
