### PR TITLE
Adding coords

### LINKED ISSUE #5234: git hello
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by maxnvdm**
closes #5234

### CODE REVIEW

**Comment by danielamartinezp** [comment]
:+1:

**Comment by danielamartinezp** [comment]
+---
githubHandle: maxnvdm
latitude: -33.9258
longitude: 18.4232
+---

Should be in this format

**Comment by hollenberry** [comment]
Hey @maxnvdm  !

- @danielamartinezp, above, is absolutely correct, you'll want to add those three dashes around your lines of code as well. 
- Additionally, you'll want to remove the `.` from the end of your filename to appear as `.json` instead of it's current state `.json.`

After that, you should be all set! 😄 👍

Please let us know if you need any help! We'll be closing this out to keep the repository clean if there's no action or conversation within the week.

**Comment by hollenberry** [comment]
@maxnvdm  I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/5235/commits/016a49a68fba28a1719c3a4566ceccea5d9c130f. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green Merge pull request button. If you haven't merged it by April 21st, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
