### PR TITLE
Add githubstudent's handle to map

### PR DESCRIPTION
**Pull request by linling1381**
Add SF - inner sunset

### CODE REVIEW

**Comment by wilso040** [comment]
Looks good.

**Comment by hollenberry** [comment]
Hey @linling1381 ! Almost there! 😄

It looks like all you need to do is rename your file to _pins/linling1381.json .
Also, you'll need to rename `githubhandle` to `githubHandle`.

Please let us know if you need any help! We'll be closing this out to keep the repository clean if there's no action or conversation within the week.

**Comment by hollenberry** [comment]
@linling1381  I went ahead and fixed the syntax issues. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green Merge pull request button. If you haven't merged it by April 21st, I will go ahead and do it just to keep the repository clean!

**Comment by crichID** [comment]
@linling1381 your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on April 21st.

**Pull request merged**
