### PR TITLE
Add stephenpaff's pin to the map

### LINKED ISSUE #5275: Add me!
Hello! :wave: Please add me as a collaborator to this repo.

### LINKED ISSUE #5278: Please add me - Chicago
## Adding Chicago to the map

Hi everyone! This issue is to track the addition of Chicago to the map, which can be found at: 

- Longitude: -87.629798
- Latitude: 41.878114

### PR DESCRIPTION
**Pull request by stephenpaff**
@githubteacher What do you think? 

This pull request closes #5278 
This pull request closes #5275

### CODE REVIEW

**Comment by shajanjp** [comment]
Your pin should be in this format.
```
---
githubHandle: <YOUR_USER_NAME>
latitude: <LATITUDE>
longitude: <LONGITUDE>
---
```

You missed the `---` in the beginning and end.

**Comment by ZhangRuFu** [comment]
shajanjp is right :+1:

**Comment by hollenberry** [comment]
Hey @stephenpaff  !

I agree with the community above! Add those `---` lines and update the `githubHandle` syntax, and after that, you should be all set! 😄 👍

Please let us know if you need any help! We'll be closing this out to keep the repository clean if there's no action or conversation within the week.

**Comment by hollenberry** [comment]
@stephenpaff  I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/5289/commits/4030e58cc73fec1db2eeee00048e69dad8b7d783. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green Merge pull request button. If you haven't merged it by April 21st, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
