### PR TITLE
User relocation

### PR DESCRIPTION
**Pull request by david-sarra**
---
@githubteacher Could you fix this issue? Thank you
Closes: #940
---

### CODE REVIEW

**Comment by hollenberry** [comment]
Hey @david-sarra  !

@ridsjin is correct! All that's left is for you to make sure that your file is a part of the _pins directory, and that it has a .json file extension.

This video should help if there's any extra confusion: https://vimeo.com/201011288

After that, you should be all set! 😄 👍

Please let us know if you need any help! We'll be closing this out to keep the repository clean if there's no action or conversation within the week.

**Comment by david-sarra** [comment]
@ridsjin @hollenberry thank you very much. Changes are done!

**Comment by david-sarra** [comment]
@hollenberry I can see myself in the map now, thank you again!

**Comment by hollenberry** [comment]
No worries, @david-sarra ! Nice work!

**Pull request merged**
