### PR TITLE
Adding Hyderabad,India to Github Maps

### PR DESCRIPTION
**Pull request by sateesh2020**
Adding Hyderabad Location for the Issue #154

### CODE REVIEW

**Comment by hectorsector** [comment]
@sateesh2020 apologies for the delay! You should now be ready to merge when you're ready. Happy 🚢 -ing!

**Comment by sateesh2020** [comment]
Thanks 😊

**Comment by hectorsector** [comment]
@sateesh2020 anytime, you can click the `Update Branch` button to bring in changes from master, and that will allow you to merge!

**Comment by rskranthi** [comment]
I am adding pin to this city !!!

**Comment by kranthi7325** [comment]
Hi all

**Comment by kranthi7325** [comment]
Hi all

**Pull request merged**
