### PR TITLE
Create sachsgit.json

### LINKED ISSUE #6385: Please, add me as a collaborator
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by sachsgit**
@githubteacher closes #6385

### CODE REVIEW

**Comment by sachsgit** [comment]
@githubteacher closes #6385

**Comment by sachsgit** [comment]
@githubteacher closes #6385

**Comment by VOffoma** [comment]
@sachsgit Keep up the good work 👍

**Comment by beardofedu** [comment]
@sachsgit this is good to merge. 👍

**Pull request merged**
