### PR TITLE
Added latitude and longitude

### PR DESCRIPTION
**Pull request by dfuqua**
@githubteacher closes #5634

### CODE REVIEW

**Comment by gloaysa** [comment]
Hi @dfuqua I'm leaving you feedback 😄

**Comment by crichID** [comment]
@dfuqua you are very close! You just need to add three dashes `---` one the first and last lines of the file and it will be :+1:. If you need any assistance, here is a quick video to show you how: https://vimeo.com/201011288

**Comment by NickiCB** [comment]
@dfuqua :tada:

**Comment by NickiCB** [comment]
:unicorn:

**Pull request merged**
