### PR TITLE
Adding my city

### PR DESCRIPTION
**Pull request by Manchen08**

### CODE REVIEW

**Comment by Manchen08** [comment]
Adding my city @githubteacher closes #3174

**Comment by crichID** [comment]
@Manchen08 this looks great :sparkles:

**Comment by YouCanRememberMe** [comment]
@Manchen08 this looks great

**Comment by htackett** [comment]
@Manchen08 this looks great

**Comment by crichID** [comment]
@Manchen08 your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on February 3rd.

**Pull request merged**
