### PR TITLE
Adding coordinates to YoyoAnandra file

### PR DESCRIPTION
**Pull request by YoyoAnandra**
@YoyoAnandra Hi!
This pull request closes #2827

### CODE REVIEW

**Comment by brianamarie** [comment]
Hi @YoyoAnandra! A few things...
- The numbers for the latitude and longitude have to be just that - numbers. If it includes letters like N, E, S, or W, the test will fail. Make sure you have the correct format! 
- Make sure there are no spaces before the characters on lines 1-5.

**Comment by crichID** [comment]
@YoyoAnandra I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/2827/commits/e64c47d6bbcab61a541c9ee7d37132f321e676cb. Please take a quick look at the changes. Once the tests have finished running, please feel free to click the big green **Merge pull request** button. If you haven't merged it by January 27th, I will go ahead and do it just to keep the repository clean!

**Comment by lydita** [comment]
need to no if its working

**Comment by crichID** [comment]
@lydita please do not merge pull requests you did not create!

**Pull request merged**
