### PR TITLE
Created file novotnyeric716

### PR DESCRIPTION
**Pull request by EricNovotny**
@githubteacher Hi

closes #5204

### CODE REVIEW

**Comment by EricNovotny** [comment]
1. Made this thing
2. Figuring it out still
3. Bye

**Comment by shajanjp** [comment]
@EricNovotny 
Your pin should be in this format.
```
---
githubHandle: <YOUR_USER_NAME>
latitude: <LATITUDE>
longitude: <LONGITUDE>
---
```

**Comment by amitavak** [comment]
Change the pin format in the file to 
---
githubHandle: <YOUR_USER_NAME>
latitude: <LATITUDE>
longitude: <LONGITUDE>
---

**Comment by hollenberry** [comment]
Hey @EricNovotny   ! 

Looks like you got some great advice from @shajanjp above! If you take action on his requested changes, you should be all set! 😄 👍 

Please let us know if you need any help! We'll be closing this out to keep the repository clean if there's no action or conversation within the week.

**Comment by hollenberry** [comment]
@EricNovotny   I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/5204/commits/b57fcedb17376943391177b628bb0d8ff790f530. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green Merge pull request button. If you haven't merged it by April 21st, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
