### PR TITLE
Create temmyadex01.json

### PR DESCRIPTION
**Pull request by temmyadex01**
the creation of the pin with the hometown location of the pin on the map

### CODE REVIEW

**Comment by temmyadex01** [comment]
finally added my location and hometown.
what an experience. @githubteacher whats your take on this?

**Comment by MarieCrappe** [comment]
@temmyadex01 looks great !

**Comment by MarieCrappe** [comment]
@temmyadex01 if you want to pass the checks and appear on the map, you need to put the 3 "-" before and after your coordinates. It should look like this :  
`---`
`githubHandle: YOUR-USERNAME`
`latitude: YOUR_LATITUDE`
`longitude: YOUR_LONGITUDE`
`---`

:+1: 
**Good luck!** You're almost there

**Comment by temmyadex01** [comment]
Thanks and I quite appreciate this. Moving on to the next level

On 4 Jan 2017 16:29, MarieCrappe <notifications@github.com> wrote:

@temmyadex01<https://github.com/temmyadex01> if you want to pass the checks and appear on the map, you need to put the 3 "-" before and after your coordinates. It should look like this :
---
githubHandle: YOUR-USERNAME
latitude: YOUR_LATITUDE
longitude: YOUR_LONGITUDE
---

👍
Good luck! You're almost there

**Comment by temmyadex01** [comment]
yeah I fix this

**Pull request closed without merging**
