### PR TITLE
Create lashbrook71

### PR DESCRIPTION
**Pull request by lashbrook71**
hi: smiley face, please tell me where i am going wrong

### CODE REVIEW

**Comment by crichID** [comment]
@lashbrook71 it looks like you are very close. All you need to do is add the `.json` file extension. If you need help, this video has instructions on how to fix common problems: https://vimeo.com/201011288

**Comment by BryanGuillaume** [comment]
@lashbrook71 Everything seems working fine now. Well done 🎉

**Comment by brianamarie** [comment]
@lashbrook71 your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on April 28.

**Comment by lashbrook71** [comment]
thanks for all the help

**Pull request merged**
