### PR TITLE
Valone seattlewa

### PR DESCRIPTION
**Pull request by valone**
add pin to map

### CODE REVIEW

**Comment by a-a-ron** [comment]
Hey @valone, you only need one file so let's delete the `pins/valone-seattlewa` and `_pins/valone-seattlewa.json` files. Let's also rename the `_pins/valoneseattlewa.json` to be `_pins/valone.json` so it matches the filename format of `_pins/YOUR-USERNAME.json`that is shown here; https://services.github.com/on-demand/intro-to-github/work-on-github. 

 The contents of your file should also follow the below format;
```
---
githubHandle: YOUR-USERNAME
latitude: YOUR_LATITUDE
longitude: YOUR_LONGITUDE
---
```
Update your `githubHandle: valoneseattlewa` to be `githubHandle: valone` and after making these changes your builds should pass. If you have questions on how to edit the filename or run into any other issues, check out this video that might help; https://vimeo.com/201011288.

**Comment by crichID** [comment]
@valone it looks like you accidentally closed your pull request! I went ahead and reopened it so you could finish the activity. I also deleted the two extra files since that part can be tricky and your pull request should pass now! Please let me know if you have any other questions.

**Comment by dosjota** [comment]
great!! 👍

**Comment by Dav-i-d** [comment]
good job

**Comment by brianamarie** [comment]
@valone  your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on April 28.

**Comment by spandzgit** [comment]
@valone - this is great 👍

**Pull request merged**
