### PR TITLE
stefanieisidora's pin

### PR DESCRIPTION
**Pull request by stefanieisidora**
Here's my coordinates and username. @githubteacher closes #3

### CODE REVIEW

**Comment by hiq-alexanderbatsis** [comment]
# 🐫

**Comment by DBarbarian** [comment]
Looking good @stefanieisidora

**Comment by DBarbarian** [comment]
🥇

**Comment by bas** [comment]
@stefanieisidora these reactions are quite useful, for example to have votes from the community 👍  or 👎  for example. Although I favour the ❤️  reaction.

**Pull request merged**
