### PR TITLE
Adding more logic to the clean-up script

### PR DESCRIPTION
**Pull request by crichID**
The clean-up script can currently be run by anyone with push access to this repo. This PR adds some logic to ensure dependencies are installed with the correct scope before running the script.

### CODE REVIEW

**Comment by crichID** [comment]
@hectorsector @brianamarie @hollenberry @beardofedu looking for one :+1: to merge!

**Comment by hectorsector** [comment]
@crichID I get the following:

```
 script/clean-up                                                                                   ⮂
├─┬ geojson-merge@0.1.0
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
Switched to a new branch 'cleanup-and-merge'
:frown: there are no new topojson files!
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
Deleted branch cleanup-and-merge (was 394bb7e).
```

Although there is a `topojson` file: #134

**Comment by crichID** [comment]
Doh @hectorsector the file name has quotes in the if statement. Rookie mistake!

**Comment by crichID** [comment]
@hectorsector I removed the quotes that were causing the problem and went ahead and merged. I tested that it would block them from running the script if they didn't have the package installed at the global scope and that was the biggest reason I wanted to make sure we had this merged in!

**Pull request merged**
