### PR TITLE
Add gwpjamie's pin to the map

### PR DESCRIPTION
**Pull request by gwpjamie**
Adding Tulsa to the map!

### CODE REVIEW

**Comment by AShankle** [comment]
Also in Tulsa!

**Comment by tuffix** [comment]
Hej @gwpjamie, think you need to direct the commit to the **_pins** directory and it should merge just fine!

**Comment by gwpjamie** [comment]
@AShankle will you be at the connected Tulsa event today too?

**Comment by brianamarie** [comment]
@gwpjamie I think @tuffix is right about the name of the file. Once it's `_pins/gwpjamie.json` instead of just `gwpjamie.json`, the tests should pass. Let me know if you want any help!

**Pull request merged**
