### PR TITLE
Brian h combes denver sw

### PR DESCRIPTION
**Pull request by BrianHCombes**
**Changed my coordinate JSON file back to original file name so it wouldn't have a suffix.**

_**Would this md format be itallic bold??**_

### Why yes ###

### CODE REVIEW

**Comment by crichID** [comment]
:wave: @BrianHCombes I love that you are playing around and you should definitely feel free to continue to do it! All I ask is that you please do not merge this pull request and change our README :wink:

**Comment by LarryReader** [comment]
👍

**Comment by Daniel54** [comment]
Good Job.

**Comment by yfCanada** [comment]
@BrianHCombes Good job practicing! Keep going!

**Comment by brianamarie** [comment]
Hello! I'm going to close this PR since it's changing code in the `README.md`. 😄

**Pull request closed without merging**
