### PR TITLE
Andrea create my branche

### LINKED ISSUE #6599: Hi, Add me!
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by andreaItaly2017**
Adding me to the map

closes #6599

### CODE REVIEW

**Comment by andreaparlongo2017** [comment]
Hi

**Comment by andreaparlongo2017** [comment]
hi I want to comment

**Comment by hollenberry** [comment]
Hey @andreaItaly2017 ! It looks like you were having some trouble with your PR, but I tried to tidy it up a little bit for you if you want to give it another go!

I removed two extra files, and left the last file for you to make edits on. You're very close! You'll just need to add some dashes, like in this video: https://vimeo.com/201011288.

 If you have questions, please don't hesitate to reach out!

**Comment by hollenberry** [comment]
@andreaItaly2017 I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/6601/commits/aead1002de79ad95a147533d9fe76b7b7ee97837. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by May 26, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
