### PR TITLE
Create splash.json

### LINKED ISSUE #12987: Add me
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by Splashleigh**
@githubteacher 
Add splash tot he map
closes #12987

### CODE REVIEW

**Comment by jeffmitch** [comment]
noice

**Comment by s002803** [comment]
Way to go.

**Comment by LamLieu** [comment]
Wow!

**Comment by andrew-kim99** [comment]
@Splashleigh this looks great! 👍

**Pull request merged**
