### PR TITLE
adding my location pin

### LINKED ISSUE #10735: i dno whats happening
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by Jshepherd97**
@githubteacher 
ive added my location pin closes #10735

### CODE REVIEW

**Comment by Jshepherd97** [comment]
@githubteacher what am I doing wrong?

**Comment by alpereira7** [comment]
I can't see what's wrong...

**Comment by vimeDev** [comment]
That´s great

**Comment by hollenberry** [comment]
@Jshepherd97  I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/10736/commits/15ec215e275f545dc4e5286cf51bec4cfc62fbc9. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by October 27th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
