### PR TITLE
Honeybee777 branchville

### PR DESCRIPTION
**Pull request by honeybee777**
Update the file.

### CODE REVIEW

**Comment by lousapetr** [comment]
Hello honeybee777 :)

You are on very good way to successfully create your pin! I think the tests fail because of the + signs at the beginning of each line. If you delete them, it should be ok 🎉

**Comment by mgrivera** [comment]
@honeybee777: Yes, I think as @lousapetr says, the  directory should be _pins and not pins_. Thanks and bye ...

**Comment by brianamarie** [comment]
@user I went ahead and fixed the syntax issues in [d2a3b4f](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/5784/commits/d2a3b4f8ebf0f3345feba928a67be59ab960270b). Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by April 28th, I will go ahead and do it just to keep the repository clean!

**Comment by honeybee777** [comment]
Thanks everyone! Hooray!

**Pull request merged**
