### PR TITLE
Add citizenkanee's coordinants

### LINKED ISSUE #5075: Please add me-Shenzhen,China
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by citizenkanee**
@githubteacher What do you think of this?
This pull request closes #5077.

### CODE REVIEW

**Comment by califocation** [comment]
👍

**Comment by a-a-ron** [comment]
Hey @citizenkanee, make sure your file is in the `_pins` directory. It's currently in `pins`.

**Comment by hectorsector** [comment]
@citizenkanee let us know if you need any help following @a-a-ron's advice!

**Comment by hollenberry** [comment]
Hey @citizenkanee  ! Looks like you've gotten good advice from Aaron above! If you take action on those changes, you'll be set. 👍

Please let us know if you need any help! We'll be closing this out to keep the repository clean if there's no action or conversation within the week.

**Comment by citizenkanee** [comment]
I still don't know how to get this right. So I'm gonna to create a new branch and follow your advice.

**Comment by citizenkanee** [comment]
Bravo!! I finally made it. Thank you for your help guys. It's really nice of you all. Very appreciate about that.

**Pull request merged**
