### PR TITLE
Create CRivasGomez.json

### PR DESCRIPTION
**Pull request by CRivasGomez**
Hello @githubteacher, I'm here for learning 👍 
Add to the map my pin of San Sebastian, Spain.
closes #649

### CODE REVIEW

**Comment by CRivasGomez** [comment]
close #649

**Comment by khari512** [comment]
Every thing looks good

**Comment by glaubergft** [comment]
Congratulations @CRivasGomez!

**Comment by githubteacher** [comment]
@CRivasGomez I would :heart: to see your pin on our map! Simply click the update branch button above, that will pull in the changes that have happened on master since you created this Pull Request. Then you should be able to click the big green merge button! Please let me know if you have any questions!

**Pull request merged**
