### PR TITLE
Create TFroh.json

### PR DESCRIPTION
**Pull request by TFroh**
Adding lat/long to pin
@githubteacher class closes #3572

### CODE REVIEW

**Comment by ljmwaugh** [comment]
hello, I'm trying to learn too

**Comment by johncooperpdx** [comment]
@TFroh I think you're missing the three dashes at the beginning and end.

**Comment by brianamarie** [comment]
Hi @TFroh! 👋 @johncooperpdx is right - Line one should only be the characters `---`, and the last line should be, too. Let me know if you need any help!

**Comment by brianamarie** [comment]
Hi @TFroh! I went ahead and made some changes. Since it's been open for a while, I'm going to merge, too. Nice work!

**Pull request merged**
