### PR TITLE
add mingtam pin to the map

### PR DESCRIPTION
**Pull request by mingtam**
add mingtam to the map 👍

### CODE REVIEW

**Comment by georgepatterson** [comment]
@mingtam It appearw you have a formatting error or two. Please have another read of the tutorial and try again.

**Comment by mingtam** [comment]
Hi,

I found I am not able to create a new branch, so I tried to use other person branch to go to the next step. Same, not able to assign myself when writing the comment while submit the pull, does it not open to new user?

**Comment by brianamarie** [comment]
Hi @mingtam! If you aren't able to create a branch, you probably haven't commented on #927. Give that a shot and see if it works!

**Comment by crichID** [comment]
@mingtam it looks like you created a fork instead of being added as a collaborator and contributing directly to this repository. I am going to go ahead and close this pull request and recommend that you check out the instructions [here](https://services.github.com/on-demand/intro-to-github/02/) to get added as a collaborator!

**Pull request closed without merging**
