### PR TITLE
Create gesinecauer.json yay

### PR DESCRIPTION
**Pull request by gesinecauer**
Doing the tutorial
Thanks @githubteacher

### CODE REVIEW

**Comment by nishantpa** [comment]
@gesinecauer great your checks pass. good job 🎉

**Comment by thc4agithub** [comment]
Keep up the **good** work!

**Comment by BrendonGonzales** [comment]
@gesinecauer Nice!

**Comment by chentt05** [comment]
@gesinecauer Great!

**Comment by jaj371** [comment]
Good job ya did it!!!!

**Pull request merged**
