### PR TITLE
Create aileenzeng.json

### LINKED ISSUE #11892: Add @aileenzeng to this project please
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by aileenzeng**
Adding myself to **map** for the workshop at UofR.

Closes #11892 
cc: @githubteacher

### CODE REVIEW

**Comment by duncangrubbs** [comment]
Feedback and motivation!

**Comment by xlzth** [comment]
👍 😄

**Comment by shawnchan2014** [comment]
Hi Aileen

**Comment by anesi** [comment]
Hello Aileen

**Pull request merged**
