### PR TITLE
latitude_longitude_coordinates

### PR DESCRIPTION
**Pull request by byassine93**
Adding coordinates. 
Changes made thanks to @githubteacher

### CODE REVIEW

**Comment by hectorsector** [comment]
Great start, @byassine93! It just looks like you forgot to put the extension at the end of the file name! [This video](https://vimeo.com/201011288) may help you correct it.

**Comment by dustendub** [comment]
good work

**Comment by austinxu13** [comment]
Well done 👍

**Comment by etonw** [comment]
## Looks good :) 

When will the pull request be accepted _and by who?_ 

@githubteacher ?

**Pull request merged**
