### PR TITLE
Pull Request

### PR DESCRIPTION
**Pull request by shreya-standard**

### CODE REVIEW

**Comment by cobalteam** [comment]
Hi shreya...good work!.
You created 2 files..  
_pins/shreya-standard.json  
...and...
pins/shreya-standard.json

Modify the first one, the bot will be looking inside the "_pins" folder. Just write latitude and longitude....all lowercase. Think you'll be good to go.

Good luck!.

**Comment by cobalteam** [comment]
Ohh...to modify a file!

- Click the Files changed tab at the top of the Pull Request.
- On the far right side of the file header, click the pencil icon to open the web editor.
- Make the necessary changes.
- Scroll to the bottom of the page and add the commit to your branch.
- This will kick off a new round of checks!

Again...good luck!

**Comment by hollenberry** [comment]
@cobalteam you rock! That's absolutely correct. @shreya-standard I removed the additional file because that can be kind of tricky, so you only need to worry about the one, making the recommended changes by @cobalteam .

If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions! :tada:

**Comment by hollenberry** [comment]
@shreya-standard  I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/7721/commits/7cda2faa177745c7f44d3b5686f236f7ec6a5593. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by June 30th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
