### PR TITLE
Please add my pin

### PR DESCRIPTION
**Pull request by jomustech**
I hope this take is final.

### CODE REVIEW

**Comment by jomustech** [comment]
Hi @githubteacher , 

Stuck on this one, have done everything according the video & always have the same result: The Travis CI build failing. Also @XanoXeno727 has the same issue as we discussed. Could you help us, please?

Thanks

**Comment by rsmith28** [comment]
Hi jomustech :)
Looking at your file, it contains + at the start of each line. I think you need to remove them

**Comment by rsmith28** [comment]
Hi Jomustech,

You have longitude spelled wrong. Remove the erroneous 't' after 'g'

**Comment by jomustech** [comment]
Thank you @rsmith28 ,

I updated my file.

**Pull request merged**
