### PR TITLE
Birdie seattle

### PR DESCRIPTION
**Pull request by berdie**
I added a pin to Seattle @githubteacher 

closes #297

### CODE REVIEW

**Comment by gmorganVA** [comment]
Change looks good. :-) Wonder who does the merge to master?

**Comment by crichID** [comment]
@berdie you should be able to merge this branch with master once you have clicked the "Update branch" button shown above!

**Comment by hollenberry** [comment]
Hey @berdie! Just a heads up, I'm planning on closing this out by the end of the week if it's still open, to keep the repo tidy. 

Feel free to reopen if you don't get a chance to merge this in time and want to return in the future.

**Comment by basellers1** [comment]
Hello, I am ging to add my name to this Seattle pin

**Pull request closed without merging**
