### PR TITLE
Add pin to map

### PR DESCRIPTION
**Pull request by robwm**
Adding seattle to the map.

### CODE REVIEW

**Comment by a-a-ron** [comment]
Hey @robwm, your file path is `_Pins/robwm.json` when it should be `_pins/robwm.json`. The "P" needs to be lowercase. Fix that and your builds should pass.

**Comment by hectorsector** [comment]
@robwm you've got some good advice from @a-a-ron ☝️ let us know if there's anything we can do to help!

**Comment by robwm** [comment]
Would someone be able to point me to some instructions on how to correct my file path? I could probably just make another pull request but I should learn how to correct mistakes at some point...  :)

**Comment by robwm** [comment]
After I requested further assistance, I stumbled upon a place where I could edit the path. I'm not sure I clearly understood how I got there but I'm sure I could find it again with a little effort. After that, everything fell into place. Should I delete the branch now? What's best practice?

**Pull request merged**
