### PR TITLE
SantPol jfernandezh.json

### PR DESCRIPTION
**Pull request by jfernandezh**
I added the city Sant Pol, this city is at Spain.

### CODE REVIEW

**Comment by jokerevil1611** [comment]
Good job! :)

**Comment by crichID** [comment]
@jfernandezh your code looks perfect but it looks like someone accidentally closed your pull request! I have re-opened it. Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on Friday (January 27).

**Comment by githubteacher** [comment]
:tada: @jfernandezh you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
:tada: @jfernandezh you are now a repository collaborator. :balloon:

**Pull request merged**
