### PR TITLE
Githubstudent spain3

### PR DESCRIPTION
**Pull request by mandy9408**
Adding SF to the map

### CODE REVIEW

**Comment by 0zxo** [comment]
@mandy9408  :wave:  hallo
i made some changes to your file and now is ready to merge
but you should post a comment (or edit your first comment) saying:
> `@githubteacher`  this pull request closes `#18650` <<this is your issue
<hr>

so the issue closes after merging.
:zap:  :cyclone: :es:

**Comment by DereTomBrand** [comment]
@mandy9408 This looks good.

@0zxo Thanks for your comment, I learned from it.

**Comment by podzhog** [comment]
Enhorabuena! ;-) Saludos desde Rusia!

**Comment by adyaaggarwal** [comment]
Great going @mandy9408

**Comment by davekilroy** [comment]
all looks fantastic and smashing!!! 👍

**Comment by tristanh314** [comment]
Looks good! Keep up the great work!

**Pull request merged**
