### PR TITLE
Adding amzel's coordinates

### LINKED ISSUE #18205: Please add me
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by amzel**
Adding my coordinates.

 @githubteacher.

closes #18205

### CODE REVIEW

**Comment by tmakarow** [comment]
this  looks good!

**Comment by mduhez** [comment]
This looks good! +1

**Comment by grust101** [comment]
This looks great +2

**Comment by Paolo-Man001** [comment]
Goody good!!!

**Comment by VindalooGamedev** [comment]
This looks great +3 :D :tada:

**Comment by thisisdope** [comment]
Well done!

**Pull request merged**
