### PR TITLE
Adding aby54's coordinates

### LINKED ISSUE #6732: Please add me - Chennai
## Adding Chennai to the map 

Hi everyone this issue is to track the addition of chennai to the map, which can be found at

-Latitude: 13° 04' N 
-Longitude: 80° 17' E

### PR DESCRIPTION
**Pull request by aby54**
@githubteacher
this pull request closes #6732

### CODE REVIEW

**Comment by akoboyd** [comment]
@aby54 Keep up the good work! 👍

**Comment by cressterrell** [comment]
@aby54 this looks great 👍

**Comment by hollenberry** [comment]
@aby54 You're so close! 

The only thing we need to update is to make the first letter of each line lower case! `githubHandle`, `latitude`, + `longitude`. 

If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions!

**Comment by brianamarie** [comment]
@aby54 I made some changes so the test will pass, and once everything's fixed, I'm going to merge it in to keep the repository tidy. Nice work! ✨

**Pull request merged**
