### PR TITLE
add my location on map

### LINKED ISSUE #9972: What's an issue?
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by majorg38**
@githubteacher what do you think?

this pull request closes #9972

### CODE REVIEW

**Comment by majorg38** [comment]
@githubteacher what do you think?

this pull request closes #9972

**Comment by jsonBeginner** [comment]
I think the format of the file should begin and end with ---.

**Comment by hollenberry** [comment]
Almost there @majorg38  ! Looks like you just need to make sure you have only three dashes (`---`) above and below your code, instead of the large amount of dashes. If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions! :tada:

**Comment by hollenberry** [comment]
@majorg38  I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/9975/commits/7a1261158500dbbd79842defe1615acbee20d444. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by September 22nd, I will go ahead and do it just to keep the repository clean!

**Comment by majorg38** [comment]
Dear Eric,  I have need of help with clarity of Level 2.4.  Can you possibly help me with that?  I didn't add the word "rebase" to deadly skills before pushing it up.  I tried pulling that branch back down but it's not working.  I can't go forward until this is cleared up.  The Git Hub course won't let me.  I click on "submit answer" but nothing happens.  Please.  I've been at this for hours and hours.  MJG




-----Original Message-----

**Comment by crichID** [comment]
> The Git Hub course won't let me. 

@majorg38 can you please provide a link to the course you are referencing?

**Comment by majorg38** [comment]
http://campus.codeschool.com/courses/mastering-github/level/2/section/2/collaborating-on-pull-requests




-----Original Message-----

**Comment by majorg38** [comment]
@Cynthia RIch, even though I fixed the list and added 'rebase' and pushed it up.  Everytime i click Submit Answer, nothing happens.  I think I messed up by originally pushing up the commit with out adding the word 'rebase'.  It's really messed up.  Can you help?  Thank you, Mary Jane Graff @majorg38




-----Original Message-----

**Pull request merged**
