### PR TITLE
Create shawnchan2014.json

### LINKED ISSUE #11895: Add me @shawnchan2014
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by shawnchan2014**
**Adding myself to map for the workshop at UR**

- This
- is
- a
- list

####TODO

- [ ] Things to do

Closes #11895 

cc: @githubteacher

### CODE REVIEW

**Comment by kylemacey** [comment]
You put your file in the `_pin` directory instead of the `_pins` directory

**Comment by jimmyli17** [comment]
Good job, Shawn :clap::clap::clap:

**Comment by randywang123** [comment]
Good job Shawn

**Comment by aileenzeng** [comment]
h e l l o !

**Pull request merged**
