### PR TITLE
Create daughk.json

### PR DESCRIPTION
**Pull request by daughk**
Change that includes my coordinates. @githubteacher

### CODE REVIEW

**Comment by corniste01** [comment]
@daughk Excellent 🎉

**Comment by hollenberry** [comment]
Hey @daughk  !

This looks excellent! Go ahead and click that big green `Merge` button above!

Please let us know if you need any help! We'll be closing this out to keep the repository clean if there's no action or conversation within the week.

**Comment by airscofield** [comment]
@daughk great job!

**Comment by qingmaliuguang** [comment]
@daughk  This looks great!

**Comment by crichID** [comment]
@daughk your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on April 21st.

**Comment by Anster04** [comment]
@daughk estas de parabens!

**Pull request closed without merging**
