### PR TITLE
Add Vijayshanth's pin to the map

### PR DESCRIPTION
**Pull request by Vijayshanth**
Adding me to the map!

### CODE REVIEW

**Comment by hollenberry** [comment]
Almost there @Vijayshanth  ! Looks like you just need to remove the double spaces from each line of code (looks indented), and rename your file to _pins/vijayshanth.json. If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions! :tada:

**Comment by crichID** [comment]
@vijayshanth I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/10036/commits/97824d619511e4a68fb8670f28f163392a185aca. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by September 29th, I will go ahead and do it just to keep the repository clean!

**Comment by aumirza** [comment]
@Vijayshanth It looks Great.

**Comment by crichID** [comment]
@PeteSykora please do not merge pull requests you did not create! We like to leave these so the original author can come back and merge them in. We run a script at the end of the week to clean up any that remain. Thank you!

**Comment by PeteSykora** [comment]
@crichID My apologies!

**Pull request merged**
