### PR TITLE
Add student pins to map

### PR DESCRIPTION
**Pull request by Ramwankhede**
abcdefgh

### CODE REVIEW

**Comment by StephenPacker** [comment]
@Ramwankhede looks aight 🎉

**Comment by RoloCao** [comment]
You missed the _ in the pins part it has to be _pins instead of just pins @Ramwankhede

**Comment by AnnaDore** [comment]
@Ramwankhede It's a great idea!

**Comment by AnnaDore** [comment]
@Ramwankhede it's a good decision!

**Pull request merged**
