### PR TITLE
Create longliveping

### PR DESCRIPTION
**Pull request by Longliveping**
Statue of Liberty

### CODE REVIEW

**Comment by toby10ant** [comment]
@Longliveping I think you need to add the extension .json to the file name.

**Comment by crichID** [comment]
@Longliveping your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on August 11th.

**Comment by morsegates** [comment]
@Longliveping _Looking good!_ 🎉

**Comment by fox-hunt** [comment]
@Longliveping This looks great! 🎉

**Pull request merged**
