### PR TITLE
Add my (FajriFadli) location to the map

### LINKED ISSUE #96: Adding Jakarta to the Map
## Adding Jakarta to the map

Hi everyone! This issue is to track the addition of Jakarta to the map, which can be found at:

- Longitude: 106.845599
- Latitude: -6.208763

git

### PR DESCRIPTION
**Pull request by FajriFadli**
@githubteacher 
I've added my location to the map, closes #96

### CODE REVIEW

**Comment by FajriFadli** [comment]
Can I merge now?

**Comment by jr-cologne** [comment]
Update the branch and then feel free to merge! :+1:

**Comment by FajriFadli** [comment]
@jr-cologne I usually update the branch by clicking Update branch just like in the picture below as an example.
82df93f2-5030-11e5-84ec-ea15e16ed887

But now I don't have the option to do that.
2016-09-02 06_29_49-add my fajrifadli location to the map by fajrifadli pull request 331 gith

Is there another way to update my branch?
Thanks

**Comment by FajriFadli** [comment]
Nevermind, I don't know what happen but the Update branch button is back.

**Comment by jr-cologne** [comment]
Ok, great! :+1:

Maybe it was a bug...

**Pull request merged**
