### PR TITLE
Add Ahigggs pin to the map

### PR DESCRIPTION
**Pull request by Ahigggs**
Adding Athens to the Map
@githubteacher 
closes
14003

### CODE REVIEW

**Comment by aravindharinair** [comment]
Hi @Ahigggs ,
You should mention @githubteacher and add the "closes" keyword at the end of your comment followed by your issue ID (14003)

**Comment by 07sebascode** [comment]
animo

**Comment by beardofedu** [comment]
@Ahigggs you should just need to change: `githubhandle` to `githubHandle` and the test should pass allowing you to merge your pull request. 👍

**Comment by sglodek** [comment]
you can dooo it

**Pull request closed without merging**
