### PR TITLE
Create morrowcj.json

### PR DESCRIPTION
**Pull request by morrowcj**
morrowcj location

@githubteacher 

closes #thisone

### CODE REVIEW

**Comment by gcs1usa** [comment]
@morrowcj , I don't see why this didn't pass checks.  Was there something wrong with the format?

😢

**Comment by gcs1usa** [comment]
I see the problem, @morrowcj .  Follow the formatting instructions exactly and review the Travis CI check details for more information.

**Comment by Funce** [comment]
My gosh Travis is so Finnicky.

**Comment by brianamarie** [comment]
Hi @morrowcj, this looks great! Go ahead and merge. 😄

**Pull request merged**
