### PR TITLE
added pin

### PR DESCRIPTION
**Pull request by acnithin**
Hello,

Added my pin

### CODE REVIEW

**Comment by hectorsector** [comment]
@acnithin apologies for the delay! You should now be able to merge. Happy 🚢-ing!

**Comment by TedWolfe** [comment]
Why still open?!?

**Comment by TedWolfe** [comment]
Ahhhh... merge your commits, eh?

**Comment by hollenberry** [comment]
Hey @acnithin ! Friendly follow up-ping, this looks good to go! You can feel free to merge when you're ready 😄

**Comment by brianamarie** [comment]
@acnithin We are no longer using this file structure for our activities. If you'd like to continue, you can either close this pull request and start again, OR:

- On your same branch, undo any changes to the `class-pins.topojson` file
- Create a new file after your username, like `acnithin.json`
- Fill that file with the following text, replacing the important bits:
```
---
githubHandle: Lobo
latitude: -31.420198
longitude: -64.188773
---
```

Let me know if you need/want any help! 😄 🎉

**Comment by hollenberry** [comment]
Hey @acnithin! Just a heads up, I'm planning on closing this out by the end of the week if it's still open, to keep the repo tidy. 

Feel free to reopen if you don't get a chance to make updates in time and want to return in the future.

**Pull request closed without merging**
