### PR TITLE
Adding terickso25 coordinates

### LINKED ISSUE #4728: New to Github....online learning
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by terickso25**
Added my coordinates for inclusion in the pin map

@githubteacher has been great so far with learding Github

Closes #4728

### CODE REVIEW

**Comment by MaiaEspinosa** [comment]
@terickso25  This looks fantastic! Congratulations :tada:

**Comment by shajanjp** [comment]
@terickso25  Looks great ! Now press the big green **Merge pull request** button below and your coordinates will be added to the map.

**Comment by hectorsector** [comment]
@terdia feel free to merge when you're ready!

**Comment by MyAngelQian** [comment]
@terickso25 This looks great!:data

**Comment by MyAngelQian** [comment]
@terickso25 This looks great! :tada:

**Comment by hollenberry** [comment]
Well done @terickso25 ! Merging this in for you to keep the repository clean! 🎉 🎉 ✨

**Pull request merged**
