### PR TITLE
 _pins/smiah4333.json

### PR DESCRIPTION
**Pull request by smiah4433**
hello sir

### CODE REVIEW

**Comment by smiah4433** [comment]
@githubteacher closes #7823

**Comment by hollenberry** [comment]
Almost there @smiah4433  ! 

Looks like you just need to: 
- Rename your file to _pins/smiah4333.json (you can backspace through the extra `/` in the UI)
- Add dashes above and below your code, like so: `---`

If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions! :tada:

**Comment by Jopture** [comment]
You can do it! 🙌

**Comment by jenlscribner** [comment]
Don't give up.  You can do it.  :tada:

**Comment by brianamarie** [comment]
@smiah4433  I made some changes so the tests will pass. Once everything turns green, I'll go ahead and merge this in since it's been a few days and we want to keep the repository clean. 😄 ✨

**Pull request merged**
