### PR TITLE
add Vermont to map

### PR DESCRIPTION
**Pull request by VTG38**
1. +---
2. +githubHandle:  VTG38
3. +Latitude: 44.5588
4. +Longitude: 72.5778

#2665

### CODE REVIEW

**Comment by lydebacle** [comment]
this looks great! 🎉

**Comment by VTG38** [comment]
[]https://github.com/githubschool/open-enrollment-classes-introduction-to-github.git(url)

**Comment by VTG38** [comment]
[open-enrollment-classes-introduction-to-github-master.zip](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/files/691854/open-enrollment-classes-introduction-to-github-master.zip)

**Comment by VTG38** [comment]
Should I have deleted the branch?

**Comment by VTG38** [comment]
From b2d1fc09ff14e764bb05c151d927bd52c7cd47a3 Mon Sep 17 00:00:00 2001
From: VTG38 <VTG38@users.noreply.github.com>
Date: Sat, 7 Jan 2017 21:11:44 -0500
Subject: [PATCH] Delete _config.yml

---
 _config.yml | 3 ---
 1 file changed, 3 deletions(-)
 delete mode 100644 _config.yml

diff --git a/_config.yml b/_config.yml
deleted file mode 100644
index ceaed8c..0000000
--- a/_config.yml
+++ /dev/null
@@ -1,3 +0,0 @@
-collections:
-  - pins
-exclude: [vendor]

**Pull request merged**
