### PR TITLE
Create ngurney.json.

### LINKED ISSUE #4642: Please Add Me - Provo, UT
Hello! :wave: Please add me as a collaborator to this repo. 

Log: 111.658534
Lat: 40.233844

### PR DESCRIPTION
**Pull request by ngurney**
@githubteacher 

Adding my pin to the map!

This pull request closes #4642

### CODE REVIEW

**Comment by ngurney** [comment]
@githubteacher Any thoughts as to why this keeps failing? Thanks!

**Comment by a-a-ron** [comment]
Hey @ngurney! Everything looks good except for the extra `.` at the end of json in your file name. Remove that and your builds should work.

**Comment by ngurney** [comment]
@a-a-ron Oh perfect! Didn't notice that! Thanks for all your help!

**Comment by a-a-ron** [comment]
@ngurney No problem. Always glad to help a fellow Utahan :)

**Pull request merged**
