### PR TITLE
Create psmith01.json

### PR DESCRIPTION
**Pull request by psmith01**
My Durham location
@githubteacher 
closes #19106

### CODE REVIEW

**Comment by psmith01** [comment]
Hi

**Comment by Alli666Mirdad** [comment]
Can someone to up my maxis no. First,  I then we can build anything

**Comment by Alli666Mirdad** [comment]
0178156123
Who's help me, they is the 1st one I will serve

**Comment by Alli666Mirdad** [comment]
Can you top up my maxis no first?  Only rm5,  who's help me,  they is the
1st one I will served

**Pull request closed without merging**
