### PR TITLE
Lrrhoade g ville

### PR DESCRIPTION
**Pull request by lrrhoade**
add pin to map

### CODE REVIEW

**Comment by crichID** [comment]
@lrrhoade your file `_pins/lrrhoade1.json` is correct, but unfortunately your tests will continue to fail because the other file you created on this pull request has `...` instead of `---`. I will go ahead and remove this file and then everything should pass!

**Comment by lrrhoade** [comment]
Thank you. Is there a way i couldve deleted myself?

**Comment by hollenberry** [comment]
Hey @lrrhoade ! 

It looks like there's one more fix leftover for you to tackle! 

Instead of `githubhandle`, it should show `githubHandle`. Please let me know if you need any help fixing this! Afterwards, you should be good to merge!

**Comment by hollenberry** [comment]
You'll also want to include spaces after each of the `:`'s.

**Comment by hollenberry** [comment]
@lrrhoade  I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/6556/commits/175170bc1fcc462a704056d279432bfe3ddc9e22. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by May 26, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
