### PR TITLE
Delete saTraiiningFile

### PR DESCRIPTION
**Pull request by mccurcio**
Just cuz

### CODE REVIEW

**Comment by perlba** [comment]
:+1:

**Comment by hollenberry** [comment]
Agreed, @mccurcio. Go ahead and merge!

**Comment by mccurcio** [comment]
cleaning

**Comment by hollenberry** [comment]
Almost there!

**Comment by mccurcio** [comment]
all done?

**Comment by hollenberry** [comment]
👍

**Pull request merged**
