### PR TITLE
adding coordinats

### LINKED ISSUE #9531: Please add me
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by dagolinuxoid**
@githubteacher — take a look

closes #9531

### CODE REVIEW

**Comment by dagolinuxoid** [comment]
All checks have failed — what the heck is this? :)

**Comment by hollenberry** [comment]
Hey @dagolinuxoid ! You're so close! Looks like there's a trailing space on line 2.

**Comment by dagolinuxoid** [comment]
@hollenberry thx ^^. BTW actually I've deleted this branch and create a new one.

**Comment by hollenberry** [comment]
Oh, okay! No problem! In the future, you can always add commits to branches that need fixing! Should save you some time and effort 👍  😄

**Pull request closed without merging**
