### PR TITLE
Adding lat and long

### PR DESCRIPTION
**Pull request by harshil1712**
@githubteacher 
#6575

### CODE REVIEW

**Comment by harshil1712** [comment]
@githubteacher why did it failed? How can I resolve it?

**Comment by ktlnbstn** [comment]
Looks like you missed the step that asked you to submit your latitude and longitude. 
Those numbers will enable the program to 'pin' your location and therefore complete this mini lesson.

**Comment by crichID** [comment]
@harshil1712 it looks like the checks are failing because one or more of your lines has an extra space at the end. 

screen shot 2017-05-18 at 9 34 27 am

If you remove the trailing space the checks will pass! If you need help, check out this video: https://vimeo.com/201011288

**Comment by hollenberry** [comment]
@harshil1712  I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/6576/commits/35f167afe4fa26a0ac1eb7f33b3f3a96c65db5b3. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by May 26, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
