### PR TITLE
Adding Budapest, HU

### LINKED ISSUE #5319: Please add me - Budapest, HU
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by Markcanfly**
Added my **name** and my *coordinates*.
@githubteacher tell me *your* opinion.
The pull request closes #5319

### CODE REVIEW

**Comment by 1metronome** [comment]
Use lowercase for your githubHandle.

**Comment by hollenberry** [comment]
Hey @Markcanfly  !

You're _so_ close! You'll want to add your file to the _pins directory as well. 

This video should help: https://vimeo.com/201011288

After that, you should be all set! 😄 👍

Please let us know if you need any help! We'll be closing this out to keep the repository clean if there's no action or conversation within the week.

**Comment by Markcanfly** [comment]
Ahh, I feel so dumb. 
Thank you for being so helpful, I've gone ahead and added the file to _pins.

**Comment by hollenberry** [comment]
@Markcanfly You're still so close!

It looks like you accidentally created a second file, or you had two files to start and only renamed one (and we'll only want to merge __one__ in). If you take the same steps on the file left (I removed the other), it'll pass. 😄 

I know you know how to do this, but I'm attaching screenshots in case they're helpful. 

screen shot 2017-04-12 at 9 45 00 am

screen shot 2017-04-12 at 9 44 47 am

**Comment by hollenberry** [comment]
@Markcanfly I went ahead and fixed the syntax issues that we discussed. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green Merge pull request button. If you haven't merged it by April 21st, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
