### PR TITLE
Add jtralongo's pin to the map

### PR DESCRIPTION
**Pull request by jtralongo**
Adding Brewer to the map!

### CODE REVIEW

**Comment by antoniomavaro** [comment]
Hello from Italy!
Image of Yaktocat

**Comment by jtralongo** [comment]
Hello Antonio!

**Comment by gamino1996** [comment]
Looks good!!!

**Comment by CwuAl** [comment]
Looks good @jtralongo 
You should probably merge the pull request.  😄

**Comment by festinalente-software** [comment]
@jtralongo 💯 looks great now!

**Comment by exwima** [comment]
@jtralongo Hi Jack, that looks fine. :star:

**Pull request merged**
