### PR TITLE
adding my coordinates

### LINKED ISSUE #3768: Please add me - Atlanta, GA
Hello! :wave: Please add me as a collaborator to this repo. 

## Atlanta here
Hello this issue is to track the addition to Atlanta to the map. Which can be found at 
Longitude: 33.7490° N
Latitude: 84.3880° W

### PR DESCRIPTION
**Pull request by kevinnumber1**
hi
@githubteacher 
closes #3768

### CODE REVIEW

**Comment by oranjee** [comment]
@kevinnumber1 👍 u doin good kid

**Comment by kevinnumber1** [comment]
but my checks failed 😢

**Comment by brianamarie** [comment]
@kevinnumber1 It looks like there are some spaces at the end of line 2, after your username. Try deleting those. 😄

**Comment by xyhesummer** [comment]
@kevinnumber1 try one more time?

**Comment by Anjanette-09** [comment]
this looks great!

**Pull request closed without merging**
