### PR TITLE
Add toto's coordinates

### LINKED ISSUE #4435: Please add me
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by renjian2017**
@githubteacher Add toto's corordinates from google map
closes #4435

### CODE REVIEW

**Comment by kdeguzman101** [comment]
@renjian2017 Looks good! :tada:

**Comment by hollenberry** [comment]
@renjian2017 You're good to ship (thanks @kdeguzman101 !!)! If you would like your pin to appear on the map, you will need to click the big green button below to Merge pull request. Please let us know if you need any assistance.

**Comment by benfraid** [comment]
@renjian2017 This looks great! 🌮

**Comment by jinifrancis** [comment]
Successfully completed...Congrats

**Comment by crichID** [comment]
@renjian2017 your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on March 17, 2017.

**Pull request merged**
