### PR TITLE
Create tylernd27

### PR DESCRIPTION
**Pull request by tylernd27**

### CODE REVIEW

**Comment by a-a-ron** [comment]
Hey @tylernd27, make sure to include the `.json` at the end of your file. Everything else looks good!

**Comment by jgreenbergpw** [comment]
Cool! 😎 👍🏼

**Comment by hectorsector** [comment]
@tylernd27 great start! You'll need to add `.json` at the end of your file as suggested by @a-a-ron. Let us know if you need any help with it!

**Comment by tylernd27** [comment]
doh! thanks @hectorsector and @a-a-ron

**Comment by hectorsector** [comment]
👏 great work! Feel free to merge your PR :shipit:

**Comment by robt79** [comment]
@tylernd27 This looks great!

**Comment by hollenberry** [comment]
Well done @tylernd27 ! Merging for you to keep the repository clean. 🎉

**Pull request merged**
