### PR TITLE
More touchdowns!

### PR DESCRIPTION
**Pull request by Johnspenader**
Go Bucs!

### CODE REVIEW

**Comment by Johnspenader** [comment]
closes #3 @githubteacher

**Comment by Johnspenader** [comment]
Closes #5 @githubteacher

**Comment by jiannaml** [comment]
Good job on the hard work! I'm practicing too

**Comment by crichID** [comment]
@Johnspenader thank you for checking out our [on-demand classes](https://services.github.com/on-demand/). Since this file is not valid per the examples in the course, I am going to go ahead and close this Pull Request. If you would like to complete the activity, please feel free to re-open this Pull Request or start again. If you have any questions, please let us know!

**Pull request closed without merging**
