### PR TITLE
Adding remcopasma's coordinates

### LINKED ISSUE #14395: Please add me: Remco Pasma
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by remcopasma**
## Leren hoe github werkt 
@githubteacher  is great.
closes #14400

### CODE REVIEW

**Comment by remcopasma** [comment]
verandering

**Comment by madebymartin** [comment]
Go go go!

**Comment by Timilof** [comment]
gaas 💯

**Comment by nixus619** [comment]
This looks like something for sure

**Comment by wooorm** [comment]
@remcopasma You added a file as in the root directory, `remcopasmaa.js`, that shouldn’t be here.
It also looks like you removed a JSON file? `_pins/remcopasma.json`. That should be there, but have a YAML extension!

**Pull request merged**
