### PR TITLE
Create randub.json

### PR DESCRIPTION
**Pull request by randub**
Adding longitude and latitude
I did **nothing**

### CODE REVIEW

**Comment by levelfly17** [comment]
@randub  Great!! 🎉

**Comment by DanielvandeVelde** [comment]
@Randub Well done! :loudspeaker:  :tada:

**Comment by sdbeng** [comment]
@randub Great job! 🎉

**Comment by TheLost2Lt** [comment]
Great Job🎉

**Comment by rbntimes** [comment]
@randub Great work 👍

**Pull request merged**
