### PR TITLE
Adding enuj's coordinants

### LINKED ISSUE #5788: Add me
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by enuj**
Hello @githubteacher 
I just added my coordinates into the project.
This pull request closes #5788

### CODE REVIEW

**Comment by kvn-dly** [comment]
Looks great! :earth_asia: :+1:

**Comment by OmarAbdelhafiz** [comment]
Well Done!! 🥇

**Comment by brianamarie** [comment]
@enuj I went ahead and fixed the syntax issues in [1d2c013](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/5794/commits/1d2c0133b7b11e0bd4d24bf3d583204cf9c68c93). Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by April 28, I will go ahead and do it just to keep the repository clean!

**Comment by lashbrook71** [comment]
looks **great** @enuj 👍

**Comment by taptso** [comment]
@enuj This looks great. 🎉

**Comment by taptso** [comment]
@enuj this looks great 🎉

**Comment by enuj** [comment]
Leave a comment

**Pull request merged**
