### PR TITLE
Add Brooklyn to the Map

### LINKED ISSUE #141: Brooklyn addition
## Adding Brooklyn to the map

Hi everyone! This issue is to track the addition of Brooklyn to the map, which can be found at:
- Longitude: -73.944158
- Latitude: 40.678178

### PR DESCRIPTION
**Pull request by sallyjiang**
Add pin to map
@githubteacher 
closes #141

### CODE REVIEW

**Comment by designer226** [comment]
Looks great @sallyjiang!
:fireworks:

**Comment by Trehalose** [comment]
Looks good to me, @sallyjiang !
Brooklyn needs more love, yo

**Comment by grapes323** [comment]
Good job!

**Comment by hollenberry** [comment]
Hey @sallyjiang ! I plugged Brooklyn into http://mynasadata.larc.nasa.gov/latitudelongitude-finder/ and it looks like you might want to flip your longitude to ( - ) . After that, you should be all set to 🚢 !

**Pull request closed without merging**
