### PR TITLE
Add githubstudent's pin to the map

### PR DESCRIPTION
**Pull request by guopei0001**
Adding SF to the map!

closes #940

### CODE REVIEW

**Comment by bobbymay** [comment]
looks good!

**Comment by hollenberry** [comment]
Hey @bobbymay ! I think you accidentally closed this one.

**Comment by hollenberry** [comment]
@guopei0001 You're very close to finishing this merge! I removed the extra file from your PR, but a few fixes still need to be made to the one remaining. Specifically, you can change `githubstudent` to your handle, and add three dashes to the bottom of the file.

If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions!

**Comment by crichID** [comment]
@guopei0001 I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/6726/commits/c93df26545776d4812fffe41670a844ac24b0b63. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by May 26th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
