### PR TITLE
Create Dingindlela.json

### PR DESCRIPTION
**Pull request by Dingindlela**
Adding Harare to the map

### CODE REVIEW

**Comment by Dingindlela** [comment]
Harare added successfully

**Comment by crichID** [comment]
@Dingindlela all you need to do is add a series of three dashes `---` as the first and last line of your file and this will be ready to merge! Your finished file should look like this:

screen shot 2016-10-16 at 10 12 41 am

**Comment by AumDove** [comment]
Keep up the good work!! :raised_hands: :clap:

**Comment by msonon** [comment]
If you add the "+---" before and after the text already in the file, it should work.  i.e.

+---
+githubHandle: Dingindlela
+latitude: -17.825166
+longitude: 31.033510
+---

**Pull request merged**
