### PR TITLE
Leireneira patch 1

### PR DESCRIPTION
**Pull request by leireneira**
@mberasategi  What do you think?

This pull request closes #17347

### CODE REVIEW

**Comment by Kcmamu** [comment]
:tongue:

**Comment by han1txh** [comment]
Hi !

**Comment by mberasategi** [comment]
Hi @leireneira , check the latest commits I made to your branch. You had two problems:

- missing spaces after colons in the file (after `githubHandle:` and `longitude:`, you nedded a space), solved in 6ed0936 , and
- an unnecessary empty file that the system tried to make sense of. Just deleted it in 8a29fb4

All checks are now passing. so go ahead and [merge your pull request](https://services.github.com/on-demand/intro-to-github/merge-pull-request) to finish the tutorial.

**Comment by paulasoroetaarizcuren** [comment]
This is great! 🎉

**Pull request merged**
