### PR TITLE
Okutaonairobi

### PR DESCRIPTION
**Pull request by ogacho**
new pull request

### CODE REVIEW

**Comment by ogacho** [comment]
syntax

**Comment by brianamarie** [comment]
This looks great, @ogacho! Go ahead and merge whenever you're ready! 🚢

**Comment by ogacho** [comment]
@brianamarie can't find the merge button, please advise.

**Comment by brianamarie** [comment]
@ogacho Scroll down, do you see a big green button that looks like this?  

screen shot 2016-11-01 at 10 04 31 am

**Comment by ogacho** [comment]
@brianamarie still can't find it! Don't know what i'm doing wrong 👎

**Comment by ogacho** [comment]
@brianamarie I found my error, I forked instead of creating a new branch.... 👍

**Comment by ogacho** [comment]
@brianamarie its interesting learning github

**Pull request closed without merging**
