### PR TITLE
Adding hodgepodge73's coordinates

### LINKED ISSUE #14302: Please add me
Hello! :wave: Please add me as a collaborator to this repo. I live in Ontario.

### PR DESCRIPTION
**Pull request by hodgepodge73**
@githubteacher 
adds hodgepodge73's coordinates and city
closes #14302

### CODE REVIEW

**Comment by heidismith** [comment]
@hodgepodge73  Great job!  CI build passed on your first try!

**Comment by sushanth02** [comment]
Hey @hodgepodge73 . Good work!!

**Comment by Maikxx** [comment]
Good job! Looks good. Great location.

**Comment by LindadeHaan** [comment]
Good job!!

**Pull request merged**
