### PR TITLE
Add LindaLalonde Pin to Map

### LINKED ISSUE #11454: Please add me - Ottawa, ON
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by lindalalonde**
@githubteacher closes #11454  (This should work. :) )

### CODE REVIEW

**Comment by sczxoz** [comment]
@githubteacher  closes #11456

**Comment by lindalalonde** [comment]
I have committed a new file with the correct folder path of _pins

**Comment by subhrajitb** [comment]
Same checks failed for me. Maybe I need to add "#" before the issue number in the comments section ? OK. Best of luck.

**Comment by subhrajitb** [comment]
My issue was not what I initially thought it was. It was in the code.

**Comment by MarianoTerzolo** [comment]
@lindalalonde if you commited a new file to the _pin folder don't forget to delete the old one from the root folder. That was what happened to me.

**Comment by hectorsector** [comment]
Apologies for the trouble @lindalalonde! You were on the right track to fix the issues you were having, but ended up creating multiple files which is caught as an error, as well.

Everything looks ✨ now feel free to merge!

**Comment by joraq** [comment]
@lindalalonde This looks great!

**Pull request merged**
