### PR TITLE
Add basilio's pin to the map

### PR DESCRIPTION
**Pull request by basiliomp**

### CODE REVIEW

**Comment by brianamarie** [comment]
Hi @basiliomp! This looks great, go ahead and merge whenever you're ready!

**Comment by Battle941** [comment]
Looks good to me! 🎉

**Comment by CptKirk18** [comment]
@basiliomp Looks good to me!

**Comment by edusegzy** [comment]
@basiliomp  This looks great 👍 tada

**Comment by midnight250** [comment]
@basiliomp  this looks great

**Comment by Utkarsh9615** [comment]
Great to come

**Pull request merged**
