### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by chandrika009**

### CODE REVIEW

**Comment by brianamarie** [comment]
Hi @chandrika009 👋 ! 

I think the test is failing because of the format of the latitude and longitude. Try formatting it like this:

```
{ "type": "Feature", "geometry": {"type": "Point", "coordinates": [-6.360144, 36.623687]}, "properties": {"username": "jess-alexander"} }
```
_[found here](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/196)_

Remember to do longitude FIRST, and latitude second. 😄 Let me know if you need any help!

**Comment by hollenberry** [comment]
Hey @chandrika009 ! Friendly reminder ping. Once you update this PR with the changes recommended by @brianamarie, you should be all set to 🚢 !

**Comment by croworc** [comment]
Hi @chandrika009,

adding to @brianamarie and @hollenberry:

When you created that file, did you _**save**_ it in` Unicode` format (like, `UTF-8`), not in `ASCII`/`ANSI` format? 
When I looked at your file in `RAW` format, some chars couldn't be displayed correctly in the browser window...
Cheers!

**Comment by hollenberry** [comment]
Hey @chandrika009 ! Just a heads up, I'm planning on closing this out by the end of the week if it's still open, to keep the repo tidy. 

Feel free to reopen if you don't get a chance to make adjustments in time and want to return in the future.

**Pull request closed without merging**
