### PR TITLE
Create sharat.json

### PR DESCRIPTION
**Pull request by sharatsarvankar**

### CODE REVIEW

**Comment by sharatsarvankar** [comment]
testing

**Comment by shajanjp** [comment]
Your pin should be in this format.
```
---
githubHandle: <YOUR_USER_NAME>
latitude: <LATITUDE>
longitude: <LONGITUDE>
---
```

**Comment by shajanjp** [comment]
Your pin should be in this format.
```
---
githubHandle: <YOUR_USER_NAME>
latitude: <LATITUDE>
longitude: <LONGITUDE>
---
```

**Comment by hollenberry** [comment]
Almost there @sharatsarvankar! @shajanjp is correct! Once you make those changes, you should be set.

If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions! :tada:

**Comment by brianamarie** [comment]
@sharatsarvankar  thank you for checking out our [on-demand classes](https://services.github.com/on-demand/). Since this file is not valid per the examples in the course, I am going to go ahead and close this Pull Request. If you would like to complete the activity, please feel free to re-open this Pull Request or start again. If you have any questions, please let us know!

**Pull request closed without merging**
