### PR TITLE
Create jimmyg0ld.json

### PR DESCRIPTION
**Pull request by jimmyg0ld**
@githubteacher How's it looking?

THis pull request closes #1

### CODE REVIEW

**Comment by zachary-murphy** [comment]
Nice, Pull Request ;)

**Comment by WStrellis** [comment]
@jimmyg0ld Good work 👍

**Comment by mblouin02** [comment]
Good job @jimmyg0ld !

**Comment by danieltaylor7** [comment]
Awesome job @jimmyg0ld

**Pull request merged**
