### PR TITLE
adds username label in map

### PR DESCRIPTION
**Pull request by shajanjp**
Github handle will be shown as label for each pin

### CODE REVIEW

**Comment by shajanjp** [comment]
@githubrobot @crichID is this ok ?

**Comment by MixMasterT** [comment]
@shajanjp nice work! You are making great progress.

**Comment by hectorsector** [comment]
Thanks for the contribution, @shajanjp! I'll ping other members of @githubschool/training-team so we can get some 👀 and code review kicked off!

**Comment by jarryh** [comment]
@shajanjp  Hey cool 👍

**Comment by hectorsector** [comment]
@stoe @shajanjp I don't think this actually changes the display on the published site -- just on the internal rendering of this repo. Therefore, I think in order to display this we'll need an accompanying contribution to the [corresponding `js` file on `training-kit`](https://github.com/github/training-kit/blob/master/assets/js/mapsAPI.js).

**Comment by stoe** [comment]
> Therefore, I think in order to display this we'll need an accompanying contribution to the corresponding `js` file on `training-kit`.

@hectorsector @shajanjp , yes.
We need to add the `label` attribute also in https://github.com/github/training-kit/blob/master/assets/js/mapsAPI.js#L47-L61 for it to show up. Right now it only has a `title` attribute that will display the user's name on hover only.

**Comment by shajanjp** [comment]
@stoe @hectorsector It will be so awesome if we can replicate the same map design in this page https://services.github.com/on-demand/intro-to-github/ :relaxed:

**Pull request closed without merging**
