### PR TITLE
Create 00fo11.json

### PR DESCRIPTION
**Pull request by 00fo11**
closes 1593

### CODE REVIEW

**Comment by 00as12** [comment]
Well done :-1:

**Comment by 00as12** [comment]
:+1:

**Comment by crichID** [comment]
@00fo11 this looks good to merge! Please feel free to click the big green button above to **Merge pull request**.

If you haven't merged by 11/15/2016, a member of the GitHub training team will merge it for you 😉

**Comment by ttkudeans** [comment]
help

**Pull request merged**
