### PR TITLE
practice

### PR DESCRIPTION
**Pull request by nikhilbhanushali21**

### CODE REVIEW

**Comment by nikhilbhanushali21** [comment]
add

**Comment by nikhilbhanushali21** [comment]
@githubteacher

closes #9150

**Comment by nikhilbhanushali21** [comment]
@githubteacher 
closes #9150

**Comment by nikhilbhanushali21** [comment]
@githubteacher
closes #2970

**Comment by LivingProgram** [comment]
@nikhilbhanushali21 
hey, you need to remove the spaces before your lines and that will stop the error message

**Comment by LivingProgram** [comment]
So you would need to change the contents of your file to something like this:
```
---
githubHandle: nikhilbhanushali21
latitude: 36.8874
longitude: -119.7697
---
```

**Comment by lli5ba** [comment]
Good job!

**Comment by crichID** [comment]
@nikhilbhanushali21 I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/2970/commits/47c7d3d0f3929ede2bebd932aba239b2875d4f75. Please take a quick look at the changes. Once the tests have finished running, please feel free to click the big green **Merge pull request** button. If you haven't merged it by January 27th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
