### PR TITLE
Create coderjay8989.json

### PR DESCRIPTION
**Pull request by coderjay8989**
@githubteacher this closes well im not sure to be honest i guess the create coderjay8989.json?

### CODE REVIEW

**Comment by NickSkye** [comment]
@coderjay8989  looking good

**Comment by denaron** [comment]
@coderjay8989 looks great

**Comment by brianamarie** [comment]
Hi @coderjay8989! Make sure there are no spaces at the beginning of each line, I believe that's what is causing the tests to fail. 😄

**Comment by crichID** [comment]
@coderjay8989 I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/2512/commits/afae899254169d9c7d0feed8642094a25a4ffb56. Please take a quick look at the changes. Once the tests have finished running, please feel free to click the big green **Merge pull request** button. If you haven't merged it by Friday (January 27, 2017), I will go ahead and do it just to keep the repository clean!

**Pull request merged**
