### PR TITLE
Create ACDCaffrey.json

### PR DESCRIPTION
**Pull request by ACDCaffrey**
latitude and longitude added from a tutorial
from help by @githubteacher

### CODE REVIEW

**Comment by brianamarie** [comment]
Hi @ACDCaffrey! I've noticed your tests are failing. Make sure there are no spaces before the characters on lines 1-5. 😄

**Comment by cpoon4** [comment]
@ACDCaffrey looks like you got it down.

**Comment by packerfan626** [comment]
Hi! Just fix the spaces at the beginning of each line and it will fix your issues! It worked for me! Keep it up!

**Comment by isaacpak** [comment]
@ACDCaffrey Great job!

**Comment by crichID** [comment]
@ACDCaffrey I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/2577/commits/65e13ce13940d9dfdbc9a1d8ad2d4e560053f178. Please take a quick look at the changes. Once the tests have finished running, please feel free to click the big green **Merge pull request** button. If you haven't merged it by January 27th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
