### PR TITLE
Hi!

### PR DESCRIPTION
**Pull request by serenetso**
I wrote a message on my pull request!

### CODE REVIEW

**Comment by lovisamelnyk** [comment]
Nice work

**Comment by serenetso** [comment]
Let's learn to write hello world in different programming languages!

**Comment by serenetso** [comment]
@lovisamelnyk Check this out!

**Comment by egkelados** [comment]
**Good job**  @serenetso  :1st_place_medal:

**Comment by kerberos56** [comment]
Hello serenetso :-) 
Keep up the good work!

**Comment by ronaldochaves** [comment]
@serenetso 
All checks have passed and you are all set to merge your branch.
Could you do that?
Nice job until now 🎉

**Pull request merged**
