### PR TITLE
Adding Github Hall Student Coordinates

### LINKED ISSUE #7812: Jesse Year Up Student
If anyone could add me, I greatly appreciate it.

### PR DESCRIPTION
**Pull request by Jesse-S-H0711**
@Jesse-S-H0711 What do you think?

This pull request closes #7812

### CODE REVIEW

**Comment by Jesse-S-H0711** [comment]
@Jesse-S-H0711 What do you think?

The pull request closes #7812

**Comment by pugglett** [comment]
Jesse, you should be able to merge this pull request - your commit looks just fine!

**Comment by crichID** [comment]
@Jesse-S-H0711 you should just need to fix the filename so the tests will pass. If you need any assistance, check out this video: https://vimeo.com/201011288

**Comment by brianamarie** [comment]
@Jesse-S-H0711 Let me know if you need or want any help making these changes.  If they aren't made in a few days, someone from the GitHub training team will go ahead and make the changes and merge this pull request. 😄

**Comment by Jesse-S-H0711** [comment]
Feel free to do so.

________________________________

**Comment by meierjp57** [comment]
Looks like it took some time but it finally looks like ti will get merged. Well done!

**Pull request merged**
