### PR TITLE
Adding Deeva84's coordinates

### PR DESCRIPTION
**Pull request by Deeva84**
@githubteacher 

This pull closes #6622

### CODE REVIEW

**Comment by iootbob** [comment]
test

**Comment by Deeva84** [comment]
test

**Comment by Deeva84** [comment]
testing travis ci

**Comment by Deeva84** [comment]
new round of test

**Comment by Deeva84** [comment]
@githubteacher my checks keep failing due to Travis CI build failed. How do I fix this?

**Comment by uncleef** [comment]
Add '---' into your file, on top and bottom

**Comment by Deeva84** [comment]
@uncleef Thanks!

**Comment by uncleef** [comment]
@Deeva84 Try to remove number (84) from githubHandle into file...probably works now!

**Comment by Deeva84** [comment]
test

**Pull request merged**
