### PR TITLE
Add github's student's pin to the map

### PR DESCRIPTION
**Pull request by apolmig**
Add Tarragona to the map

this closes #5250

### CODE REVIEW

**Comment by shajanjp** [comment]
Your pin should be in this format.
```
---
githubHandle: <YOUR_USER_NAME>
latitude: <LATITUDE>
longitude: <LONGITUDE>
---
```

**Comment by newordn** [comment]
fix your error if you want to merge your pull request @apolmig

**Comment by hollenberry** [comment]
Hey @apolmig  !

@shajanjp is absolutely correct. You're almost there, but you'll need to match the format above. 

After that, you should be all set! 😄 👍

Please let us know if you need any help! We'll be closing this out to keep the repository clean if there's no action or conversation within the week.

**Comment by hollenberry** [comment]
@apolmig I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/5250/commits/41b504e29c30def8b7aa2c613a74fcc6f3e81191. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green Merge pull request button. If you haven't merged it by April 21st, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
