### PR TITLE
Add Klabautamann's pin to the map

### PR DESCRIPTION
**Pull request by Klabautamann**
Adding Vienna to the map
#2554

### CODE REVIEW

**Comment by bhbai** [comment]
@Klabautamann  look great :+1:

**Comment by bhbai** [comment]
yes.  :1st_place_medal:

**Comment by bhbai** [comment]
:tada:  :mag:

**Comment by crichID** [comment]
@Klabautamann  I went ahead and fixed the syntax and file naming issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/2554/commits/01181c78e1dbb731ed13192831ba9490d9bdc4d3. Please take a quick look at the changes. Once the tests have finished running, please feel free to click the big green **Merge pull request** button. If you haven't merged it by January 27th, I will go ahead and do it just to keep the repository clean!

**Comment by Klabautamann** [comment]
thankx!

**Pull request merged**
