### PR TITLE
Adding lau's coordinats

### LINKED ISSUE #8080: hello
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by laugalo21**
Hiiiii!

@emejiambge  wears black socks :)))

@RoberChavarria wears withe socks :((((

@githubteacher what do you think about it????
closes #8080

### CODE REVIEW

**Comment by davidnhz** [comment]
👍

**Comment by BriandaPena** [comment]
@laugalo21 this is great! 💯 🌮

**Comment by emejiambge** [comment]
you suck!!

**Comment by davidnhz** [comment]
You need to add the file inside the folder `_pins`

**Comment by crichID** [comment]
@emejiambge please use appropriate language when interacting with others in this repository. If you have any questions, please take a look at our [Community Guidelines](https://services.github.com/on-demand/community/).

**Comment by laugalo21** [comment]
@davidnhz How can I move the file to the correct folder?

**Pull request closed without merging**
