### PR TITLE
Pinning my first repository

### PR DESCRIPTION
**Pull request by SrRohitKandpal**
@githubteacher This is my first learning repository on Github. How you want to review this?

This pulll request closes #2879

### CODE REVIEW

**Comment by SrRohitKandpal** [comment]
@githubteacher

**Comment by octa-g** [comment]
Do not dispair, the reason why the checks fail are the spaces before the lines in the file . If you fix that, it should work 👍

**Comment by Kyle123z** [comment]
Sweet! 🍦

**Comment by brianamarie** [comment]
@SrRohitKandpal You're so close! I think there are still spaces at the front of lines 1 and 5.

**Comment by SrRohitKandpal** [comment]
Hello Sir/Mam,

I have edited the code 7 times i.e. 7 commits and in last three ones I have
removed all the spaces from front of 1 and 5 lines, but it's still showing
'All Checks Failed', I'm a real new learner on Git and Github, please help
me to solve this problem as soon as possible.

**Comment by SrRohitKandpal** [comment]
@githubteacher  I'm totally stuck here, even after removing spaces from the front of 1 and 5 lines, it's showing 'All Checks Failed'. I'm a beginner on Git and Github, help me out from this.

**Comment by brianamarie** [comment]
Hi @SrRohitKandpal! I hope it's OK - I went ahead and updated the file since you were SO close and have done such a good job in so many ways! 

The changes I made were small - I added `---` at the beginning and end of the file. You can see that change specifically [here](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/2879/commits/ee242e4cbc70779143ff54ee6bd566b42d2fcf51). 

Things that you have done SUPER well and you should be proud of:
- You completed the GitHub workflow! You made a branch and made commits! 
- When you got stuck, you kept with it. Learning Git is hard, and sticking with it is the best way to be successful. 
- You asked for help. Sounds simple, but the simple act of asking for help will take you far. 
- You kept committing and trying on the same PR. Some don't understand that a pull request is a comparison of two branches, so you can continue work. Some would have closed this pull request and started over. But, you did the right thing by continuing to make commits on this same branch.

Great job, @SrRohitKandpal! Go ahead and merge! 🚢

**Comment by SrRohitKandpal** [comment]
@brianamarie Thank you very much for your kind support and appreciation. All the things you told me in the comment, I'm feeling more confident and I will definitely learn Git to solve complex problems. Thanks again. Github is awesome.

**Pull request merged**
