### PR TITLE
adding ksullivan76 coordinates

### LINKED ISSUE #15958: Please add me - Waterford
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by ksullivan76**
@githubteacher What do you think?

This pull request closes #15958.

### CODE REVIEW

**Comment by pashambe** [comment]
@ksullivan76 great!

**Comment by jacobwestlund** [comment]
@ksullivan76 good work!

**Comment by DrQu** [comment]
@ksullivan76 Amazing job!!!

**Comment by ronaldochaves** [comment]
@ksullivan76 
All checks have passed and you are all set to merge your branch to the master one.
Could you do that?
After, you will be able to delete your branch safely.
regards ;)

**Comment by sethu90** [comment]
Well done
You are on the way to make wonders
Continue the spirit

**Comment by sarahipj** [comment]
Good job! Have a lovely week

**Pull request merged**
