### PR TITLE
Create JakeHam.json

### LINKED ISSUE #9451: Add me!
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by JakeHam**
Added myself to the map
@githubteacher 
closes #9451

### CODE REVIEW

**Comment by brianamarie** [comment]
@JakeHam  your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open by the end of next week.

**Comment by geoffraetz** [comment]
excellent

**Comment by martykopka** [comment]
zxcadasda

**Comment by martykopka** [comment]
yay

**Comment by martykopka** [comment]
@JakeHam ovide feedback :loudspeaker: and motivation :tada:.

**Pull request merged**
