### PR TITLE
add me too

### PR DESCRIPTION
**Pull request by silkypriya**
pin the location to map!

### CODE REVIEW

**Comment by silkypriya** [comment]
pin the location

**Comment by OpsScript** [comment]
hey @silkypriya,  i removed spaces before the ":" and its working now. 👍

**Comment by crichID** [comment]
@silkypriya your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on December 29th.

**Comment by Saichethan** [comment]
Done!!
Congratulations

**Pull request merged**
