### PR TITLE
Adding vincentlamphier's coordinates

### PR DESCRIPTION
**Pull request by vincentlamphier**
@githubteacher 

This pull request closes #9406

### CODE REVIEW

**Comment by jcllobet** [comment]
You are almost there! As you do the pull request, make sure to finish with:
Close #9406

**Comment by vincentlamphier** [comment]
Hi Jan! I don't quite understand what your asking me, did I not Close
#9406, or do I need to do it again?

**Comment by billchenchina** [comment]
@vincentlamphier You just need to click the green button “Merge pull request” to merge your branch to the repo,and that's all.

**Comment by dagolinuxoid** [comment]
Good job

**Pull request merged**
