### PR TITLE
Adding pinkysaid's coordinates

### LINKED ISSUE #10313: Please add me - Kilifi, Kenya
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by pinkysaid**
@githubteacher Well done?

This pull request closes #10313

### CODE REVIEW

**Comment by SheYoe** [comment]
@pinkysaid This looks great! 🎉

**Comment by Xiovera** [comment]
@pinkysaid Great job! :+1:

**Comment by brianamarie** [comment]
@pinkysaid your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open by the end of next week.

**Comment by eric-laporte** [comment]
It seems these coordinates are in Africa.

**Comment by pinkysaid** [comment]
@brianamarie @Xiovera @SheYoe  Thank you! 
@eric-laporte Yes it is in Africa. A town called Kilifi in Kenya.

**Pull request merged**
