### PR TITLE
add meeee

### PR DESCRIPTION
**Pull request by PulsatingStar**

### CODE REVIEW

**Comment by ikhall** [comment]
I had trouble with my first commit. I left the '.json' off my user name when I was creating the coordinate file.
ex. _pins/PulsatingStar.json

May this helps?

**Comment by hollenberry** [comment]
Almost there @PulsatingStar  ! Looks like you just need to change your name as @ikhall recommended, and convert the `Latitude` and `Longitude` strings to all lowercase. Ex: `latitude` and `longitude`. If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions! :tada:

**Comment by hollenberry** [comment]
@PulsatingStar   I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/7626/commits/1562eb09dc92b8dcba70af21f17a8b41e8fbd03a. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by June 30th, I will go ahead and do it just to keep the repository clean!

**Comment by alextor1810** [comment]
It looks great now :tada:  :+1:

**Pull request merged**
