### PR TITLE
Create xwmaxx.json

### PR DESCRIPTION
**Pull request by xwmaxx**
My location
@githubteacher 
This pull request closes #16758

### CODE REVIEW

**Comment by LivvyTaylor** [comment]
Syntax can be tricky! All I changed was the capital letters of Latitude and Longitude to lowercase

**Comment by tycrawford** [comment]
Glad it worked out for you!

**Comment by Inventrohyder** [comment]
Well done: 👍

**Comment by pulchrit** [comment]
Great work and excellent collaboration! :clap:

**Pull request merged**
