### PR TITLE
please add dankton

### PR DESCRIPTION
**Pull request by 00ep13**
closes 1597

hello dankness my old friend,
I've come to browse your memes again.

### CODE REVIEW

**Comment by stanley-godfrey** [comment]
Who am I to disagree :+1:

**Comment by tomtom304** [comment]
I r8 0/8 not enough memes.

**Comment by 00ep13** [comment]
@tomtom304 I am fully offended

**Comment by luciferchan** [comment]
spam

**Comment by 00ep13** [comment]
@luciferchan Im vegan

**Comment by crichID** [comment]
@00ep13 this looks good to merge! Please feel free to click the big green button above to **Merge pull request**.

If you haven't merged by 11/15/2016, a member of the GitHub training team will merge it for you 😉

**Pull request merged**
