### PR TITLE
Add slouda_mogao's pin to the map

### PR DESCRIPTION
**Pull request by slouda**
adding Mogao canvas to the map

### CODE REVIEW

**Comment by slouda** [comment]
Add slouda_mogao's pin to the map

**Comment by hollenberry** [comment]
Almost there @slouda  ! Looks like you just need to rename your file to be a part of the `_pins` directory (note the underscore), and make sure the extension is `.json` instead of `.jason`. If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions! :tada:

**Comment by hollenberry** [comment]
:tada: Nice work! Ready to merge! 🎈

**Comment by slouda** [comment]
_jason I Cried for you !!! 
@hollenberry  Thanks millions!

**Pull request merged**
