### PR TITLE
Adding qingmaliuguang's coordinats

### LINKED ISSUE #5585: Please add me -qingmaliuguang
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by qingmaliuguang**
@githubteacher  What do you think?

This pull request closes #5585 .

### CODE REVIEW

**Comment by hollenberry** [comment]
Hey @qingmaliuguang  !

You're very close! Edit the name of the file to be nested in the `pins` directory, and you should be all set! 😄  👍  Right now, it looks like `pin_yourfilename.json` instead of `pins_yourfilename.json`.

This video should help if there's any extra confusion: https://vimeo.com/201011288

Please let us know if you need any help! We'll be closing this out to keep the repository clean if there's no action or conversation within the week.

**Comment by qingmaliuguang** [comment]
Thank you @hollenberry !

**Comment by qingmaliuguang** [comment]
Could you please tell me how to delete the wrong file and the wrong directory?@hollenberry

**Comment by hollenberry** [comment]
Yes! Screenshot below:

screen shot 2017-04-17 at 1 49 06 pm


I actually went ahead and did this for you because finding that screen can seem unnecessarily complicated. In the future, you can typically delete files by selecting the trash can icon next to the edit icon.

Please let me know if you have any extra questions! You should be all set to merge!

**Comment by shanecarr1** [comment]
@qingmaliuguang I had to do the same thing and delete files. It's a little confusing, but looks like you're doing great 👍

**Comment by crichID** [comment]
@qingmaliuguang your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on April 21st.

**Comment by qingmaliuguang** [comment]
Thanks for your help @hollenberry !

**Comment by qingmaliuguang** [comment]
Thank you @shanecarr1 !

**Comment by qingmaliuguang** [comment]
Thank you @crichID !

**Comment by Anster04** [comment]
@qingmaliuguang parabens, continuai!...

**Pull request merged**
