### PR TITLE
Adding Rost87 coordinates.

### PR DESCRIPTION
**Pull request by Rost87**
@githubteacher I do something new.
This pull request closes #12785

### CODE REVIEW

**Comment by OpsScript** [comment]
@githubteacher 
detail Travis CI : 
[31m             Error: could not read file /home/travis/build/githubschool/open-enrollment-classes-introduction-to-github/_pins/**sjkaiser2,json**: undefined method `split' for nil:NilClass[0m

**Comment by crichID** [comment]
@Rost87 looking at the TravisCI results, it appears your file has some trailing spaces that need to be removed:

screen shot 2017-12-27 at 6 29 50 pm

If you need any assistance editing the file,  please check out this video: https://vimeo.com/201011288

**Comment by Saichethan** [comment]
Check Travis-CI settings

**Comment by Saichethan** [comment]
1.name directory as "_pins"/"Githandle"
2.turn on Travis-CI settings 
3.for resources check "on demand Github"

**Comment by brianamarie** [comment]
@Rost87  I made some changes so the tests will pass. Once everything turns green, I'll go ahead and merge this in since it's been a few days and we want to keep the repository clean. 😄 ✨

**Pull request merged**
