### PR TITLE
Adding my coordinates for map pin

### PR DESCRIPTION
**Pull request by navabromberger**
@githubteacher here's my my lang and long

Closes #2523

### CODE REVIEW

**Comment by navabromberger** [comment]
Updated my Close referene

**Comment by frazermuci** [comment]
what a delight, this is great. great pull request. simply great. jolly good show!

**Comment by navabromberger** [comment]
Can someone tell me why the checks are failing?  I can't figure it out.

**Comment by michaellnguyenn** [comment]
my checks are failing too @navabromberger

**Comment by michaellnguyenn** [comment]
found it, delete the spaces infront of each line

**Comment by navabromberger** [comment]
@michaellnguyenn  try deleting the spaces in front of each line.  Worked for me!

**Pull request merged**
