### PR TITLE
Mkaden is in mataró

### LINKED ISSUE #1706: Mataró
## Adding <Mataró> to the map

Hi everyone! This issue is to track the addition of <Mataró> to the map, which can be found at:

- Longitude: <41.538112>
- Latitude: <2.444741>

### PR DESCRIPTION
**Pull request by mkaden**
new addition

addsomething@githubteacher

closes #1

### CODE REVIEW

**Comment by mkaden** [comment]
yeeh blue color

**Comment by alisongobr** [comment]
yeah

**Comment by JRuiz7** [comment]
OOOOH MY GOOOOSH

**Comment by mkaden** [comment]
eewwww

**Comment by alisongobr** [comment]
holi

**Pull request merged**
