### PR TITLE
Create johannespejo.json

### PR DESCRIPTION
**Pull request by JohannEspejo**
Add me

### CODE REVIEW

**Comment by johannespejo** [comment]
Check again!

**Comment by crichID** [comment]
@JohannEspejo I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/2849/commits/437ce8a668faa0a3e87be822f3ab5aed09e0eac5. Please take a quick look at the changes. Once the tests have finished running, please feel free to click the big green **Merge pull request** button. If you haven't merged it by January 27th, I will go ahead and do it just to keep the repository clean!

**Comment by lydita** [comment]
help me

**Comment by crichID** [comment]
@lydita please do not click the big green **Merge pull request** button on pull requests you did not create! We want each student to have the opportunity to merge their own pull request!

**Pull request merged**
