### PR TITLE
Create teintoo.json

### PR DESCRIPTION
**Pull request by teintoo**

### CODE REVIEW

**Comment by freginold** [comment]
nice!

**Comment by NicholsSolutions** [comment]
Nice job

**Comment by Joachim92** [comment]
Everything looks good! 👍

**Comment by AumDove** [comment]
👍 :clap:

**Comment by stefan574** [comment]
:+1:

**Comment by andy-yangz** [comment]
Great!

**Comment by kim-codes** [comment]
Your changes look good! 👍

**Comment by dagiro** [comment]
oh my

**Pull request merged**
