### PR TITLE
Diegofontecilla london

### PR DESCRIPTION
**Pull request by diegofontecilla**
@githubteacher what do you think?
 
this is pull request closes ##15230.

### CODE REVIEW

**Comment by diegofontecilla** [comment]
i don't know what my extension should be. please help

**Comment by mpalmisano** [comment]
It should be .json

**Comment by stephenmatlock** [comment]
Keep on working!

**Comment by stephenmatlock** [comment]
@githubteacher  this is a comment

**Comment by Schiavi13** [comment]
@diegofontecilla You need to delete the one that's .md and just keep the other one that's .json

**Comment by 0zxo** [comment]
@diegofontecilla  hallo :wave: 
i deleted the file diegofontesilla.md from your branch and now is ready to merge
but you should post a comment or edit your comment saying:
> `@githubteacher` this pull request closes `#15229`

that's the number of your issue, this will close the issue after merging 
:zap:

**Pull request merged**
