### PR TITLE
Create jsObjects.json

### PR DESCRIPTION
**Pull request by jsObjects**
@githubteacher   add file to pin my profile on the map.

### CODE REVIEW

**Comment by ClicheUsername** [comment]
goodjob

**Comment by isema** [comment]
Update branch and merge pull request

**Comment by Hkhan15** [comment]
good job.

**Comment by githubteacher** [comment]
@jsObjects I would :heart: to see your pin on our map! Simply click the update branch button above, that will pull in the changes that have happened on master since you created this Pull Request. Then you should be able to click the big green merge button! Please let me know if you have any questions!

**Pull request merged**
