### PR TITLE
Create radicalpharaoh

### PR DESCRIPTION
**Pull request by radicalpharaoh**

### CODE REVIEW

**Comment by hectorsector** [comment]
@radicalpharoah - your code your be in the _pins directory and contain a json extension.

**Comment by radicalpharaoh** [comment]
Finally figured out how to make it a .json extension and add it to _pins directory. Took me longer than needed to realize what you meant. Sorry.

**Comment by hectorsector** [comment]
Thanks @radicalpharaoh now please make sure that you remove the extra formatting, the only thing in the file should be:

```
---
githubHandle: radicalpharaoh
latitude: 28.291956
longitude:-81.407571
---
```

**Comment by radicalpharaoh** [comment]
Done. Thank you for being so patient with me over this simple pull request I couldn't grasp.

**Comment by isema** [comment]
Needed a space in between the colon and negative symbol. Update branch and merge pull request.

**Pull request merged**
