### PR TITLE
Adding Exeter to the map

### LINKED ISSUE #30: Adding Exeter to the map
## Adding Exeter to the map

Hi everyone! This issue is to track the addition of Exeter to the map, which can be found at:

- Longitude: -3.533899
- Latitude: 50.718412

### PR DESCRIPTION
**Pull request by NickTikhonov**
This change adds **Exeter** to:

*  a new map, `exeter.topojson`
*  the existing `class-pins.topojson` map as a new pin.

These changes fix #30 

I would be interested in getting feedback on the position of the pin within Exeter, perhaps there could be a better place for the pin to go 😃 

cc @githubteacher

### CODE REVIEW

**Comment by FemiAw** [comment]
Looks good 👍 I'd probably put the pin right by the university but I'm a bit biased 😄

**Comment by brianamarie** [comment]
Looks good to merge! ✨  @NickTikhonov 🚢

**Comment by brianamarie** [comment]
@NickTikhonov  👋 Hello! I'd love to help you get this merge conflict figured out. Please let me know if you want some help! 

There are changes coming to this project and repository. To help get it ready, we are hoping to clean up some outstanding issues and pull requests. Unless I hear from you here, I am planning on closing this pull request without merging on **Friday, July 1st**. Thank you and happy coding! 😄

**Comment by crichID** [comment]
:wave: @NickTikhonov I believe you are getting a merge conflict because your branch modified the class-pins file. I am going to go ahead and resolve the merge conflict so we can see your pin on the map!

**Pull request merged**
