### PR TITLE
Handle smuhuri pin to the map

### PR DESCRIPTION
**Pull request by smuhuri**
Adding NJ to the map

### CODE REVIEW

**Comment by hbaer18** [comment]
@smuhuri This looks great! 🎉

**Comment by mysterioux** [comment]
@smuhuri your path link is not a json file kindly change your link which is currently as /_pins/sou to /_pins/sou.json and you are good to go.. Good luck

**Comment by brianamarie** [comment]
Hi @smuhuri! @mysterioux is correct - you'll need to rename your file so it ends in `.json`. Let me know if you need any help!

**Comment by crichID** [comment]
@smuhuri I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/4158/commits/1814a9117d70acb9c4d6a188dcd8f898cee76e8f. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by 3/17/2017, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
