### PR TITLE
Seattle

### LINKED ISSUE #1234: Seattle, WA
## Adding Seattle to the map

Hi everyone! This issue is to track the addition of Seattle to the map, which can be found at:
- Longitude: 47.6
- Latitude: -122.3

### PR DESCRIPTION
**Pull request by meganizr**
I added the lat and long values for my city. @githubteacher   This closes #1234

### CODE REVIEW

**Comment by geckya** [comment]
📢 🎉

**Comment by ad3z10** [comment]
:tada: :jack_o_lantern: :tada:

**Comment by jriosrodriguez** [comment]
Excellent work!!

**Comment by cristivela1217** [comment]
nicely done

**Pull request merged**
