### PR TITLE
Glen Allen Lat and Long

### PR DESCRIPTION
**Pull request by saluchau**
Not added as a contributor yet, so trying to see if I can use this fork to accomplish the same thing as creating a branch

### CODE REVIEW

**Comment by crichID** [comment]
> trying to see if I can use this fork to accomplish the same thing as creating a branch

@saluchau you can definitely use a fork to complete this project. The tests in this repository are very picky about the name and format of the file.  Here are some things  you will want to fix so your Pull Request will pass all of the checks:

- Move the file to the _pins` directory
- Add the `.json`  file extension to the file name
- Add three dashes `---` on the first and last line of the file
- On the second line, add an key/value pair as follows `githubHandle:  saluchau`
- Ensure latitude and longitude both begin with a lowercase `l`

Here is a video to help you make these changes:  https://vimeo.com/201011288 Please let me know if you have any questions!

**Comment by JPJ-GitProfile** [comment]
@saluchau  You can do this!  Update the file per the suggestions above and then recommit.   :+1:

**Comment by hollenberry** [comment]
@saluchau  I went ahead and fixed the syntax issues recommended by Cynthia above in 
https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/12206/commits/2f16893bcc56d806af436eef4e60c6141a28c056. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by December 15th, I will go ahead and do it just to keep the repository clean!

**Comment by saluchau** [comment]
thanks for the help @hollenberry and @crichID. My only options for this fork appear to be "close and comment" or "Comment". I do not have a Merge button. :-/

**Comment by crichID** [comment]
> My only options for this fork appear to be "close and comment" or "Comment". I do not have a Merge button. :-/

@saluchau yes, since you are working with a fork you cannot  merge  your own pull request. I will go ahead and do this for you now!

**Pull request merged**
