### PR TITLE
 @zalew16i coordinates.

### PR DESCRIPTION
**Pull request by marcosecchi**

### CODE REVIEW

**Comment by brianamarie** [comment]
@zalew16 Please don't merge other people's pull requests. This is a learning experience and it's more full when users can go through the whole process themselves. @marcosecchi If you'd like, I'm happy to revert this PR so you have a chance to press the big green button yourself. Either way, you did a great job and all the tests passed!

**Comment by marcosecchi** [comment]
@brianmarie no worries, just leave as it is! I just don't understand why @zalew16 changed the title. Was something wrong with the original one?

**Comment by brianamarie** [comment]
@marcosecchi, No, your title was perfect. I don't know why @zalew16 changed the title either... @zalew16 if you continue this type of behavior we will have to try some other strategies to keep the learning environment safe and predictable for all users.

**Comment by marcosecchi** [comment]
@brianamarie Cool! Thanks for the clarification.

**Pull request merged**
