### PR TITLE
Create nginx-training.json

### LINKED ISSUE #6614: Please add me as a collaborator
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by nginx-training**
@githubteacher How's this?

This closes #6614

### CODE REVIEW

**Comment by nginx-training** [comment]
comment

**Comment by nginx-training** [comment]
comment

**Comment by nginx-training** [comment]
this doesn't work

**Comment by hollenberry** [comment]
@nginx-training you're so close! That empty space on line 1 is probably triggering your errors. 

If you need help removing it, please let us know, but you're almost there!

**Comment by hollenberry** [comment]
@nginx-training  I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/6617/commits/2762e0f645645d83fc33718da7200ed6194adbf2. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by May 26, I will go ahead and do it just to keep the repository clean!

**Comment by crichID** [comment]
Oops it looks like this is a duplicate. I will go ahead and close out this pull request!

**Pull request closed without merging**
