### PR TITLE
Add noahsimpson's pin to the map

### PR DESCRIPTION
**Pull request by noahsimpson**
Adding Ottawa to the map!

### CODE REVIEW

**Comment by umaibal** [comment]
This looks great! :D

**Comment by franny11** [comment]
Sweet

**Comment by hollenberry** [comment]
Almost there @noahsimpson  ! Fun fact - writing this comment from the YOW airport. 

Looks like you just need to add three dashes to the end of your file, just like in line 1. Also, rename your file to be a part of the `_pins/` directory. If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions! :tada:

**Comment by hollenberry** [comment]
@noahsimpson  I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/9948/commits/e711b00abc2a66b600d9a42a29bf8f4253149811. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by September 22nd, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
