### PR TITLE
Create springseign.json

### PR DESCRIPTION
**Pull request by springseign**
Add **latitude && longitude** of my house
@githubteacher 
closes #4273

### CODE REVIEW

**Comment by brianamarie** [comment]
Hi @springseign! This looks great, go ahead and merge whenever you're ready! 🚢

**Comment by axblain** [comment]
Looks good

**Comment by crichID** [comment]
@springseign your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on March 17, 2017.

**Comment by worldnbw** [comment]
mute this thread

**Pull request merged**
