### PR TITLE
Create JosephAncil.json

### PR DESCRIPTION
**Pull request by JosephAncil**
Added the Longitude and Latitude with E & N respectively

I added an introduction file for GitHub teacher @githubteacher as requested

### CODE REVIEW

**Comment by JosephAncil** [comment]
Closing since I failed and retry the process and steps.

**Comment by JosephAncil** [comment]
Changed file as requested by jr-cologne

**Comment by JosephAncil** [comment]
I am having trouble, not sure what I am doing wrong @jr-cologne. Can you please help?

**Comment by jr-cologne** [comment]
You can just copy and paste the code I posted earlier. I can't see any changes in the diff.

**Comment by JosephAncil** [comment]
I am still having trouble, not sure what I am doing wrong @jr-cologne. I verbatim copied the code your mentioned, however my build still failed
---
githubHandle: JosephAncil
longitude: -74.759917
latitude: 40.295127
---

**Comment by jr-cologne** [comment]
Hm, very strange...

**Comment by crichID** [comment]
@JosephAncil you were SO close! The issue was that the file needed to be in the `_pins` directory and you had it in `pins`. You should be ok to merge now!

**Comment by crichID** [comment]
Actually, scratch that @JosephAncil it looks like you contributed via a fork so it will not allow you to merge until you are a collaborator. Just comment on #927 to be added as a collaborator!

**Pull request merged**
