### PR TITLE
About me!

### LINKED ISSUE #12794: Intro About Me!
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by amustaque97**
json file to pin me up on the map!

@githubteacher What do you think?

Please let me know if there is critical! Thank You

This pull request closes #12794 .

### CODE REVIEW

**Comment by shahsk0901** [comment]
that's great!

**Comment by withshubh** [comment]
@amustaque97 looks great! 🎉

**Comment by cccccccccccccc** [comment]
No problem

**Comment by anyadoc** [comment]
Looks good!

**Comment by Shwetabh1** [comment]
Looks neat

**Comment by crichID** [comment]
@amustaque97 your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on December 29th.

**Pull request merged**
