### PR TITLE
new pin for jMe1zer

### LINKED ISSUE #5506: Please add me
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by jMe1zer**
added my pin
closes #5506 
@githubteacher

### CODE REVIEW

**Comment by shajanjp** [comment]
You are almost there, add a new line after the last `---`. (Just press enter key)

**Comment by cmoten** [comment]
@jMe1zer, it looks like you still need to add a new line after the last --- by pressing enter.

**Comment by hollenberry** [comment]
@jMe1zer Looks like Cynthia was able to resolve your syntax errors in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/5508/commits/10013bba8aa866d44ca6eaff88092beacc1294b8 .Please go ahead and click the big green button below to Merge pull request. In an effort to keep things in this repository clean, I will merge this if it is still open on April 21st.

**Comment by crichID** [comment]
@jMe1zer for what it's worth, this was a tricky problem. You may want to try running `git config --global core.autocrlf true` on your command line to prevent this problem in the future.

**Pull request closed without merging**
