### PR TITLE
User's position

### PR DESCRIPTION
**Pull request by melsaa**

### CODE REVIEW

**Comment by samyrmoises** [comment]
@melsaa do you need any help?

**Comment by melsa08** [comment]
@samyrmoises yess, I want to know how to run git commands on Windows

**Comment by hollenberry** [comment]
> You must have a line that contains 3 dashes before and a line that contains 3 dashes after. Add the two lines and that will fix this problem

@melsaa , @AbrahamFriedman is correct. If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions! :tada:

**Comment by hollenberry** [comment]
@melsaa  I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/10607/commits/b980c320185e20756bef2148ea87447347a2071f. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by tomorrow, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
