### PR TITLE
Add BocianAJ pin to the map

### LINKED ISSUE #7881: Add me!
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by BocianAJ**
As requested by @githubteacher
I have added a file with my pin and commited it, this closes #7881

### CODE REVIEW

**Comment by shajanjp** [comment]
Replace `githubstudent` with your github username. That is `BocianAJ`

**Comment by Spandyie** [comment]
@BocianAJ Great Job!

**Comment by hollenberry** [comment]
Almost there @BocianAJ ! @shajanjp is correct! Once you make those changes, you should be set.

If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions! :tada:

**Comment by BocianAJ** [comment]
Thank you both  @hollenberry and @shajanjp , I have made the necessary change in my file.

**Pull request merged**
