### PR TITLE
Create nthanhhai.json

### PR DESCRIPTION
**Pull request by nthanhhai**
Adding coordinate of my location

### CODE REVIEW

**Comment by brianamarie** [comment]
@nthanhhai your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on November 10th.

**Comment by dsmit253** [comment]
This looks great!

**Comment by coolc23** [comment]
Looks great :+1:

**Comment by nthanhhai** [comment]
Thanks for your review :)

**Comment by nthanhhai** [comment]
@brianamarie I can't see the merge button here. Do I have write access on master?

**Comment by brianamarie** [comment]
Ah! I think since you created a fork, you do not. I will merge now. Great work! 🎉

**Pull request merged**
