### PR TITLE
This city is insane 

### PR DESCRIPTION
**Pull request by EmJD4**

### CODE REVIEW

**Comment by AmyLiyujie** [comment]
💯 👍

**Comment by marcozhuang21** [comment]
yeah totally

**Comment by hollenberry** [comment]
Hey @EmJD4 ! Almost there! You'll need to rename your file to include a _pins/ directory and a .json extension. Also, it looks like you might need to camel case githubHandle.

If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions!

**Comment by crichID** [comment]
@EmJD4 I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/6707/commits/98b67a844c4ad071374d226c53b82db24d8b00c4. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by May 26th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
