### PR TITLE
Adding jahernandez20000's Coordinates

### PR DESCRIPTION
**Pull request by jahernandez20000**

### CODE REVIEW

**Comment by hectorsector** [comment]
@jahernandez20000 you just need to add a `.json` extension to your filename and should be all set! [This video](https://vimeo.com/201011288) could help!

**Comment by metacman** [comment]
@jahernandez20000   IDK what this is ❓

**Comment by camerongibbs85** [comment]
I've changed the file extension for you and it is explained in my commit message.

**Comment by mmm93** [comment]
Hi, All looks good with the changes made by Cameron, well done both of you 👋

**Comment by crichID** [comment]
@jahernandez20000 your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on December 29th.

**Pull request merged**
