### PR TITLE
Adding JustinHartline's coordinates

### LINKED ISSUE #12003: Please add me. Thank you.
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by JustinHartline**
@githubteacher

This pull request closes #12003.

### CODE REVIEW

**Comment by BLittenberg** [comment]
@JustinHartline All good, I guess. 👍

**Comment by JustinHartline** [comment]
@brianamarie 

Hello. It looks as if my pull request was closed, so I believe I'm unable to merge to the main branch. Am I correct in this assumption?

**Comment by brianamarie** [comment]
Hi @JustinHartline! I'm sorry that your pull request got closed. You can 'reopen' the pull request with the grey button at the bottom next to "comment". I'll go ahead and do that now.  Let me know if you have any other questions 😄

**Comment by JustinHartline** [comment]
Thank you so much, @brianamarie! I noticed it's been added to "Merge on December 1", which the name being obvious, means it will be merged on that date. Can I/should I delete the branch in the interim?

**Comment by brianamarie** [comment]
@JustinHartline We add the milestone to help us keep track as maintainers. But, you can go ahead and merge this pull request and delete the branch now if you'd like! 😄 Great job!

**Comment by JustinHartline** [comment]
@brianamarie Hey, I'm sure you're absolutely knackered getting mentions from me! I don't believe I have write access to merge this request. Thank you for all of your help!

"Only those with write access to this repository can merge pull requests."

**Comment by brianamarie** [comment]
Hi @JustinHartline! No problem with the mentions. 😄 I'm glad you're asking for help! I'm not sure why you don't have access, you definitely used to because you were able to create a branch. 🤔 

In the meantime, you should have [an invitation here](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations). Once you accept this, you should be able to merge. Let me know if you run into any more problems!

**Pull request merged**
