### PR TITLE
yassss

### LINKED ISSUE #1618: saitama
## Adding saitama to the map

Hi everyone! This issue is to track the addition of saitama to the map, which can be found at:

- Longitude:34.694968
- Latitude: 135.548759

### PR DESCRIPTION
**Pull request by luciferchan**
closes #1618 

does mike wink or blink?

### CODE REVIEW

**Comment by MorganKendle** [comment]
Why, just why.

**Comment by jamesthelester** [comment]
well done

**Comment by willmerrr** [comment]
:100:

**Comment by fabcooldog** [comment]
You don't have spaces in between 'latitude:<number>'

**Pull request merged**
