### PR TITLE
Adding civvx's coordinates

### LINKED ISSUE #14579: Please add me - Amsterdam, Netherlands
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by civvx**
* Added my latitude and longitude @githubteacher 

closes #14579

### CODE REVIEW

**Comment by herrshatz** [comment]
Nice, good work!

**Comment by Techdemo** [comment]
Good work! Looks nice!

**Comment by jelub2** [comment]
Awesome! keep up the good work 💃

**Comment by gitelig** [comment]
Good work! 🎉

**Comment by MickeyBlueyez** [comment]
#14590 
Flossin on them @civvx 
closes #14590

**Pull request closed without merging**
