### PR TITLE
Create 4catkinson.json

### PR DESCRIPTION
**Pull request by 4catkinson**

### CODE REVIEW

**Comment by 4catkinson** [comment]
Location/User add. Following intro training course.

**Comment by tabathak** [comment]
Hey, you can assign to yourself too ;-)

**Comment by hollenberry** [comment]
Almost there @4catkinson  ! Looks like you just need to add a line of three dashes: `---`, above and below your current code. If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions! :tada:

**Comment by hollenberry** [comment]
@4catkinson  I went ahead and fixed the syntax issues in
https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/9470/commits/344e54977db3329c01dcbabfe174f7c7b8b0667f. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by August 25th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
