### PR TITLE
Create enchanthorse.json

### PR DESCRIPTION
**Pull request by enchanthorse**
hello!@githubteacher

this pull requests closes #940.

### CODE REVIEW

**Comment by roos** [comment]
@enchanthorse This looks great.

**Comment by roos** [comment]
@enchanthorse you can merge youre pr

**Comment by jackcouch** [comment]
looks good to me.

**Comment by camilaburne** [comment]
this looks **great ** !

**Comment by fongj2** [comment]
@enchanthorse This looks great! 🎉 📢

**Comment by NickSkye** [comment]
@enchanthorse looking enchanted

**Comment by jamesj228** [comment]
@enchanthorse perfect!

**Comment by ramydihom** [comment]
@enchanthorse Looks great!

**Comment by arcaf** [comment]
looks good!

**Pull request merged**
