### PR TITLE
alvie40.json

### PR DESCRIPTION
**Pull request by Alvie40**
Learning work with github

### CODE REVIEW

**Comment by Coder-Mustafa** [comment]
Nice One

**Comment by crichID** [comment]
@Alvie40 you are off to a great start! You just need to replace the placeholder text with your username and coordinates! Here is a quick video on how to make changes to your file: https://vimeo.com/201011288. Please let us know if we can help.

**Comment by qmixon** [comment]
@Alvie40 good for you  🎉

**Comment by brianamarie** [comment]
Hi @Alvie40! I'm going to close this pull request since it's been open for about 2 weeks with no more edits. Please feel free to reopen if you would like to continue. 😄

**Pull request closed without merging**
