### PR TITLE
Adding alisongobr.json

### LINKED ISSUE #1707: Tordera
## Adding <Tordera> to the map

Hi everyone! This issue is to track the addition of <Tordera> to the map, which can be found at:

- Longitude: <41.6948301>
- Latitude: <2.7085592>

### PR DESCRIPTION
**Pull request by alisongobr**
*added*
**Tordera**
@githubteacher 
closes #1707

### CODE REVIEW

**Comment by sith23** [comment]
Alison 0/2 checks GG.

**Comment by floyo13** [comment]
Cool!

**Comment by mkaden** [comment]
como mola tordera, to flama

**Comment by JosepJF** [comment]
ei good joob

**Comment by pabopicasso** [comment]
Nice!

**Pull request closed without merging**
