### PR TITLE
Add kayhanacan's pin to the map

### PR DESCRIPTION
**Pull request by kayhanacan**
Adding IST to the map!

### CODE REVIEW

**Comment by brianamarie** [comment]
@kayhanacan 👋 Hello! I added a space after the colon on line 2, let's see if the tests will pass! :crossed_fingers:

**Comment by kayhanacan** [comment]
@brianamarie Hello! I corrected folder name yet I can not pass the checks , could you please give me a hand about it? Thx in advance!

**Comment by kayhanacan** [comment]
@githubteacher Hi, I have issues to pass the checks, could you please help me about it? Thx

Closes #5899

**Comment by brianamarie** [comment]
Hi @kayhanacan! I tried changing the spelling of 'longitude', that _should_ do it. If not, I'll keep trying to find what's wrong. 😄

**Comment by mkselbee** [comment]
Looks to be correct.

**Comment by kayhanacan** [comment]
Thanks for your help @brianamarie

**Pull request merged**
