### PR TITLE
Adding mariaclaudia coord

### PR DESCRIPTION
**Pull request by mariaclaudia**
Added Cuneo lat e long with @githubteacher.closes #3761

### CODE REVIEW

**Comment by mariaclaudia** [comment]
What's wrong?

**Comment by Funce** [comment]
Hey @mariaclaudia
You actually have a full stop at the end of your file name.
That is the only thing I see.

**Comment by brianamarie** [comment]
Hi @mariaclaudia, just as @Funce said, the title of your file is incorrect. Try deleting the `.` at the very end. 😄  Let me know if you need help!

**Comment by hectorsector** [comment]
@mariaclaudia I went ahead and fixed the syntax issues in e93b862. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by Feb 24, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
