### PR TITLE
Create CPT-KERNEL.json

### LINKED ISSUE #18136: Add me - Grand Rapids, MI
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by cpt-kernel**
@githubteacher I added my pin.
closes #18136

### CODE REVIEW

**Comment by hftb** [comment]
@cpt-kernel - does it need to be case sensitive?

**Comment by montaspm** [comment]
You need to add the 3 dashes at the top and bottom and latitude and longitude must be in lowercase.

**Comment by montaspm** [comment]
Format of the File is Incorrect

The contents of your .json file should look like this:

  ---
  githubHandle: YOUR-USERNAME
  latitude:
  longitude:
  ---

**Comment by 0zxo** [comment]
@cpt-kernel

**Pull request merged**
