### PR TITLE
Add rahelutza's pin to the map!

### PR DESCRIPTION
**Pull request by rahelutza**
Adding Atlanta to the map
closes #940

### CODE REVIEW

**Comment by rahelutza** [comment]
Please build me!

**Comment by rahelutza** [comment]
Please build me!

**Comment by rahelutza** [comment]
Please build me!

**Comment by brianamarie** [comment]
@rahelutza  There are still a few errors in your file that are keeping the tests from passing. [Click "Help Me Troubleshoot" for some specific ideas](https://services.github.com/on-demand/intro-to-github/edit-files-on-github), or [watch this video to get some help](https://vimeo.com/201011288). If you need or want help, let me know! (I think the problem is with `githubhandle`. It's case sensitive, and should be `githubHandle`.) If this hasn't been resolved by the end of next week, I'll go ahead and make the changes for you so that it can be merged in. 😄

**Pull request merged**
