### PR TITLE
joshawalawa.coordinates

### LINKED ISSUE #15536: Please add me - Gaithersburg, MD
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by joshawalawa**
@githubteacher what do you think?
@joshawalawa added coordinates file

pull request closes #15536

### CODE REVIEW

**Comment by njgarfield** [comment]
@joshawalawa 
This looks great! 🎉

**Comment by nehadamele** [comment]
great!

**Comment by nehadamele** [comment]
@joshawalawa greaaat !

**Comment by mpm0000** [comment]
@joshawalawa it looks fine 🥇

**Comment by dengo1905** [comment]
@joshawalawa this looks promising 🥇

**Comment by AxentaCA** [comment]
@joshawalawa Looks good!

**Pull request merged**
