### PR TITLE
Adding Hicks7 localisation

### LINKED ISSUE #6130: Please add me - Maroua, extreme nord
#adding maroua to the map

Hi everyone ! This issue is to track addiction of maroua to the map, which can be found at : 

-Latitude = 10.604644
-longitude = 14.354539

### PR DESCRIPTION
**Pull request by Hicks7**
@githubteacher what do you think ?!
This pull request closes #6130 .

### CODE REVIEW

**Comment by shajanjp** [comment]
@Hicks7 
Looks great ! Now press the big green **Merge pull request** button below and your coordinates will be added to the map.

**Comment by shravane5** [comment]
@Hicks7  Hey! This looks good :tada:

**Comment by Z0L0** [comment]
Gr8 job,  @Hicks7!

**Comment by hollenberry** [comment]
Hey @Hicks7 ! Looks like this got closed accidentally, but feel free to merge when you're ready! 

If not, we'll lump this into our next big automated merge to keep the repo clean.

**Pull request merged**
