### PR TITLE
Manal/ vienna

### LINKED ISSUE #7731: Manal
Hello! :wave: Please add me as a collaborator to this repo. 
hello...

### PR DESCRIPTION
**Pull request by ManalsHanna**
@githubteacher please merge this changes

closes #7731

### CODE REVIEW

**Comment by AlexHartveld** [comment]
Hey Manal, you've added two files, please delete the other one that is not ending in .json

**Comment by ManalsHanna** [comment]
@githubteacher can you check that I only added one File.

**Comment by hollenberry** [comment]
Almost there @ManalsHanna  !

 Looks like you just need to make sure to rename the file and make it a part of the _pins directory. 

If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions! :tada:

**Comment by hollenberry** [comment]
@ManalsHanna  I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/7738/commits/f1738f58ff1391cc270d2336c95d1f56de43d1e4. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by June 30th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
