### PR TITLE
.

### PR DESCRIPTION
**Pull request by SefuLaBani**

### CODE REVIEW

**Comment by crichID** [comment]
@SefuLaBani it looks like you closed your pull request instead of merging it:

- When you close the pull request, it is like saying "I changed my mind and don't want to make this change". 
- When you merge the pull request, you are adding your code to the master branch and your pin will appear on the map. 

If you would like to merge it, you will want to make a small change to your file. Your tests were failing because you had a space in `github Handle`. Just make it all one word `githubHandle` and it should work. Then you will be able to press the big green **Merge pull request** button. We created this short video to show you how to make changes if you need it: https://vimeo.com/201011288

**Comment by shajanjp** [comment]
Your pin should be in this format.
```
---
githubHandle: <YOUR_USER_NAME>
latitude: <LATITUDE>
longitude: <LONGITUDE>
---
```

You added a space in `githubHandle`. Fix it and we are good to go. @SefuLaBani

**Comment by hollenberry** [comment]
Hey @SefuLaBani ! It looks like there's only one minor change left. 

Please feel free to re-open this PR to make the fix if you're ever interested in the future! For now, I'll close out the PR to keep the repository clean.

**Comment by crichID** [comment]
@SefuLaBani I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/4603/commits/abe84ec91cea84980b552ee96679ba39a202ff8b. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by April 21st, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
