### PR TITLE
Olie13201

### PR DESCRIPTION
**Pull request by Olie13201**
###something
or other###

### CODE REVIEW

**Comment by Olie13201** [comment]
closes #1592

**Comment by fabcooldog** [comment]
Hello Oliver :-1:

**Comment by Olie13201** [comment]
cheers pal

**Comment by crichID** [comment]
Hey @Olie13201 the reason you are unable to merge is because you need a space between the `:` and the value for your githubHandle and latitude. Once you fix this, you should be able to click the big green button to **Merge pull request**

**Pull request closed without merging**
