### PR TITLE
Adding coordinates

### LINKED ISSUE #17681: Please Add Me - Gurgaon, India !
## Adding Gurgaon to the map.

### PR DESCRIPTION
**Pull request by shivammckc**
@githubteacher what do you think?

This pull request closes #17681

### CODE REVIEW

**Comment by SdwOne** [comment]
@shivammckc Looks greate! Keep going! :+1:

**Comment by SdwOne** [comment]
@shivammckc motivation adding test :tada:

**Comment by shaynkun** [comment]
:+1:  Keep it up!

**Comment by pretty25** [comment]
hello checking --test test

**Comment by pretty25** [comment]
test close

**Pull request merged**
