### PR TITLE
Adding koderproxy's coordinates

### PR DESCRIPTION
**Pull request by koderproxy**

### CODE REVIEW

**Comment by MetalMacGyver** [comment]
Looks like you missed the step where you add a file in your new branch named: _pins/YOUR-USERNAME.json

**Comment by RobSchripsema** [comment]
Keep going!

**Comment by dmmargo** [comment]
niceee

**Comment by Tabitha4** [comment]
@koderproxy 

Woot!

**Comment by russellcoleman** [comment]
passing through

**Comment by Cameron2317** [comment]
leaving a supportive comment

**Comment by brianamarie** [comment]
@koderproxy There are still a few errors in your file that are keeping the tests from passing. [Click "Help Me Troubleshoot" for some specific ideas](https://services.github.com/on-demand/intro-to-github/edit-files-on-github), or [watch this video to get some help](https://vimeo.com/201011288). If you need or want help, let me know! If this hasn't been resolved by the end of next week, I'll go ahead and make the changes for you so that it can be merged in. 😄

**Comment by koderproxy** [comment]
pls merge this

**Comment by CaryF300** [comment]
Looks good, but appears to need a bit more work. 😉

**Comment by koderproxy** [comment]
how i correct travis ci problem

**Comment by jjaawbkearns** [comment]
_**You Got This!**_ :punch:

**Comment by CaryF300** [comment]
I believe the problems are because your file isn't correctly formatted. It should look like this:

`---`
`githubhandle: koderproxy`
`latitude: -30.3165`
`longitude: -78.0322`
`---`

You are missing the colons after the latitude and longitude settings, and have a degree symbol after them.

**Comment by koderproxy** [comment]
Ohk I will understand now how things work

**Pull request closed without merging**
