### PR TITLE
Add githubstudent's pin to the map

### PR DESCRIPTION
**Pull request by MauricioPaez**
Adding Bogota to the Map!

### CODE REVIEW

**Comment by MauricioPaez** [comment]
Can someone help me? I can't seem to be able to pin my position into the map

**Comment by a-a-ron** [comment]
Hey @MauricioPaez, make the "Latitude" and "Longitude" lowercase and your builds should pass.

**Comment by hectorsector** [comment]
@MauricioPaez you've got some great feedback from @a-a-ron and @shajanjp. Please let us know if we can help in any way!

**Comment by MauricioPaez** [comment]
Great! Thanks a lot for your support :)

**Pull request merged**
