### PR TITLE
creating psansom.json

### LINKED ISSUE #11579: 12 Men in the Huddle AAAAaaaaah!
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by psansom**
Added my pin

@githubteacher This is confusing, but closes #11579

### CODE REVIEW

**Comment by vishalalisetty** [comment]
Looks good!

**Comment by DanielOlivas** [comment]
@psansom This looks great! 💯 👍

**Comment by MohammedBari** [comment]
@psansom Good job

**Comment by aarondhorowitz** [comment]
@psansom This looks **great!**

**Comment by djbrooks** [comment]
psansom, you are a ROCK STAR. Well done and I agree: This *is* a little confusing... :)

**Comment by g-anvesh** [comment]
Well done !!!

**Comment by psansom** [comment]
I want to add a comment into the pin file, just to see what it's like to modify the file.  What is the correct syntax?  Is it "//" like in C code, or something else?

**Pull request merged**
