### PR TITLE
Create milenkobrkovic.json

### PR DESCRIPTION
**Pull request by milenkobrkovic**
Adding location
@githubteacher

### CODE REVIEW

**Comment by milenkobrkovic** [comment]
pass

**Comment by milenkobrkovic** [comment]
git fetch origin
git checkout -b github-Milenko origin/github-Milenko
git merge master

**Comment by crichID** [comment]
@milenkobrkovic I believe your checks are failing because you have added a `city` line. If you remove that line, the checks should pass. If you need help, check out this video: https://vimeo.com/201011288

**Comment by hollenberry** [comment]
Hey @milenkobrkovic ! This is good to merge! When you're ready, go ahead and click that big green `Merge Pull Request` button! If you don't do it by the milestone date, we'll go ahead and run that for you in the background.

Let us know if you need any help or have questions! 🎉

**Comment by milenkobrkovic** [comment]
Hello,

I have removed city line, but I have no Merge Pull Request button? What is
a problem?
How to commit it.

Thanks in advance!

Kind regards,

**Comment by hollenberry** [comment]
@milenkobrkovic This is actually good to go! You can feel free to click the big green `Merge Pull Request` button below whenever you're comfortable!

**Pull request merged**
