### PR TITLE
Create fvillaamil.json

### PR DESCRIPTION
**Pull request by fvillaamil**
Identifying Latitude and Longitude for my location

### CODE REVIEW

**Comment by aisa0906** [comment]
feedback :loudspeaker: and motivation :tada:

**Comment by grandpotato** [comment]
more feedback 📢 and motivation 🎉

**Comment by eprattic** [comment]
even more feedback :loudspeaker: and motivation :tada:

**Comment by hectorsector** [comment]
😆 thanks for the feedback 📢 and motivation 🎉 @aisa0906 @grandpotato @eprattic!

@fvillaamil this looks ready to 🚢! Go ahead and click the green merge button when you're ready. We're all with you ❤️

**Comment by 3xj** [comment]
Is it too late to offer feedback 📢 and motivation 🎉 ?

**Comment by crichID** [comment]
@fvillaamil I see that you submitted this work via a fork and therefore will not be able to do the merge yourself! I will go ahead and :ship: this for you - great work!

**Pull request merged**
