### PR TITLE
my location coff* coff*

### PR DESCRIPTION
**Pull request by Asbert69**

### CODE REVIEW

**Comment by tabathak** [comment]
@Asbert69 , sorry if I'm intruding, but I made a little change in your code adding spaces 😉

**Comment by tabathak** [comment]
@githubteacher can you help us understand what are the failed checks please?
I assumed it was some spaces missing but it did not solve the problem.
Other guess is the branch being wrong/not created. In this case, how do we link this Pull Request to the branch?
Thanks

**Comment by hollenberry** [comment]
Almost there @Asbert69 + @tabathak  ! 

Looks like you'll need to rename the file to _pins/asbert69.json , and change githubhandle case sensitivity to githubHandle!

If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions! :tada:

**Comment by billchenchina** [comment]
Yep,the filename is wrong
you need to add “.json”at the end of the filename

**Comment by hollenberry** [comment]
@Asbert69   I went ahead and fixed the syntax issues in
https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/9475/commits/ed362a0eff12c49f7f032e8499a60e04990518b0. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by August 25th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
