### PR TITLE
Kindly add githubschool-capetown's pin to the map

### PR DESCRIPTION
**Pull request by FuProNix**
Adding CT to the map - 2nd try

### CODE REVIEW

**Comment by brianamarie** [comment]
@FuProNix There are still a few errors in your file that are keeping the tests from passing. [Click "Help Me Troubleshoot" for some specific ideas](https://services.github.com/on-demand/intro-to-github/edit-files-on-github), or [watch this video to get some help](https://vimeo.com/201011288). If you need or want help, let me know! If this hasn't been resolved in a few days, one of the trainers will go ahead and make the changes for you so that it can be merged in. 😄

**Comment by Randian368** [comment]
Mmmm maybe you should use markdown and reference the issue of your's - you know that .json file's #number that you've created earlier! Good luck! :hungary: :us:

**Comment by Yannmm** [comment]
@FuProNix I think you are doing great.🎉

**Comment by hectorsector** [comment]
@FuProNix I went ahead and fixed the syntax issues in 4ba3a9e. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by Monday, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
