### PR TITLE
Create angelineviray's coordinates

### LINKED ISSUE #5493: Please add me, thanks! :) angelineviray - Taguig City, Philippines
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by angelineviray**
@githubteacher This good? :)

This closes #5493.

### CODE REVIEW

**Comment by shajanjp** [comment]
This is fantastic ! Now press the big green **Merge pull request** button below and your coordinates will be added to the map.

**Comment by lp0rc** [comment]
Proving feedback, turned up to 11!

**Comment by peoray** [comment]
looking good 🎉

**Comment by hollenberry** [comment]
Hey @angelineviray!

Like @shajanjp said, this looks great! Go ahead and merge!

Please let us know if you need any help! We'll be closing this out to keep the repository clean if there's no action or conversation within the week.

**Comment by Anster04** [comment]
@angelineviray uau você conseguiu, parabens!... o meu até agora esta a dar erro. Mais já estou consertando com ajuda do @crichID.

**Comment by angelineviray** [comment]
Thanks everyone! :) I'm learning the ropes! :)

**Pull request merged**
