### PR TITLE
longitude and latitude info for charlottesville

### PR DESCRIPTION
**Pull request by janedlene**
File containing city longitude and latitude

### CODE REVIEW

**Comment by jcombs0929** [comment]
@janedlene **Good Work!** *Keep Going!*

**Comment by JoAnnaEsq** [comment]
@janedlene Looking good! :tada:

**Comment by crichID** [comment]
@janedlene  your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**.

**Comment by lydita** [comment]
lydiae.

**Pull request merged**
