### PR TITLE
Guiyuliu s

### PR DESCRIPTION
**Pull request by guiyuliu**
please add my coordinates

### CODE REVIEW

**Comment by 600rob** [comment]
@guiyuliu looks fine to me

**Comment by 600rob** [comment]
Opps my bad @guiyuliu , closed by accident. reopened again

**Comment by brianamarie** [comment]
Hi @guiyuliu! For this to pass, try adding a line at the beginning of your file with three hyphens, `---`. Let me know if you need any help!

**Comment by crichID** [comment]
@guiyuliu @600rob I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/4253/commits/dac721c782cb4816cac20bb29bdc24181e3a08ae and https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/4253/commits/162dcc4d5bab620b429826a10ae4c18347338511. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by March 17, 2017, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
