### PR TITLE
Adding lloydouyang's Introduction

### PR DESCRIPTION
**Pull request by lloydouyang**
I added an  **introduction** file lloydouyang as requested in #1

@githubteacher
closes #1

### CODE REVIEW

**Comment by lloydouyang** [comment]
hmmm

**Comment by crichID** [comment]
@lloydouyang the reason the build is failing is that you have a space at the beginning of each line. If you click the **Files changed** tab at the top of this pull request, you will see a small pencil at the top right of the file. Click that and you will be back in edit mode! Please let me know if I can help!

**Comment by crichID** [comment]
@lloydouyang it looks like we also needed to update your branch with some things I fixed earlier tonight! It should be all set now!

**Comment by lloydouyang** [comment]
fixes #3431

**Comment by lloydouyang** [comment]
@githubteacher I forgot to type fixes #3431 when I merged. Is that the reason that I don't have this issue closed?

**Comment by crichID** [comment]
> I didn't type fixes #3431 when I merged. Is that the reason that I don't have this issue closed?

@lloydouyang yes! It should actually be in the opening comment of the pull request, or you can add it when you merge the pull request.

**Comment by lloydouyang** [comment]
so now how can I close the issue?

**Pull request merged**
