### PR TITLE
Create OsvaldoDiaz.json.

### PR DESCRIPTION
**Pull request by OsvaldoDiaz**
coordenadas randoom

### CODE REVIEW

**Comment by davidnhz** [comment]
👍

**Comment by lokilontan** [comment]
@davidnhz гхнида

**Comment by crichID** [comment]
@OsvaldoDiaz it looks like you just have a couple small things to fix:

1. You will need to remove the extra `.` at the end of your filename.
2. You will need to remove the trailing spaces at the end of your code:

screen shot 2017-07-02 at 11 47 27 am

If you need any help making the changes, please check out this quick video: https://vimeo.com/201011288

**Comment by brianamarie** [comment]
@OsvaldoDiaz :wave: Let us know if you want or need any help making these changes. If in a few days the changes still aren't made, one of the GitHub trainers may make the changes for you to keep the repository clean. ✨

**Pull request merged**
