### PR TITLE
Add my pin to the map

### PR DESCRIPTION
**Pull request by BullfrogFTW**
Fixing mistakes, hopefully

### CODE REVIEW

**Comment by BullfrogFTW** [comment]
@githubteacher What have I done wrong, that it is not passing the check?

**Comment by brianamarie** [comment]
@BullfrogFTW As I commented on the commit, the name isn't quite right. Try adjusting to `_pins/bullfrogftw.json`. 👍

**Comment by HelioRochaCardoso** [comment]
@BullfrogFTW the only issue I saw there is with githubhandle:bullfrogftw. You must leave a space between after the colon : then it should be fine 👍

**Comment by madhavprapurna** [comment]
@BullfrogFTW  try it again

**Comment by badcoder28** [comment]
Hey instead of `githubhandle` try `githubHandle`

**Comment by hectorsector** [comment]
@BullfrogFTW I went ahead and fixed the syntax issues in 0a22383. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by tomorrow, I will go ahead and do it just to keep the repository clean!

**Pull request closed without merging**
