### PR TITLE
Add more tests

### PR DESCRIPTION
**Pull request by brianamarie**
@hectorsector @crichID @hollenberry @beardofedu Adding some tests here to try and get pins in the correct directory with the correct line ending. WIP 🚧

### CODE REVIEW

**Comment by crichID** [comment]
@brianamarie :sparkles: :sparkles: :sparkles: :sparkles: :heart: :sparkles: :sparkles: :sparkles: :sparkles:

**Comment by brianamarie** [comment]
OK  - @crichID @hectorsector @beardofedu @hollenberry If anyone has time to test this locally, please do! Looks good from my end. 👍

**Comment by hectorsector** [comment]
Looks great @brianamarie! This is a huge improvement from what we currently have. 

Here's what I tested on the `test-brianamarie-ci` branch:
❌ [pin with proper syntax in root directory](https://travis-ci.org/githubschool/open-enrollment-classes-introduction-to-github/builds/172003749)
❌ [pin without any extension](https://travis-ci.org/githubschool/open-enrollment-classes-introduction-to-github/builds/172007761)
❌ [pin with `txt` extension](https://travis-ci.org/githubschool/open-enrollment-classes-introduction-to-github/builds/172008383)
❌ [pin without `---` in yaml front-matter](https://travis-ci.org/githubschool/open-enrollment-classes-introduction-to-github/builds/172008855)
✅ [pin with proper syntax in `_pins` directory](https://travis-ci.org/githubschool/open-enrollment-classes-introduction-to-github/builds/172004499)

This one passed when it wasn't supposed to, but there's always going to be one, right? 
❓ [pin with coordinates in ° instead of decimal](https://travis-ci.org/githubschool/open-enrollment-classes-introduction-to-github/builds/172009326)

**Comment by brianamarie** [comment]
@hectorsector :bowing_woman: Thank you so much for testing! 

> This one passed when it wasn't supposed to, but there's always going to be one, right? 
> ❓ pin with coordinates in ° instead of decimal

🤔 Hmm...I can and will definitely look into that! 

@crichID @hectorsector @beardofedu @hollenberry  Thoughts of merging this in, then iterating on tests to be better?

**Pull request merged**
