### PR TITLE
Create MJThompson1st-Peoria

### LINKED ISSUE #1588: Peoria
## Adding Peoria to the map

Hi everyone! This issue is to track the addition of Peoria to the map, which can be found at:

- Longitude: 40.752177
- Latitude: -89.612861

### PR DESCRIPTION
**Pull request by MJThompson1st**
closes #1588

### CODE REVIEW

**Comment by Vitreusak** [comment]
Good work! Congratulations on your first pull request! :+1:

**Comment by ZacharyMC** [comment]
You smell like a leper gnome! Your mother was a murloc!

**Comment by Stratty** [comment]
maestro yi main

**Comment by MJThompson1st** [comment]
Follow me on MySpace

**Comment by crichID** [comment]
@MJThompson1st you will need to add the `.json` extension to the end of the file name in order for your build to pass. Just click on the **Files Changed** tab above and then add it next to the file name. Then you will scroll to the bottom of the page and commit your changes! Good luck and please let us know if we can help!

**Pull request merged**
