### PR TITLE
Added pin to map

### LINKED ISSUE #1599: Adding Peterborough
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: 52.579844
- Latitude: -0.242094

### PR DESCRIPTION
**Pull request by stpd11**
closes #1599 I have added Peterborough.
@githubteacher

### CODE REVIEW

**Comment by Olie13201** [comment]
great job @stpd11

**Comment by nfjackson5** [comment]
really good work, sir.

**Comment by nfjackson5** [comment]
:100: :100: :

**Comment by Olie13201** [comment]
:+1:

**Comment by JoshuaMJ2001** [comment]
:cactus: hi cameron
#1586

**Comment by JoshuaMJ2001** [comment]
:100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :kiss: :blonde_man: :black_man:

**Comment by JoshuaMJ2001** [comment]
i like :chicken:

**Comment by JoshuaMJ2001** [comment]
:hocho: do you know jamie fisher?

**Pull request closed without merging**
