### PR TITLE
Specialkid1337's coordinates

### PR DESCRIPTION
**Pull request by Specialkid1337**
@githubteacher 

Closes #10216 

lovin' this tutorial
also join OU GDA, this is your (hopefully if you join) President speaking---I'm here to help!

### CODE REVIEW

**Comment by pickles976** [comment]
cool username brotendo

**Comment by noahzemlin** [comment]
true

**Comment by Specialkid1337** [comment]
ayy lmao

**Comment by noahzemlin** [comment]
i think you need to feed the hamster that runs this bot more if you want it to work

**Comment by Specialkid1337** [comment]
No, it's time to go Super Human...and FURTHER...BEYOND!

AAAAAAAAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Pull request merged**
