### PR TITLE
Create jordanrburger.json

### PR DESCRIPTION
**Pull request by jordanrburger**

### CODE REVIEW

**Comment by mrw7474** [comment]
👍

**Comment by clough11** [comment]
Way to go 💯 🍔 🍰 !

**Comment by brianamarie** [comment]
@jordanrburger  your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open by the end of the week.

**Comment by brianamarie** [comment]
@SamHep0803 Please do not merge or close other people's pull requests. @jordanrburger, since you didn't get a chance to complete the activity, please let me know if you have any questions.

**Pull request merged**
