### PR TITLE
adds shajanjp's location pin

### PR DESCRIPTION
**Pull request by shajanjp**
Adds geo location of @shajanjp to the list of pins.

### CODE REVIEW

**Comment by krydev** [comment]
@shajanjp Hello from Ukraine:)

**Comment by WallenHan** [comment]
@shajanjp   
haha, you are in the other side  of the world.

**Comment by brianamarie** [comment]
Hi @shajanjp! This looks great, go ahead and merge whenever you're ready!

**Comment by jasonm8197** [comment]
Hey! New to github

**Comment by brianamarie** [comment]
Hi @shajanjp! Since it's been a few days, I'm going to go ahead and merge your file into master. Good work! 🎉

**Comment by shajanjp** [comment]
@brianamarie Thanks !

**Pull request merged**
