### PR TITLE
Add @carolinaknoll pin to the map

### LINKED ISSUE #707: Adding Florianópolis, Brazil to the map
## Adding Florianópolis, Brazil to the map

Hi everyone! This issue is to track the addition of Florianópolis (Santa Catarina, Brazil) to the map, which can be found at:

- Longitude: -48.548050
- Latitude: -27.595378

Thank you!   :earth_americas:

### PR DESCRIPTION
**Pull request by carolinaknoll**
Hello! @githubteacher, I would like to please add my pin to the map. Thank you! :sparkles: 
This PR closes #707.

### CODE REVIEW

**Comment by adonozo** [comment]
Looks good to me :+1:

**Comment by hummatli** [comment]
Excellent, it looks good 👍

**Comment by gavilancomun** [comment]
Looks good.

**Comment by RCMiron** [comment]
awesome location!

**Comment by RCMiron** [comment]
awesome [location](https://www.google.com.cy/search?q=Florian%C3%B3polis,+Brazil&espv=2&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiw1sTZxJTPAhXKCMAKHRoPA5EQ_AUICCgB&biw=1366&bih=643#imgrc=NEQXeGiQXQ8XoM%3A)

**Comment by jmlxrob** [comment]
Looks good!

**Comment by aarvizu** [comment]
Looks Good

**Comment by basellers1** [comment]
Looks like you're a pro already!

**Comment by basellers1** [comment]
:revolving_hearts:

**Comment by dtun** [comment]
Cool! Nice work.

**Comment by carolinaknoll** [comment]
Thanks everyone for the positive feedback! 
I hope you are doing great with learning about GitHub as well! ✨

**Pull request merged**
