### PR TITLE
Robin xiangbin nie calgary

### PR DESCRIPTION
**Pull request by RobinxiangbinNie**
I had put the json file in the wrong folder and just corrected.

### CODE REVIEW

**Comment by omque** [comment]
Hey @RobinxiangbinNie, you may want to assign this PR to yourself so the system clears you for it! Good luck!

**Comment by omque** [comment]
Sorry, one more comment! Noticed that the file is named -json, it should be ".json". So you probably want to change it from "RobinxiangbinNie-json" -> "RobinxiangbinNie.json"

**Comment by crichID** [comment]
@RobinxiangbinNie you are very close to being finished! I went ahead and made two small changes for you, I removed the extra file and I changed the -json to .json. I left a couple things for you to fix as well:

- Remove the blank lines in the file.
- Add a space after each `:`

I created a quick video to show you how to make these changes: https://vimeo.com/201011288

Please let me know if you need any additional help!

**Comment by damooch** [comment]
comment

**Comment by crichID** [comment]
@RobinxiangbinNie I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/3295/commits/06c9d625d2fb71f9ed7db16b45be074c66460193. Please take a quick look at the changes. Once the tests have finished running, please feel free to click the big green **Merge pull request** button. If you haven't merged it by February 10th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
