### PR TITLE
Create spmcelrath.json

### PR DESCRIPTION
**Pull request by spmcelrath**
My latitude and longitude @githubteacher closes #3

### CODE REVIEW

**Comment by crichID** [comment]
@spmcelrath this looks great! Feel free to click the green **Merge pull request** button when you are ready!

**Comment by sathyacse67** [comment]
hey there, @spmcelrath 
Nice to meet you man..

**Comment by hoodin** [comment]
good

**Comment by brianamarie** [comment]
Hi @spmcelrath! Since this is ready to merge and has been waiting for a few weeks, I'm going to go ahead and merge for you. Nice work!

**Pull request merged**
