### PR TITLE
Adding afaaqalam's coordinates

### PR DESCRIPTION
**Pull request by afaaqalam**
Added github username, latitude and longitude.

### CODE REVIEW

**Comment by afaaqalam** [comment]
Followed the format for adding the pin @githubteacher 
close #3082

**Comment by mmm-code** [comment]
this looks great :1st_place_medal:

**Comment by lloydouyang** [comment]
👍

**Comment by crichID** [comment]
@afaaqalam your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**.

**Comment by andriybilous** [comment]
@afaaqalam This looks good

**Comment by crichID** [comment]
@afaaqalam your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on February 3rd.

**Pull request merged**
