### PR TITLE
Add githubstudnets pin to the map

### PR DESCRIPTION
**Pull request by jaiyadur**
Adding ott to map
closes

### CODE REVIEW

**Comment by samyrmoises** [comment]
@jaiyadur do you need any help with it?

**Comment by samyrmoises** [comment]
@jaiyadur  Check the details of the failed checks to finish this tutorial! see ya.

**Comment by hollenberry** [comment]
@jaiyadur , @AbrahamFriedman is correct. Once you make those fixes, you should be all set. 

If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions! :tada:

**Comment by hollenberry** [comment]
@jaiyadur I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/10613/commits/8db3661fdd2e19a642efac1cb47de8dd41850be9. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by October 20th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
