### PR TITLE
Maddiesavich detroit

### PR DESCRIPTION
**Pull request by maddiesavich**
Adding **myself** to map for the workshop at UR

- This
- is
- a
- list

#### TODO

- [x] Things to do
- [x] This other thing

closes #11967
cc: @githubteacher

### CODE REVIEW

**Comment by definitelynotavirus** [comment]
😸

**Comment by maddiesavich** [comment]
nice

**Comment by dan461** [comment]
1.

**Comment by dan461** [comment]
1. 👍 
2. 💯

**Pull request merged**
