### PR TITLE
prkiso.json

### PR DESCRIPTION
**Pull request by prkiso**
Add London coordinates

### CODE REVIEW

**Comment by prkiso** [comment]
Add coordinates of London to map @githubteacher 
closes #2564

**Comment by brianamarie** [comment]
Hi @prkiso! Make sure you replace the text 'YOUR-USERNAME' with 'prkiso'. 😄

**Comment by jessicmz** [comment]
Good catch @brianamarie

**Comment by crichID** [comment]
@prkiso I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/2564/commits/aabee30b626423b407db02979f1015cfa3cefb4b. Please take a quick look at the changes. Once the tests have finished running, please feel free to click the big green **Merge pull request** button. If you haven't merged it by January 27th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
