### PR TITLE
Add laroucol pin to the map

### PR DESCRIPTION
**Pull request by laroucol**
Adding LsQ to the map

### CODE REVIEW

**Comment by martinmphil** [comment]
@laroucol Bonjour au Québec. Pardon je suis anglais et ne parle pas français. Great fast ice skating photo :-)

**Comment by laroucol** [comment]
Thank you @martinmphil 
If you want some more, go see my Red Bull Crashed Ice race in Edmonton, Canada on www.redbull.tv
Full link: http://moments.redbull.tv/events/meta/237?cttp=heat:5260&eq=cf%3As1&streams=360&burl=https%3A%2F%2Fwww.redbull.tv%2Fvideo%2FAP-1TYXZB9SS1W11%2Ffinals-edmonton-canada

**Comment by laroucol** [comment]
Yes, i'm doing my master degree in environmental sciences. 
I need to fix one code on GitHub that i'm using for my thesis. It allow me to calculate the mass balance over a glacier for several years.
Git looks so powerfull to keep an history on my code. Just need to know the basics.
Thank you @martinmphil

**Comment by martinmphil** [comment]
Fascinating stuff; good luck with your coding.

**Pull request merged**
