### PR TITLE
Create nmattamGitHub.json

### PR DESCRIPTION
**Pull request by nmattamGitHub**
Adding pins for nmattamGitHub

### CODE REVIEW

**Comment by nmattamGitHub** [comment]
nmattamGitHub-Chennai merged to master: pull request

**Comment by nmattamGitHub** [comment]
nmattamGitHub-Chennai pull request

**Comment by nmattamGitHub** [comment]
master: nmattamGitHub: pull request

**Comment by nmattamGitHub** [comment]
You have created your Pull Request.

**Comment by nmattamGitHub** [comment]
nmattamGitHub-Chennai pull request

**Comment by crichID** [comment]
@nmattamGitHub it looks like you may have closed your pull request instead of merging it. If you close it, your branch will not be merged into master and you will not be able to see your pin on the map. I am going to reopen it now. Please feel free to click the big green button below to **Merge pull request**.

If you haven't merged by 11/15/2016, a member of the GitHub training team will merge it for you 😉

**Pull request merged**
