### PR TITLE
Laugalobranch

### LINKED ISSUE #8080: hello
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by laugalo21**
Hi! 

@githubteacher what do you think about it ?

this closes #8080

### CODE REVIEW

**Comment by davidnhz** [comment]
👍

**Comment by chatsgris** [comment]
👍 🎆

**Comment by crichID** [comment]
@laugalo21 you will need to rename your file `_pins/laugalo21.json` in order for your checks to pass. If you need any help making the changes, please check out this quick video: https://vimeo.com/201011288

**Comment by brianamarie** [comment]
@laugalo21  :wave: Let us know if you want or need any help making these changes. If in a few days the changes still aren't made, one of the GitHub trainers may make the changes for you to keep the repository clean. ✨

**Pull request merged**
