### PR TITLE
adding coords

### LINKED ISSUE #13448: hello please add me
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by wjen**
@githubteacher what do you think?

This pull request closes #13448

### CODE REVIEW

**Comment by Altgear** [comment]
@wjen nice work 🍰

**Comment by ewilde14** [comment]
great work!

**Comment by sheickson** [comment]
Awesome

**Comment by hectorsector** [comment]
@wjen this looks great, ship it!

**Pull request merged**
