### PR TITLE
Create willmerrr.json

### LINKED ISSUE #1590: Aleppo
## Adding Aleppo to the map

Hi everyone! This issue is to track the addition of Aleppo to the map, which can be found at:

- Longitude: 36.202374
- Latitude: 37.122021

### PR DESCRIPTION
**Pull request by willmerrr**
closes #1590

### CODE REVIEW

**Comment by 00ep13** [comment]
here's some motivation

**Comment by loc3219** [comment]
not even good :-1:

**Comment by crichID** [comment]
@willmerrr this looks good to merge! Please feel free to click the big green button above to **Merge pull request**.

If you haven't merged by 11/15/2016, a member of the GitHub training team will merge it for you 😉

**Comment by sunjolia** [comment]
motivation wooo

**Pull request merged**
