### PR TITLE
Adding my coordinates

### PR DESCRIPTION
**Pull request by amycullen2**
@githubteacher
This pull request closes #13027

### CODE REVIEW

**Comment by dmmargo** [comment]
hey @amycullen2 

so does the numbers matter?

**Comment by brianamarie** [comment]
@amycullen2  There are still a few errors in your file that are keeping the tests from passing. [Click "Help Me Troubleshoot" for some specific ideas](https://services.github.com/on-demand/intro-to-github/edit-files-on-github), or [watch this video to get some help](https://vimeo.com/201011288). If you need or want help, let me know! If this hasn't been resolved by the end of next week, I'll go ahead and make the changes for you so that it can be merged in. 😄

PS It looks like you might have "trailing spaces" after one of your lines. If you edit the file, and delete any extra spaces at the end of the lines, the tests will probably pass. 
screen shot 2018-01-04 at 11 16 36 am

**Comment by amycullen2** [comment]
@brianamarie I went to try to remove the trailing spaces and when I attempt to edit the file I get this error:
screen shot 2018-01-05 at 8 04 55 am
Any idea what's up? I am signed in so I'm assuming I lost push access?

**Comment by brianamarie** [comment]
Hi @amycullen2! Yep, you're right. I'm sorry about that. We have a script that 'cleans up' collaborators, but is meant to leave people who are still working. There clearly was an error. I've reinvited you, so you should be able to [accept the invitation](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations) and continue. Sorry about this! 😊 

cc/ @crichID

**Pull request merged**
