### PR TITLE
Create Daniel54.json

### PR DESCRIPTION
**Pull request by Daniel54**
Adding Daniel54 Coordinates
@githubteacher 
This closes #3372

### CODE REVIEW

**Comment by Daniel54** [comment]
Updated number.

**Comment by Blackwolfzer** [comment]
im so confused but htis looks good

**Comment by crichID** [comment]
@Daniel54 this looks great so far, the only reason the test is failing is because you are missing the underscore at the beginning of the `_pins` directory. If you fix that it should pass!

If you need help, here is a quick video showing how to fix common problems: https://vimeo.com/201011288

**Comment by Daniel54** [comment]
@crichID Thank you. The video was helpful.

**Pull request merged**
