### PR TITLE
Add Vilnius and JolaSakala

### LINKED ISSUE #1852: Add Vilnius, Lithuania
## Adding Vilnius to the map

Hi everyone! This issue is to track the addition of Vilnius to the map, which can be found at:

- Longitude: 25.279651
- Latitude: 54.687156

### PR DESCRIPTION
**Pull request by JolaSakala**
closes #1852

### CODE REVIEW

**Comment by kylemacey** [comment]
@JolaSakala try adding `.json` to the end of your file name

**Comment by JolaSakala** [comment]
Do I should have a rights to merge? Because for some reasons I either can assign this request to me, either do merge.

**Comment by KatarzynaGut** [comment]
@JolaSakala add an image to your file :+1:

**Comment by kylemacey** [comment]
@JolaSakala leave a comment on this issue: #927 

That will automatically add you as a collaborator and give you permission to merge.

**Pull request merged**
