### PR TITLE
my json file

### PR DESCRIPTION
**Pull request by Mohitac**

### CODE REVIEW

**Comment by raoasifraza11** [comment]
You shoud close your JSON code using `---`

**Comment by Miari** [comment]
Add "---" and the and of the file and commit changes. After it hte check will be successful

**Comment by raoasifraza11** [comment]
You have add the line but I seems that you did't push it still test running on your old commit

**Comment by crichID** [comment]
@Mohitac you just need to add three dashes `---` on the last line of the file and your tests should pass. If you need any help, please check out this video: https://vimeo.com/201011288

**Pull request merged**
