### PR TITLE
Add c-martin2 pin in Columbus to map

### LINKED ISSUE #686: Adding Columbus
## Adding Columbus to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:
- Longitude: -82.998794
- Latitude: 39.961176

### PR DESCRIPTION
**Pull request by c-martin2**
Add the pin for c-martin2 following tutorial by 
@githubteacher
closes #686

### CODE REVIEW

**Comment by c-martin2** [comment]
Not sure why I am getting: 

> wrong new line character: expected \n

Any ideas @githubteacher ?

**Comment by gdeworm** [comment]
testing class

**Comment by ignotas** [comment]
I don't see what's wrong with your pull request.
Make sure you have one file added in pull request and use:
[](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/1761)
as example.

**Comment by c-martin2** [comment]
Thanks @ignotas for trying...  I think I get the gist, which is really the point of the exercise, so I will just close it.  :smile:

**Pull request closed without merging**
