### PR TITLE
add me

### PR DESCRIPTION
**Pull request by codeCesar**
Chihuahua

### CODE REVIEW

**Comment by sylvia13** [comment]
why do such errors show up?

**Comment by gabcostasilva** [comment]
You need to correct the json file
Like this
`---
+githubHandle: codeCesar \
+latitude: 28.406359 \
+longitude: -106.865407
---`

**Comment by victoriahenderson** [comment]
@codeCesar This looks great 🎉

**Comment by codeCesar** [comment]
thanks for the help everyone especially @gabcostasilva & @victoriahenderson 👍

**Pull request merged**
