### PR TITLE
This is a test while I learning Git

### PR DESCRIPTION
**Pull request by nelruk**
## Hello
I'm writing this because I want my @githubteacher say "hello world"

### CODE REVIEW

**Comment by nelruk** [comment]
This is a comment super cool xD

**Comment by Darkomage** [comment]
You should assign yourself to the pull request and merge it into master !
Nice job !

**Comment by monroeld** [comment]
👍

**Comment by oolleegg55** [comment]
It is cool, collaborators. You did good. :smile:

**Comment by gllisch** [comment]
Nice!

**Comment by jrivera27** [comment]
nice 👍

**Comment by ewallerman** [comment]
:)

**Comment by crichID** [comment]
@nelruk This looks great! It looks like you submitted your changes via a Fork so I will go ahead and merge this in for you! Thank you for participating in our activity and we hope you go on to complete [one of our other courses](https://services.github.com/on-demand/) soon.

**Pull request merged**
