### PR TITLE
Add cn222hn pin to the map

### PR DESCRIPTION
**Pull request by cn222hn**
Adding SF to the map

### CODE REVIEW

**Comment by johnstarmer** [comment]
Strange that this failed. Looks ok to me. May wish to open an issue in the repository for this class and mention @githubteacher for help from one of the GitHub trainers! Good luck.

**Comment by billyjoebaron** [comment]
commit

**Comment by marioSantos97** [comment]
@cn222hn Looking good! ;)

**Comment by hectorsector** [comment]
@cn222hn if you move your file into the `_pins` folder, it should allow the tests to pass and you'll be able to merge! This video may be helpful: https://vimeo.com/201011288

**Comment by mmdgdr** [comment]
@cn222hn looks good 👍

**Comment by gooshtie** [comment]
looks good!

**Pull request closed without merging**
