### PR TITLE
Create kemjones.json

### LINKED ISSUE #495: Atlanta, Georgia
## Adding Atlanta to the map

Hi everyone! This issue is to track the addition of Atlanta to the map, which can be found at:
- Longitude: -84.387982
- Latitude: 33.748995

### PR DESCRIPTION
**Pull request by kemjones**
Add my location to the map. @githubteacher . Closes #495

### CODE REVIEW

**Comment by luketrotta** [comment]
Your code looks good 👍

**Comment by anajera** [comment]
Your coordinates look good, I want to be added to the map also.

**Comment by hollenberry** [comment]
@kemjones This looks great! Feel free to 🚢 when ready! 👍

**Comment by hollenberry** [comment]
You might run into some unique difficulties that aren't covered in the tutorial due to use of the Fork + Pull method. Let me know if you run into any issues.

**Pull request merged**
