### PR TITLE
Coords

### LINKED ISSUE #16504: Please add me
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by BroodyE**
@githubteacher What do you think?

This pull request closes #16504 .

### CODE REVIEW

**Comment by sheenkhar** [comment]
Looks good!

**Comment by Nykelos1** [comment]
hope this work

**Comment by Nykelos1** [comment]
Nykelos1
Ellensburg

**Comment by Schiavi13** [comment]
@BroodyE You need to delete the Smithrock file

**Pull request merged**
