### PR TITLE
AspenDangren.json

### LINKED ISSUE #1140: Orlando
Hi everyone! This issue is to track the addition of Orlando to the map, which can be found at:

- Longitude: -81.3792° W
- Latitude: 28.5383° N

### PR DESCRIPTION
**Pull request by AspenDangren**
@githubteacher What do you think?
This pull request closes #1140

### CODE REVIEW

**Comment by eicholz** [comment]
@AspenDangren Looks great! :tada:

**Comment by mcb42** [comment]
@AspenDangren  Looks great!

**Comment by jwalker139** [comment]
@AspenDangren Looks Great!

**Comment by crichID** [comment]
@AspenDangren I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/2772/commits/a7b976bf14802f6bd5a9737cd0e710a96c2fb8dd. Please take a quick look at the changes. Once the tests have finished running, please feel free to click the big green **Merge pull request** button. If you haven't merged it by January 27th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
