### PR TITLE
Adding location data

### PR DESCRIPTION
**Pull request by rchillard**
# Adding location
## Data for Lat/Long

### CODE REVIEW

**Comment by shajanjp** [comment]
@rchillard You missed to add `---` in the beginning and end.
Your pin should be in this format.
```
---
githubHandle: <YOUR_USER_NAME>
latitude: <LATITUDE>
longitude: <LONGITUDE>
---
```

**Comment by a-a-ron** [comment]
Hey @rchillard, also make sure that your file is created in the `_pins` directory.

**Comment by hectorsector** [comment]
@rchillard you've got some excellent advice from both @shajanjp and @a-a-ron. [This video](https://vimeo.com/201011288) should help you fix some of the issues as well.

**Comment by hollenberry** [comment]
Hey @rchillard  ! Looks like you've gotten a ton of great advice above! If you take action on those changes, you'll be set. 👍

Please let us know if you need any help! We'll be closing this out to keep the repository clean if there's no action or conversation within the week.

**Comment by crichID** [comment]
@rchillard I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/4955/commits/527e493f260e46cd619acee09ce8b84fe4e07b4f. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by April 21st, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
