### PR TITLE
adding ubet8932 coordinates

### PR DESCRIPTION
**Pull request by ubet8932**
@githubteacher what do you think

this pull requests closes#12779

### CODE REVIEW

**Comment by ubet8932** [comment]
I am wondering why the two checks are not successful, please help @githubteacher

**Comment by shownzfx** [comment]
This looks good 👍

**Comment by shownzfx** [comment]
🎉

**Comment by Justme764** [comment]
Hello @ubet8932   Below is the correction that need to be made to your file to get all green checks.

_pins/artattc.json
 2:13      warning  too many spaces before colon  (colons)
 3:9       warning  too many spaces before colon  (colons)
 4:10      warning  too many spaces before colon  (colons)
_pins/Checkerbunny.json
 2:2       warning  wrong indentation: expected 0 but found 1  (indentation)
_pins/gilbertjones-turin.json
 2:13      warning  too many spaces before colon  (colons)
_pins/metacman.json
  :15      warning  too many spaces after colon  (colons)
_pins/nikunjmakwana008.json
 6:5       warning  too many spaces before colon  (colons)
_pins/ubet8932.json
 2:23      error    trailing spaces  (trailing-spaces)

**Comment by crichID** [comment]
@ubet8932 based on the TravisCI logs, your file is not passing the  checks because it has trailing spaces:

screen shot 2017-12-27 at 6 32 04 pm

If you need  any help making the corrections,  check out  this video: https://vimeo.com/201011288

**Comment by brianamarie** [comment]
@ubet8932 I made some changes so the tests will pass. Once everything turns green, I'll go ahead and merge this in since it's been a few days and we want to keep the repository clean. 😄 ✨

**Pull request merged**
