### PR TITLE
Create chrinimue.json

### PR DESCRIPTION
**Pull request by CHRINIMUE**
Add Chrinimue
Nice

### CODE REVIEW

**Comment by CHRINIMUE** [comment]
I hope it will pass the checks :-/

**Comment by CHRINIMUE** [comment]
xD

**Comment by beardofedu** [comment]
@CHRINIMUE I believe you need to use `.` instead of `,` in your longitude and latitude numbers.

**Comment by CHRINIMUE** [comment]
Yes, it worked ...

**Pull request merged**
