### PR TITLE
add me please

### PR DESCRIPTION
**Pull request by nikitanerurkar13**

### CODE REVIEW

**Comment by abhinishetye** [comment]
@nikitanerurkar13 this looks great

**Comment by Obsinqsob01** [comment]
See the tutorial bro! :smiley:

**Comment by ijjtseng** [comment]
@nikitanerurkar13 you are missing `---` at the beginning and end, remove `...` and the "name" label should be something else, please see the tutorial. Hope this helps!

**Comment by cakirtav** [comment]
This looks awesome @nikitanerurkar13

**Comment by susan-amin** [comment]
@nikitanerurkar13 This has some issues. Refer to @ijjtseng 's feedback!

**Comment by 0zxo** [comment]
@nikitanerurkar13

**Pull request merged**
