### PR TITLE
Susmitha dallas

### PR DESCRIPTION
**Pull request by SusmithaM**
adding dallas to the map!

### CODE REVIEW

**Comment by sskaysi56** [comment]
@SusmithaM make sure you are in the "/_pins/yourname.json" directory,

**Comment by ONYEDI** [comment]
GOOD

**Comment by beardofedu** [comment]
@SusmithaM you need to delete the `susmitha.json` but keep the `_pins/susmitha.json` file.

**Comment by kimjaydot** [comment]
@SusmithaM 
looks code

**Pull request closed without merging**
