### PR TITLE
lindamb.json

### LINKED ISSUE #6287: add me
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by Lindamb**
added my coordinates
@githubteacher

closes #6287

### CODE REVIEW

**Comment by girlscodetoo** [comment]
Good Job!

**Comment by nikkipikki** [comment]
Great job!

**Comment by nataszkan** [comment]
great!

**Comment by beardofedu** [comment]
@Lindamb This is looking good to merge, click Merge pull request when you are ready. 👍

**Pull request merged**
