### PR TITLE
add benny to the list

### PR DESCRIPTION
**Pull request by bennybian**
How do you think? Is it a good idea.

### CODE REVIEW

**Comment by Tranteon** [comment]
Hey you got this man! Just rename your file to have .json at the end of it, and make sure you add it in the _pins directory 💯

**Comment by komgcn** [comment]
your file extension needs to be .json

**Comment by EleazarRC** [comment]
@bennybian  this looks great. 👍 🌮

**Comment by Andersgrundtvig** [comment]
wow good job girls! (:

**Pull request merged**
