### PR TITLE
Added hmathies coordinates

### PR DESCRIPTION
**Pull request by hmathies**
Added longitude and latitude coordinates

### CODE REVIEW

**Comment by hmathies** [comment]
Hello @githubteacher
closes #63

**Comment by hmathies** [comment]
updated pull request

**Comment by hollenberry** [comment]
Almost there @hmathies  ! Looks like you just need to rename your file to _pins/hmathies.json. A `/` instead of a `.`. If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions! :tada:

**Comment by hollenberry** [comment]
@hmathies Looks like someone went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/10559/commits/c1300b8d56d8ab3c69b9e5b2b9f44cc4e672bbda. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by October 20th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
