### PR TITLE
Rename file and add my location

### LINKED ISSUE #36: Adding Sausalito to the map
## Adding Sausalito to the map ⛵ 

Hi everyone! This issue is to track the addition of Sausalito, CA to the map, which can be found at:

- Longitude: -122.485251
- Latitude: 37.859094

### PR DESCRIPTION
**Pull request by jroll**
creating a pin for jroll

* adding a new file for my location
* the instructions said to name the file `mymap.topojson` but there was already a file with that name since all users are told this, so I included my username in the filename; was that right to do? 😊  maybe the instructions should be changed? 

@githubteacher for your review please! 

Resolves #36

### CODE REVIEW

**Comment by jroll** [comment]
Just saw @NickTikhonov's note [here](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/28#issuecomment-225314312) that I have to remove `json` from the front of the file to make it render 👏  (cc @githubteacher to include that note in the instructions)

**Comment by brianamarie** [comment]
@jroll Awesome! 🎉 🚢 Looks great to merge!

**Comment by jroll** [comment]
Thanks @brianamarie! And for these two bits:

> the instructions said to name the file mymap.topojson but there was already a file with that name since all users are told this, so I included my username in the filename; was that right to do? 😊 maybe the instructions should be changed?

> note here that I have to remove json from the front of the file to make it render

Are these things that can/should be changed in the instructions? I'm selfishly thinking ahead to the class I'm teaching Wednesday from this tutorial 😉

**Comment by brianamarie** [comment]
@jroll Yes - thank you! We will definitely improve this. 😄

**Pull request merged**
