### PR TITLE
 _pins/wade105.json

### PR DESCRIPTION
**Pull request by wade105**
---
githubHandle: wade105
latitude: 37.8717
longitude: -122.2585
---

### CODE REVIEW

**Comment by brianamarie** [comment]
Hi @wade105!  The reason you are getting red x's is due to the file you're adding. 

Try making these changes:

1. Change the name of your file to `_pins/wade105.json`
2. Change the contents of your file to

   ```
   ---
   githubHandle: wade105
   latitude: YOUR_LATITUDE
   longitude: YOUR_LONGITUDE
   ---
   ```

**Comment by wade105** [comment]
Hi Briana,
Am very glad to have your help here.
I changed name of the file and the text as you instructed. I re-read the
Github tutorial but do not see where I would have known to name the file
_pins/wade105.json
Thank you,
Wade Daniels

**Comment by brianamarie** [comment]
Hi @wade105! 

To change the title and contents of the file,

- Click the 'files changed' button
screen shot 2016-11-01 at 12 43 30 pm

- Click the pencil to edit the file 
screen shot 2016-11-01 at 12 42 52 pm

- For the title, change it directly at the top of the page
screen shot 2016-11-01 at 12 43 03 pm

**Comment by brianamarie** [comment]
Hello again @wade105! I'm going to close this issue, since it looks like you already finished out a pin [here](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/1480). Please feel free to re-open if you'd still like to work on this branch.

**Pull request closed without merging**
