### PR TITLE
this is my favorite place:sparkling_heart:

### PR DESCRIPTION
**Pull request by AmyLiyujie**
what do you think?

### CODE REVIEW

**Comment by ElvaT** [comment]
👍

**Comment by zsu678** [comment]
(｡ì _ í｡)

**Comment by hollenberry** [comment]
Almost there @AmyLiyujie ! Just a few updates. First, you'll want to rename the file to be nested in the _pins directory. Then, you'll want some spaces after the colons on the latitude and longitude lines. And last, remove that comma! Then you should be set.

If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions!

**Comment by crichID** [comment]
@AmyLiyujie I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/6704/commits/bac5d7f77e22a38deac378da5b02c6b7d3e2a5a7. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by May 26th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
