### PR TITLE
Adding rookieGit's coordinates

### LINKED ISSUE #3063: Rookie Git User
Hello :wave:! Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by rookieGit**
@githubteacher What do you think? 

closes issue #3066

### CODE REVIEW

**Comment by rookieGit** [comment]
Check again.

**Comment by rookieGit** [comment]
push request again.

**Comment by rookieGit** [comment]
fgsdafds

**Comment by rookieGit** [comment]
commit request again.

**Comment by montysagar** [comment]
@rookieGit looks _good_

**Comment by rookieGit** [comment]
reopening pull request.

**Comment by rookieGit** [comment]
Updated coordinates 1/24/17

**Comment by crichID** [comment]
@rookieGit

**Comment by rookieGit** [comment]
@crichID thanks for deleting this branch! I was trying to find this branch to delete but was unable to find it!

**Comment by crichID** [comment]
@rookieGit no problem, just in case you are looking in the future, if you go to the **Code** tab, you will see a Git status bar that shows commits, branches, etc. If you click on branches, there will be a tab with **Yours**. You can always find the branches you created there and delete them!

**Pull request closed without merging**
