### PR TITLE
Add Oslo's coordinates

### PR DESCRIPTION
**Pull request by qewry**

### CODE REVIEW

**Comment by crichID** [comment]
@qewry I think the problem was an extra dash on the last line. I have removed that, let's see if the tests pass now. If so, feel free to press the big green button to **Merge pull request**.

**Comment by ngurney** [comment]
@qewry Looks great!

**Comment by tlmurdock** [comment]
Your changes look good!

**Comment by hectorsector** [comment]
@qewry your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on Friday, March 24

**Pull request merged**
