### PR TITLE
Add AstroBoyTHU's pin to the map

### PR DESCRIPTION
**Pull request by AstroBoyTHU**
Adding AstroBoyTHU to the map!

### CODE REVIEW

**Comment by wb2ifs** [comment]
@AstroBoyTHU great job 👍

**Comment by woodtodd** [comment]
@AstroBoyTHU  :taco

**Comment by hectorsector** [comment]
@angeloruggiero Please refrain from updating Pull Requests owned by someone else. We'd like to ensure every student has the satisfaction of working on their own branch.

@AstroBoyTHU feel free to merge when you're ready! Let us know if you have any questions.

**Comment by angeloruggiero** [comment]
Hi,

I got one of these yesterday and sure i will

but....

the training actually tells you do it without any warning ... although if 
i had thought a bit more i would of refrained

:)

**Comment by LilyWang9572** [comment]
@AstroBoyTHU Good job!

**Comment by hrune93** [comment]
@AstroBoyTHU  Great job! ✨ 🚀

**Comment by hollenberry** [comment]
Hey @AstroBoyTHU ! We'll merge this one for you tomorrow to keep the repo clean, but want to give you one last chance to click that button if you're ready!

**Pull request merged**
