### PR TITLE
add ijac's pin in map

### PR DESCRIPTION
**Pull request by ijac13**
Adding taipei to the map

### CODE REVIEW

**Comment by ijac13** [comment]
I don't understand why this failed? Sorry, cannot find any FAQ here. But I do compare my json file to others who pass checked.

**Comment by awvwgk** [comment]
@ijac13 you have to add a mention to the githubteacher and the issue you want to close to your pull request. Your coordinates are correct now.
Like this:
@githubteacher 
close #6528

**Comment by ryanmaddox** [comment]
great job

**Comment by ijac13** [comment]
@ryanmaddox Why you delete my branch? I do check my file with others that can be merged. I don't understand what's the difference. Can you tell me? Thank you.

**Comment by ijac13** [comment]
@githubteacher  can anyone help to answer me? Thank you.

**Comment by hollenberry** [comment]
Hey @ijac13 ! Sorry that your PR was closed, we're not sure why that user took that action.

I looked at your PR, and it looks great!! I deleted the extra file since you ended up with two, and the only mistake you'll need to fix is a typo! `longtitude` to `longitude`.

Please let us know if you need any help. Good work!

**Comment by hollenberry** [comment]
@ijac13  I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/6529/commits/f095183f0b2073076becc60c3b7f5da5ac3cae47 . Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by May 26, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
