### PR TITLE
Create Togedemaru.json

### LINKED ISSUE #1578: Łódź Of Sausage
## Adding Łódź Of Sausage to the map

Hi everyone! This issue is to track the addition of Łódź Of Sausage to the map, which can be found at:

- Longitude: 51.758798
- Latitude: 19.457487

### PR DESCRIPTION
**Pull request by Togedemaru**
closes #1578

### CODE REVIEW

**Comment by ZacharyMC** [comment]
no one commented on your pull request, except from me

**Comment by Togedemaru** [comment]
I hate you.
:+1:

**Comment by Stratty** [comment]
gj bronzie

**Comment by ZacharyMC** [comment]
save me from the nothing i've become :+1: 
Good Job, babes

**Comment by crichID** [comment]
@Togedemaru this looks good to merge! Please feel free to click the big green button above to **Merge pull request**.

If you haven't merged by 11/15/2016, a member of the GitHub training team will merge it for you 😉

**Pull request merged**
