### PR TITLE
creating file to add Zzyzx to map

### LINKED ISSUE #1636: DAndrewA-Zzyzx
## Adding Zzyzx to the map

Hi everyone! This issue is to track the addition of Zzyzx to the map, which can be found at:

- Longitude: -116.103890
- Latitude:   35.143341

### PR DESCRIPTION
**Pull request by DAndrewA**
closes #1636

### CODE REVIEW

**Comment by halegge** [comment]
:100: :+1: Good job my boi :+1: :100:

**Comment by joepadre** [comment]
looks good.

**Comment by crichID** [comment]
@DAndrewA this looks good to merge! Please feel free to click the big green button above to Merge pull request.

If you haven't merged by 11/15/2016, a member of the GitHub training team will merge it for you 😉

**Comment by crichID** [comment]
:+1: @DAndrewA

**Pull request merged**
