### PR TITLE
Create zacharymc.json

### LINKED ISSUE #1579: Swindon Plz Ty
## Adding Swindon to the map

Hi everyone! This issue is to track the addition of Swindon to the map, which can be found at:

- Longitude: 51.557659
- Latitude: -1.780289

### PR DESCRIPTION
**Pull request by ZacharyMC**
closes #1579

### CODE REVIEW

**Comment by Wojimus** [comment]
Woo!! # Good Job!

**Comment by Stratty** [comment]
Boosted

**Comment by Stratty** [comment]
nice job dude

**Comment by Togedemaru** [comment]
:8ball: :1234: :100:  At least you tried cuckboy.

**Comment by Wojimus** [comment]
:sparkling_heart:

**Comment by crichID** [comment]
@ZacharyMC this looks good to merge! Please feel free to click the big green button above to **Merge pull request**.

If you haven't merged by 11/15/2016, a member of the GitHub training team will merge it for you 😉

**Pull request merged**
