### PR TITLE
adding toronto coordinants

### LINKED ISSUE #9463: Please add me - Toronto, Ontario
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by kmanchu**
@githubteacher for your review

This pull request closes #9463.

### CODE REVIEW

**Comment by billchenchina** [comment]
Please go to the issue page and add an issue so that @githubteacher will make you a collaborator.
After that,merge it by your self,plz

**Comment by taylorflynt** [comment]
@kmanchu This looks great to me! Keep up the good work!

**Comment by matthew-t-smith** [comment]
@kmanchu Looks good to me 🎉

**Comment by hollenberry** [comment]
@kmanchu  your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on August 18th.

**Pull request merged**
