### PR TITLE
new pull request

### PR DESCRIPTION
**Pull request by andrearadice**

### CODE REVIEW

**Comment by brianamarie** [comment]
@andrearadice There are still a few errors in your file that are keeping the tests from passing. [Click "Help Me Troubleshoot" for some specific ideas](https://services.github.com/on-demand/intro-to-github/edit-files-on-github). If you need or want help, let me know! If this hasn't been resolved by Friday June 2nd, I'll go ahead and make the changes for you so that it can be merged in. 😄

**Comment by dronetur** [comment]
Good luck learning how to work with GitHub.
:+1:

**Comment by youngsam-byun** [comment]
@GeorgiaPreda This looks good

**Comment by youngsam-byun** [comment]
This looks good :+1:

**Pull request merged**
