### PR TITLE
A test I think, Not really sure, just following the tutorial

### PR DESCRIPTION
**Pull request by Sprieto117**
@sprieto117 I don't really know what this place or what any of this is yet, help would be much appreciated.

Pull request closing #7765  

P.s  Go YearUp Chicago

### CODE REVIEW

**Comment by Williamzhangtw** [comment]
you need to add coordinates!

**Comment by omartinez93** [comment]
Don't worry you will get there

**Comment by Sprieto117** [comment]
I did include my coordinates .

**Comment by Sprieto117** [comment]
<h2>fruitcake marzipan pudding dragee $8</h2>

**Comment by ZaneFay** [comment]
What are doing on here ?

**Comment by kidmal** [comment]
providing feedback and motivation

**Comment by hollenberry** [comment]
Almost there @Sprieto117   !

Looks like you just need to make sure to rename the file and make it a part of the _pins directory. 

Right now, it says `Sprieto117_pins.json`, but it should read `_pins/sprieto117.json`

If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions! :tada:

**Comment by hollenberry** [comment]
@Sprieto117  I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/7766/commits/85b005b78cf237b35a4c1508829bdb0a5b45bc27. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by June 30th, I will go ahead and do it just to keep the repository clean!

**Comment by gkatzioras** [comment]
@Sprieto117 This looks ok now 🎉

**Pull request merged**
