### PR TITLE
Adding New York Location

### LINKED ISSUE #14338: New Issue
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by simcha-c**
@githubteacher  Adding the New York Google location. One day will work there.

closes #14338

### CODE REVIEW

**Comment by eyemeddata** [comment]
Great job @simcha-c making progress 👍

**Comment by timruiterkamp** [comment]
Looks great 🚀

**Comment by theonejonahgold** [comment]
@simcha-c That's the spirit! I hope you'll make it there someday 😄

**Comment by jesseDijkman1** [comment]
Awesome work 👍 @simcha-c

**Comment by simcha-c** [comment]
Thanks guys!

**Pull request merged**
