### PR TITLE
trying to add brucepacific to the map

### PR DESCRIPTION
**Pull request by brucePacific**
Trying to get this to work

### CODE REVIEW

**Comment by sulphy** [comment]
@brucePacific Gotta luv github!

**Comment by ccianos** [comment]
Is there any error being thrown?

**Comment by menzacek** [comment]
Hi, I have no idea what I am doing here but I hope you are doing a great work!

**Comment by monoxpace** [comment]
keep the great work! :tada:

**Comment by brucePacific** [comment]
Thanks everyone.

**Pull request merged**
