### PR TITLE
Adding HHJorge's coordinants

### LINKED ISSUE #8076: Please add me - Gdl, Jal Mexico
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by HHJorge**
@githubteacher what do you think?

This pull request closes #8076

### CODE REVIEW

**Comment by davidnhz** [comment]
👍

**Comment by davidnhz** [comment]
You need to add your file inside the folder `_pins`

**Comment by crichID** [comment]
@HHJorge as @davidnhz mentioned, you will need to add this file to the `_pins` directory. If you need help making changes, check out this quick video we made on how to correct common issues in this activity: https://vimeo.com/201011288

**Comment by brianamarie** [comment]
@HHJorge  :wave: Let us know if you want or need any help making these changes. If in a few days the changes still aren't made, one of the GitHub trainers may make the changes for you to keep the repository clean. ✨

**Pull request merged**
