### PR TITLE
Added my coordinates

### PR DESCRIPTION
**Pull request by rlanger-wesleyan**

### CODE REVIEW

**Comment by erikhusby** [comment]
Your pull request should include a comment describing the changes made.

**Comment by tuffix** [comment]
Hej @rlanger-wesleyan,
I think you should rename your file to rlanger-wesleyan.json the rest looks fine I think
Good Luck

**Comment by tuffix** [comment]
And as @erikhusby mentioned, some kind of description in your pull-request comment would be helpful if only for yourself :)

**Comment by hollenberry** [comment]
@rlanger-wesleyan , @tuffix is absolutely right! Thanks @tuffix ! If you need any help with the rename, just let us know!

**Pull request merged**
