### PR TITLE
Create jodykarczewski.json

### PR DESCRIPTION
**Pull request by JodyKarczewski**
@githubteacher What do you think?

This pull closes #2718

### CODE REVIEW

**Comment by idanelmaleh7** [comment]
nice

**Comment by mcampbe11** [comment]
Awesome!

**Comment by VicSto** [comment]
cool!

**Comment by mkirchge** [comment]
Looks good!

**Comment by idanelmaleh7** [comment]
@JodyKarczewski  looks good

**Comment by AspenDangren** [comment]
Great work, it looks really good!

**Comment by crichID** [comment]
@JodyKarczewski I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/2719/commits/c67f92dd205d8a08d197e56e338cb1b63b8cbbcb. Please take a quick look at the changes. Once the tests have finished running, please feel free to click the big green **Merge pull request** button. If you haven't merged it by January 27th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
