### PR TITLE
Create randywang123.json

### LINKED ISSUE #11931: add @randywang123 please
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by randywang123**
Adding **myself** to the map for the workshop of UofR

-This 
-is
-a
-list

####TODO

-[ ] Things to do
-[ ] This other thing

Closes #11931

cc: @githubteacher

### CODE REVIEW

**Comment by maishaidris** [comment]
🎉

**Comment by mhelmrich** [comment]
Good job Randy! :tada:

**Comment by randywang123** [comment]
Ooops ......

**Comment by shawnchan2014** [comment]
wowowowowowwo

**Pull request merged**
