### PR TITLE
jav guadalajara <your username your city>

### PR DESCRIPTION
**Pull request by javegaibm**
Adding GDL to map!!

### CODE REVIEW

**Comment by xd-self** [comment]
all  done

**Comment by Billwolfe325** [comment]
@javegaibm   🎉

**Comment by kdeguzman101** [comment]
@javegaibm This looks awesome! :tada:

**Comment by hollenberry** [comment]
@javegaibm This looks great! If you would like your pin to appear on the map, you will need to click the big green button below to Merge pull request. Please let us know if you need any assistance.

**Pull request merged**
