### PR TITLE
Create Mnatan777.json

### PR DESCRIPTION
**Pull request by Mnatan777**
Adding Cypress to the map.

### CODE REVIEW

**Comment by brianamarie** [comment]
Hi @Mnatan777! 👋  You are SUPER close. The checks for the build are very picky, and it looks like they're picking up on some capitalization errors. Make sure the words at the front are exactly like:
```
githubHandle:
latitude:
longitude: 
```

Let me know if there's anything I can do to help! 😄

**Comment by Mnatan777** [comment]
Oh wow, you are such a huge help, thank you!

**Comment by brianamarie** [comment]
I'm taking a look at the tests now @Mnatan777

**Comment by brianamarie** [comment]
Ah! I see @Mnatan777. Right now it's named `_pin/Mnatan777.json`, and it should be `_pins/Mnatan777.json`.  To change this, just edit the file like you did before, but click the file name at the top and backspace until it will let you edit the parent folder.

**Comment by brianamarie** [comment]
@Mnatan777 Great job!!! I'm glad you stuck with it and got it working. I say you merge! 🚢

**Comment by jabumeri** [comment]
good work! :)

**Comment by Mnatan777** [comment]
Thanks so much Briana, but I had to run out the door before I could go back
and merge.  Did it automatically do the merge since it was corrected?  I
cannot wait to learn more.  My plan is to continue to learn programming but
after trying to learn some code, I found through some of the lessons I had
to learn the command line, then I realized I needed to learn Git and using
GitHub so that I could do some projects.  That is when I decided to put a
hold on the code until I learn Git and using GitHub.  Then I can proceed
with learning code and doing projects.

It is exciting stuff and I each time I learn something new just makes it
that much more fun!  Thanks for your help!

Melanie  :)

**Pull request merged**
