### PR TITLE
marioureta77

### PR DESCRIPTION
**Pull request by marioureta77**
just a prove

### CODE REVIEW

**Comment by ag6ay** [comment]
Check how you initially defined the file name ... needs path and extension

**Comment by jwmauney** [comment]
When you created the new file, there was a box above the edit area to supply the name at the
 end of a path name ending in _pins/ (about the middle of the screen).  Put your actual username-location.json in there.
Jim

**Comment by remcopasma** [comment]
This is great

**Comment by crichID** [comment]
@marioureta77 it looks like this pull request may be a duplicate - I will go ahead and close this one!

**Pull request closed without merging**
