### PR TITLE
Create Ekaparna.json

### PR DESCRIPTION
**Pull request by Ekaparna**

### CODE REVIEW

**Comment by SpacialTree** [comment]
Hey, don't forget to add the three dashes, ---, to the start and end of your file!

**Comment by jmcnly** [comment]
as @SpacialTree noted the file needs to be opened and closed with '---' 3 dashes.. Hope all is good in India, keep up the learning.... Power to the Penguin :+1:

**Comment by dagiro** [comment]
woot

**Comment by appdev734** [comment]
Hi @Ekaparna, you have this:

`GithubHandle: Ekaparna`
`Latitude:28.613939`
`Longitude:77.209021` 

Try this:

`---`
`GithubHandle: Ekaparna`
`Latitude: 28.613939`
`Longitude: 77.209021`
`---`

As noted by others, need the '---' at beginning and end. Also, elsewhere others have indicated the need for the space between ":" and username, lat, lon

**Comment by crichID** [comment]
@Ekaparna please let us know if we can help you fix this file!

**Pull request merged**
