### PR TITLE
Create gitzimm.json

### LINKED ISSUE #8910: Please add me.
Hello! :wave: Please add me as a collaborator to this repo. 
Thanks

### PR DESCRIPTION
**Pull request by gitzimm**
Add my info
@githubteacher
closes #8910

### CODE REVIEW

**Comment by gitzimm** [comment]
@githubteacher I'm not sure what I'm doing wrong... have 2 failed checks?

**Comment by sskaysi56** [comment]
Hello @gitzimm you are almost there, just missed adding dashes at the beginning and the end, remember you need to add --- .  now, you are done and go on joy the joy of merging the pull request. don't forget to delete it at the end. good luck

**Comment by estein206** [comment]
@gitzimm  Nice work! :balloon: :balloon: :balloon:

**Comment by hectorsector** [comment]
@sskaysi56 thanks for being willing to help! However, please ensure that you're allowing each participant the opportunity to fix their own issues.

**Comment by naythiha** [comment]
:shipit:

**Comment by train2o** [comment]
Potato!

**Pull request merged**
