### PR TITLE
adding a new file to github

### PR DESCRIPTION
**Pull request by harsh4you07**
tesitng my pull requests

### CODE REVIEW

**Comment by harsh4you07** [comment]
whats wrong here?

**Comment by brianamarie** [comment]
@harsh4you07  There are still a few errors in your file that are keeping the tests from passing. [Click "Help Me Troubleshoot" for some specific ideas](https://services.github.com/on-demand/intro-to-github/edit-files-on-github), or [watch this video to get some help](https://vimeo.com/201011288). If you need or want help, let me know! If this hasn't been resolved by the the end of next week, I'll go ahead and make the changes for you so that it can be merged in. 😄

**Comment by harsh4you07** [comment]
whats wrong now? i updated _pins directory. updated content and there is no leading spaces in the file.

**Comment by brianamarie** [comment]
You're so close! I think there are three main changes:
- Surround the code with `---` on the first and the last lines, just like in the example.
- When you insert your username, make sure it first says `githubHandle: `
- Change the ending of the file from `.txt` to `.json`

Let me know if you want any more help :)

**Comment by harsh4you07** [comment]
is that required in all commits? or just for this training purpose?

**Comment by brianamarie** [comment]
> is that required in all commits? or just for this training purpose?

@harsh4you07 Great question - just for this training activity. For the pins to show up on the map, these things must be in line. For other commits, there may be different needs or even no CI checks at all.

**Comment by brianamarie** [comment]
@mauriceIII Please do not close others' pull requests or issues.

**Comment by mauriceIII** [comment]
Sorry trying to unsubscribe to keep email box from filling up. Closed by mistake.

**Comment by brianamarie** [comment]
@mauriceIII this may be helpful: https://help.github.com/articles/unwatching-repositories/

**Comment by harsh4you07** [comment]
now i updated everything still checks have been failed. what is a reason now?

**Comment by brianamarie** [comment]
So close!!! I think it's a spelling error in `latitude`. Change `latitiude` to `latitude`, and we should be good to go. Thank you for your patience and working through this!

**Pull request merged**
