### PR TITLE
Create Meags.json

### PR DESCRIPTION
**Pull request by Meags10**
@githubteacher What do you think?
This pull request closes #16146

### CODE REVIEW

**Comment by pdxPackrat** [comment]
Looks great @Meags10 , at least as far as I can tell 🥇 :thumbsup:

**Comment by pdxPackrat** [comment]
@Meags10 actually - you might want to change line 2 to replace YOUR-USERNAME with your actual GitHub username (I assume that is Meags10) :smile: 

Otherwise, not sure it will associate you correctly in the map pin.

**Comment by lihaa** [comment]
@Meags10  looks great!

**Comment by aMugabi** [comment]
@Meags10 This looks great! 🎉

**Comment by StatisticianKunal** [comment]
Provide feedback :loudspeaker: and motivation :tada:.

**Comment by maxsoe** [comment]
hi @Meags10 

don't forget to merge your branch by clicking on "Merge pull request" to get your pin on the map

**Comment by Meags10** [comment]
Thanks @maxsoe!

**Pull request merged**
