### PR TITLE
Create RigoBono.json

### PR DESCRIPTION
**Pull request by RigoBono**
test
@githubteacher

### CODE REVIEW

**Comment by davidnhz** [comment]
👍

**Comment by k3z0** [comment]
good job

**Comment by YessiBarrerra** [comment]
:taco:

**Comment by pojomx** [comment]
Eres un loquillo

**Comment by crichID** [comment]
@RigoBono your checks are not passing because you have trailing spaces at the end of one of your lines of code:

screen shot 2017-07-02 at 11 42 12 am

If you need help making changes, check out this quick video we made on how to correct common issues in this activity: https://vimeo.com/201011288

**Comment by brianamarie** [comment]
@RigoBono  :wave: Let us know if you want or need any help making these changes. If in a few days the changes still aren't made, one of the GitHub trainers may make the changes for you to keep the repository clean. ✨

**Pull request merged**
