### PR TITLE
Add Chicago to map with users

### LINKED ISSUE #6: Adding Chicago to the map
## Adding Chicago to the map

Hi everyone! This issue is to track the addition of Chicago to the map, which can be found at:
- Longitude: -87.629798
- Latitude: 41.878114

### PR DESCRIPTION
**Pull request by svcastaneda**
Added Chicago to the map of users.
@githubteacher 
closes #6

### CODE REVIEW

**Comment by brianamarie** [comment]
@svcastaneda Chicago - fantastic! I'm moving there in July. 😄 

This looks good to merge! 🚢

**Comment by patriciaa** [comment]
Yay looks good!!

**Comment by brianamarie** [comment]
@svcastaneda 👋 Hello! I'd love to help you get this merge conflict figured out. Please let me know if you want some help! 

There are changes coming to this project and repository. To help get it ready, we are hoping to clean up some outstanding issues and pull requests. Unless I hear from you here, I am planning on closing this pull request without merging on **Friday, July 1st**. Thank you and happy coding! 😄

**Comment by crichID** [comment]
@svcastaneda Hi :wave: we didn't want to miss adding your pin to the map, so I went ahead and fixed the merge conflict and now I am going to merge! Thank you for completing our on-demand course and welcome to GitHub!

**Comment by kokoruz** [comment]
Adding myself into the list

**Comment by jessdaubner** [comment]
+1

**Comment by huxiaomiao0427** [comment]
> 01

**Comment by dailyherald** [comment]
Adding to the list

**Pull request merged**
