### PR TITLE
Alex gui shanghai china

### LINKED ISSUE #12849: please add me - Shanghai, China
Hello! :wave: Please add me as a collaborator to this repo. 
Longitude: 120.51
Latitude: 30.40

### PR DESCRIPTION
**Pull request by alex-gui**
@githubrobot What do you think?

This pull request closes #12849

### CODE REVIEW

**Comment by Saichethan** [comment]
Go to Travis and check the settings you should on for your repository

**Comment by Saichethan** [comment]
Check this out
Your problem will be solved in less than 3 min
https://youtu.be/rXjtDj4mqIc

**Comment by crichID** [comment]
@alex-gui your checks were failing because there was an extra file being added on your branch . I went ahead and removed the file and everything should pass now!

**Comment by aprykhus** [comment]
Great job 👏!keep up the good work 👍.

**Comment by praad** [comment]
Great job!

**Pull request merged**
