### PR TITLE
add my handler

### PR DESCRIPTION
**Pull request by tstalin22**
Hi team

### CODE REVIEW

**Comment by tstalin22** [comment]
Hi everyone! This issue is to track the addition of Seattle to the map, which can be found at:

Longitude: -122.336600
Latitude: 47.601338

**Comment by crichID** [comment]
@tstalin22 it looks like you had your file started, but you will need to add the rest of the information to the file and make a few changes. Check out this short video for help: https://vimeo.com/201011288

**Comment by shajanjp** [comment]
You are almost there, your pin should be in this format.
```
---
githubHandle: <YOUR_USER_NAME>
latitude: <LATITUDE>
longitude: <LONGITUDE>
---
```

**Comment by hectorsector** [comment]
@tstalin22 thank you for checking out our [on-demand classes](https://services.github.com/on-demand/). Since this file is not valid per the examples in the course, I am going to go ahead and close this Pull Request. If you would like to complete the activity, please feel free to re-open this Pull Request or start again. If you have any questions, please let us know!

**Pull request closed without merging**
