### PR TITLE
Create ainherst.json

### PR DESCRIPTION
**Pull request by ainherst**
Followed the tutorial on the site.

### CODE REVIEW

**Comment by shajanjp** [comment]
@ainherst Looks great ! Now press the big green **Merge pull request** button below and your coordinates will be added to the map.

**Comment by hectorsector** [comment]
Looks great @ainherst! Feel free to merge when ready.

**Comment by Xukinorris** [comment]
You did well! Feel free to merge when you're done.

**Comment by shajanjp** [comment]
Looks great ! Now press the big green **Merge pull request** button below and your coordinates will be added to the map.

**Pull request merged**
