### PR TITLE
MessidaGod first commit

### PR DESCRIPTION
**Pull request by MessiDaGod**
First commit @githubteacher

### CODE REVIEW

**Comment by brianamarie** [comment]
@MessiDaGod  There are still a few errors in your file that are keeping the tests from passing. I think that it has to do with the spelling of `latitude` and the file name ending.

[Click "Help Me Troubleshoot" for some specific ideas](https://services.github.com/on-demand/intro-to-github/edit-files-on-github), or [watch this video to get some help](https://vimeo.com/201011288). If you need or want help, let me know! If this hasn't been resolved by the the end of the week, I'll go ahead and make the changes for you so that it can be merged in. 😄

**Comment by brianamarie** [comment]
@BenAkor Please do not update other people's pull requests. Sometimes you might see someone from the GitHub training team do that, but if so, we always leave at least a few days and make sure to comment so the original poster knows what will be happening.

**Comment by BenAkor** [comment]
Okay. Thanks.

B. Youquoi ☺

**Comment by beardofedu** [comment]
Closing this as it seems to be a duplicate of this pull request: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/8393

**Pull request closed without merging**
