### PR TITLE
satyapati coordinates

### PR DESCRIPTION
**Pull request by satyapati0**
@satyapati0 pull request create successfully

### CODE REVIEW

**Comment by satyapati0** [comment]
@satya done

**Comment by satyapati0** [comment]
@stya its done

**Comment by satyapati0** [comment]
satya great job :100:

**Comment by mbrasseau** [comment]
Hello! I am new too. I noticed most people, including myself, had failed checks because of typographical errors. I would double check whether your handle is supposed to have a capital letter "O", or the number "0" that is in your code.  That is all the feedback I have. Best of luck to you.

**Comment by brianamarie** [comment]
@satyapati0 If you need or want help, let me know! If this hasn't been resolved by the the end of the week, I'll go ahead and make the changes for you so that it can be merged in. 😄

**Pull request merged**
