### PR TITLE
New Directory

### PR DESCRIPTION
**Pull request by quinmixon**
I had to create a new directory to move forward. I wasn't sure how to go back and re-do the file path.

### CODE REVIEW

**Comment by brianamarie** [comment]
Hi @quinmixon! If you erase that blank line on line 5, you should be good to merge!

**Comment by brianamarie** [comment]
Hi @quinmixon! I went ahead and made some changes. Since it's been open for a while, I'm going to merge, too. Nice work!

**Comment by brianamarie** [comment]
Hi @quinmixon! It looks like you're trying to merge this into a branch _other_ than master. Try re-creating the pull request but from your branch to master of this repository. I'm going to close this for now, but please let me know if you need any help. 😄

**Comment by quinmixon** [comment]
Ok great! Thank you for getting back to me and I will give it try.

**Pull request closed without merging**
