### PR TITLE
Create nlewendon pin json file

### PR DESCRIPTION
**Pull request by nlewendon**
@githubteacher how about it?

This pull request closes issue #9929

### CODE REVIEW

**Comment by veeraragav** [comment]
Great!!

**Comment by olesonya** [comment]
@nlewendon You are a great learner!

**Comment by hollenberry** [comment]
Almost there @nlewendon  ! Looks like you just need to remove the `+` symbols from lines 1 and 5. If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions! :tada:

**Comment by hollenberry** [comment]
@nlewendon  I went ahead and fixed the syntax issues in
https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/9930/commits/c301d55f4e6baa26f373d30d7c9fdae6dd20bb8e. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by September 22nd, I will go ahead and do it just to keep the repository clean!

**Comment by nlewendon** [comment]
@hollenberry thanks so much for your help with this!

**Pull request merged**
