### PR TITLE
Added StarryFire's pin to the map

### PR DESCRIPTION
**Pull request by StarryFire**

### CODE REVIEW

**Comment by paulepps** [comment]
@StarryFire  This looks great! 🎉

**Comment by samlovison** [comment]
@StarryFire This looks great! :raised_hands:

**Comment by webbjc-MUSC** [comment]
@StarryFire Wonderful job!

**Comment by M8A98** [comment]
Amazing! You deserve some mexican tacos :taco: :taco: :laughing:

**Comment by BrittHolcomb** [comment]
@StarryFire This looks great! 👍

**Comment by hollenberry** [comment]
@StarryFire This looks great! If you would like your pin to appear on the map, you will need to click the big green button below to Merge pull request. Please let us know if you need any assistance.

**Comment by crichID** [comment]
@StarryFire it looks like you submitted your changes via a Fork so I will go ahead and merge this in for you! Thank you for participating in our activity and we hope you go on to complete [one of our other courses](https://services.github.com/on-demand/) soon.

**Pull request merged**
