### PR TITLE
Create amaiaruano.json

### PR DESCRIPTION
**Pull request by amaiaruano**
My name is **Amaia** and I'm 21 *years old*.
[link to Google!](http://google.com) 
@mberasategi 
close #17237

### CODE REVIEW

**Comment by myrisaez** [comment]
@amaiaruano Incredible! That looks crazy! Amazing baby!

**Comment by mberridi** [comment]
Come On Amaia! You can Do It!

**Comment by mberridi** [comment]
Keep going!

**Comment by andercuriel** [comment]
You should save your file with _pins/YOUR-USERNAME.ext

**Comment by mberridi** [comment]
I provide you feedback 😃 and motivation! 🎉

**Pull request merged**
