### PR TITLE
Adding DevSiddhartha's coordinates

### LINKED ISSUE #10620: Please add me to this group
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by DevSiddhartha**
@githubteacher What do u think

This pull request closes #10620

### CODE REVIEW

**Comment by programmingprincess** [comment]
Hey! Did you still need help merging your pull request?

**Comment by DevSiddhartha** [comment]
I deleted the spaces,but the problem still persists...

**Comment by hollenberry** [comment]
Almost there @DevSiddhartha  ! Looks like you just need to add a single space after the colon on each line, following `githubStudent:` , `latitude:`, and `longitude:`. If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions! :tada:

**Comment by hollenberry** [comment]
@DevSiddhartha  I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/10624/commits/f8c7a331c6a100cba889f06a4bfeba9c4b4b01a3. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by October 27th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
