### PR TITLE
Create Josh2011.json

### LINKED ISSUE #4387: New User
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by Josh2011**
Adding new location
Great job @githubteacher 💯 
closes #4387

### CODE REVIEW

**Comment by Josh2011** [comment]
I didn't make any changes!!

**Comment by tuffix** [comment]
Hej @Josh2011 ,
change it so it looks like this:
```
---
githubHandle
Latitude
Longitude
---
```
Good Luck :)

**Comment by tuffix** [comment]
Oke @Josh2011 ,
Didn't make that clear enough, my mistake, 
```
---
githubHandle: Josh2011
Latitude: 42.499994 
Longitude: -96.400307
---
```
This should work (colon (:) followed by a space **then** your information :)
Good Luck agian

**Comment by tuffix** [comment]
think it failed again and noticed your pushing to _Pins/Josh2011.json and saw it's actually _pins/Josh2011.json (no capital P in pins), maybe that will do the trick. If not, I'm leaving this to the experts
Good Luck

**Pull request closed without merging**
