### PR TITLE
Adding seanbigler coordinates

### LINKED ISSUE #9720: Please add me
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by seanbigler**
@githubteacher Is this right?

This pull closes #9720

### CODE REVIEW

**Comment by hectorsector** [comment]
Looks great, @seanbigler! Apologies that you weren't able to create a branch directly but this is fantastic. With your permission, I'll merge it.

**Comment by seanbigler** [comment]
Yes, that would be appreciated. I was wondering why the option wasn't coming up like in the video.

**Comment by hectorsector** [comment]
@seanbigler it stems from the bug that's currently plaguing Teacherbot. You were able to still contribute by using a fork instead of creating a branch as a collaborator. Therefore, the maintainers (me) has to merge your pull request.

If you'd like to add a branch as a collaborator, you can [accept this invitation](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations), create a branch, and open a new Pull Request. That will allow you to merge it yourself.

**Comment by seanbigler** [comment]
Sounds good; however, the "accept this invitation" link doesn't seem to be working...

**Comment by hectorsector** [comment]
I just invited you again. Let me know if it works!

**Comment by seanbigler** [comment]
@hectorsector Worked great, thanks.

**Pull request merged**
