### PR TITLE
add chucoyos pin to the map

### PR DESCRIPTION
**Pull request by chucoyos**
Adding SF to the map
@githubteacher 
closes#18318

### CODE REVIEW

**Comment by midhunmanohar** [comment]
mention the training team using @githubteacher 

Use the keywords `closes` immediately followed by your issue number (e.g. closes #3)to note which Issue the Pull Request is addressing. When you do this, the issue will be automatically closed when the pull request is merge.

**Comment by JosanSun** [comment]
Oops, that seems bad!

**Comment by midhunmanohar** [comment]
@chucoyos put a space after `closes`

**Comment by midhunmanohar** [comment]
@githubteacher
closes #18318

**Comment by 0zxo** [comment]
@chucoyos

**Pull request merged**
