### PR TITLE
adding my location

### LINKED ISSUE #14727: Please add me!
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by HuffleWitch**
@githubteacher adding my coordinates on to the map

this pull request closes #14727

### CODE REVIEW

**Comment by cse031sust02** [comment]
@HuffleWitch this looks great!

**Comment by andrewbates73** [comment]
way to go! 👍

**Comment by ehounder** [comment]
Do most witches fly under the radar?

**Comment by ehounder** [comment]
Do most witches fly under the radar?

**Pull request merged**
