### PR TITLE
Created k9uma.json

### PR DESCRIPTION
**Pull request by k9uma**
My location information

### CODE REVIEW

**Comment by k9uma** [comment]
Added my location to the pins folder
@githubteacher

**Comment by CY-Zhao** [comment]
@k9uma Well done!

**Comment by hollenberry** [comment]
Almost there @k9uma  ! Looks like you just need to insert three dashes (`---`) above and below your existing lines of code. If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions! :tada:

**Comment by hollenberry** [comment]
@k9uma  I went ahead and fixed the syntax issues in https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/9968/commits/28ec5c5978a932eb6e0d66358e0f0a281b4c2fde. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by September 22nd, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
