### PR TITLE
Adding polisettyManoj coordinates

### PR DESCRIPTION
**Pull request by polisettyManoj**
Adding polisettyManoj's pin to the map. @githubteacher closes #7870

### CODE REVIEW

**Comment by polisettyManoj** [comment]
thanks for adding me!!!

**Comment by polisettyManoj** [comment]
@githubteacher  im getting error THE Travis CI build failed, please help me

**Comment by hollenberry** [comment]
Almost there @polisettyManoj  ! Looks like you just need to rename your file to be nested in the _pins directory, and also remove the degree symbols and letters from your latitude and longitude.

 If you need any help, please check out the following video: https://vimeo.com/201011288, or reach out again and let us know if you have questions! :tada:

**Comment by brianamarie** [comment]
@polisettyManoj  I made some changes so the tests will pass. Once everything turns green, I'll go ahead and merge this in since it's been a few days and we want to keep the repository clean. 😄 ✨

**Pull request merged**
