### PR TITLE
tungpv92-dallas

### PR DESCRIPTION
**Pull request by tungpv92**
@githubteacher 
closes#2

### CODE REVIEW

**Comment by MrWilliamStewart** [comment]
Hello, how is the class going for you?

**Comment by brianamarie** [comment]
Hi @tungpv92 👋  😄 

Don't forget to include "---" on the first line and last line of your file before you merge. 👍

**Comment by lindalinda12** [comment]
Just saying Hi...

**Comment by manincharge** [comment]
Adding to the issue.. for Dallas

**Pull request merged**
