### PR TITLE
Consolidate files from extra teams

### PR DESCRIPTION
**Pull request by brianamarie**
👋 Hello! If you are being messaged about this pull request, it is likely because you created a 'team' and a new repository and were doing ✨  learning there instead of on this repository. Instead of asking everyone to re-do their work, I want to add your pins now. (That's why you get this notification! 😄 ) 

**You don't need to do anything - this is just to let you know that this is happening. **

You might notice that your other repository and team are going to go away, but we don't want your pin to be gone. You'll still see it here, along with all of the other pins that are displayed on the course home page. (Note: These changes won't take effect until I merge this pull request.) 

Those who _may_ be affected: 
- @hectorsector 
- @crichID 
- @hollenberry 
- @beardofedu 
- @AndriiGitHub
- @awoerner92
- @thinhdd13
- @cito125
- @raunaksingwi
- @lijessje
- @Mohit7th

Again, no action is required - this is more of a 'heads up' from GitHub trainers that we are making corrective action so your pins will be displayed properly.

### CODE REVIEW

**Comment by brianamarie** [comment]
@amclain79, I'm mentioning you here because you fit into this category of contributors. 😄 I have moved your changes here so they will appear on this map. 🎉

**Comment by brianamarie** [comment]
@marcf08, mentioning you here for same reason as well. Sorry all for multiple pings, just want to be as thorough as possible. 😄

**Comment by beardofedu** [comment]
@brianamarie  👍

**Comment by brianamarie** [comment]
Hi @raunaksingwi! We'd love to help! 😄 I suggest clicking [this link](https://gitter.im/githubschool/on-demand) and asking any questions you have in our chat room. That way, we can really help you step by step.

**Pull request merged**
