### PR TITLE
Adding mseals1.json

### LINKED ISSUE #6099: Add me!
Hello! :wave: Please add me as a collaborator to this repo.

### PR DESCRIPTION
**Pull request by mseals1**
Adds Knoxville, TN pin to the map
closes #6099

### CODE REVIEW

**Comment by mseals1** [comment]
@githubteacher I'm not sure what the error Travis CI is outputting. Mind taking a look?

**Comment by brianamarie** [comment]
@mseals1 I'm taking a look now

**Comment by brianamarie** [comment]
@mseals1 It looks like there's something going on with the Ruby gems, I am going to look into it further, but it may take a bit of time. Thank you for your patience!

**Comment by caprewitt** [comment]
@mseals1 Thanks for asking the question. I was wondering same. 🐰

**Comment by brianamarie** [comment]
@mseals1 You're good to go! 🎉 Merge whenever you're ready, and if you don't get to it, GitHub training will merge for you by May 12th.

**Pull request merged**
