### PR TITLE
Add a new Pin for Cologne

### LINKED ISSUE #337: Adding Cologne to the map
## Adding Cologne to the map

Hi everyone! This issue is to track the addition of Cologne to the map, which can be found at:

- Longitude: 6.960279
- Latitude: 50.937531

### PR DESCRIPTION
**Pull request by jr-cologne**
Added a new Pin for Cologne to the map.

@githubteacher 

closes #337

### CODE REVIEW

**Comment by jr-cologne** [comment]
When am I allowed to merge?

**Comment by stlpatd** [comment]
##I'd like to go to an FC Koln match there!

**Comment by jr-cologne** [comment]
Why not? You can do it, if you want! :laughing: 

How do you come to a idea like that? I mean it's not a very popular club...

**Comment by stlpatd** [comment]
I became familiar with them in the days of Toni Schumacher.  That's when I first thought it would be cool to see a game there.

**Comment by jr-cologne** [comment]
Oh, okay. Interesting. :)

**Pull request merged**
