### PR TITLE
my location

### PR DESCRIPTION
**Pull request by ryf1123**
add my name, location

### CODE REVIEW

**Comment by Solehov** [comment]
You forgot @githubteacher maybe ? :) or the "closes #your_issue :)

**Comment by seemarrs** [comment]
seems you need to put in your coordinates, you can get them from [nasa's coordinate website](https://mynasadata.larc.nasa.gov/latitudelongitude-finder/) or [github's tutorial](https://services.github.com/on-demand/intro-to-github/07/) will automatically find them for you by clicking "find my coordinates automatically"

**Comment by brianamarie** [comment]
Hi @ryf1123! @seemarrs is absolutely right. Please let me know if you need help making those changes. 😄

**Comment by brianamarie** [comment]
Hi  @ryf1123! I'm going to close this pull request since the changes still need to be made and it's been a little while. Please re-open if you'd like to continue work. 😄

**Pull request closed without merging**
