### PR TITLE
Add Chinese-iProX's Pin to the World Map.

### PR DESCRIPTION
**Pull request by ByiProX**
Please give me a chance.

### CODE REVIEW

**Comment by beardofedu** [comment]
@ByiProX , @paand is correct, the file needs to be in the `_pins` directory and you need to include specific markers for the code to work. Those markers are `---` as their own line at the bottom of your code.

**Comment by beardofedu** [comment]
@ByiProX your file name also needs to match the course instructions.

**Comment by alanofbrent** [comment]
@ByiProX Please see my comment on your other open pull request.

**Comment by beardofedu** [comment]
Closing this pull request @ByiProX since you made another one.

**Pull request closed without merging**
